version: 1

merge:
  whitelist:
    labels: ["automerge"]
  method: squash
  options:
    squash:
      body: summarize_commits
  delete_after_merge: true
update:
  whitelist:
    labels: ["automerge"]

