version = "3.11.1"
maxColumn = 120
rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]
rewrite.redundantBraces.stringInterpolation = true
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.newSyntax.control = false
includeCurlyBraceInSelectChains = false
optIn.breakChainOnFirstMethodDot = false
project.git = true
project.excludeFilters = []
runner.dialect = scala3
