rules = [
  DisableSyntax
  NoValInForComprehension
  RedundantSyntax
]

DisableSyntax.noNulls = false
DisableSyntax.noReturns = true
DisableSyntax.noVars = false
DisableSyntax.noAsInstanceOf = false
DisableSyntax.noIsInstanceOf = false
DisableSyntax.noXml = true
DisableSyntax.noWhileLoops = false
