#! /usr/bin/env sh

echo "[info] Cleaning target directories..."
rm -rf target
rm -rf util/target
rm -rf project/target
rm -rf project/project/target
rm -rf webknossos-datastore/target
rm -rf webknossos-datastore/project/target
rm -rf webknossos-datastore/project/project/target
rm -rf webknossos-tracingstore/target
rm -rf webknossos-tracingstore/project/target
rm -rf webknossos-tracingstore/project/project/target
rm -rf node_modules

echo "[info] Done."
