FROM scalableminds/sbt:master__7830403826
ARG VERSION_NODE="18.x"

ENV DEBIAN_FRONTEND noninteractive
ENV SBT_OPTS "${SBT_OPTS} -XX:MaxMetaspaceSize=512m -Xms1024m -Xmx1024m"

# Fixes "The method driver /usr/lib/apt/methods/https could not be found."
# See https://unix.stackexchange.com/a/478009
RUN apt-get update && apt-get install apt-transport-https

# add node package source
RUN curl -sL "https://deb.nodesource.com/setup_${VERSION_NODE}" | bash -

# Install sbt, node & build-essentials
RUN apt-get update \
  && apt-get install -y \
  build-essential \
  findutils \
  nodejs \
  postgresql-client \
  cmake \
  git \
  libdraco-dev \
  libblosc1 \
  # The following packages are necessary to run headless-gl
  && apt-get install -y \
  mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6 pkg-config x11proto-xext-dev xserver-xorg-dev libxext-dev libxi-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Enable corepack for Node (which will install yarn)
RUN corepack enable && corepack install --global yarn@4.4.1