FROM scalableminds/sbt:master__69

ARG VERSION_NODE="8.x"

ENV DEBIAN_FRONTEND noninteractive

# add node package source
RUN curl -sL "https://deb.nodesource.com/setup_${VERSION_NODE}" | bash -

# add yarn package source
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -

# Install sbt, node & build-essentials
RUN apt-get update \
  && apt-get install -y \
      build-essential \
      findutils \
      nodejs \
      postgresql-client \
      yarn \
  # The following packages are necessary to run headless-gl
  && apt-get install -y \
      mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6 pkg-config x11proto-xext-dev xserver-xorg-dev libxext-dev libxi-dev \
  # The following packages are necessary to run chrome-headless
  && apt-get install -y wget --no-install-recommends \
      && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
      && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
      && apt-get update \
      && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
        --no-install-recommends \
      && rm -rf /var/lib/apt/lists/* \
      && apt-get purge --auto-remove -y curl \
      && rm -rf /src/*.deb

  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
