#! /usr/bin/env sh

echo "[info] Updating submodule..."
git submodule update
echo "[info] Cleaning brainflight..."
./clean
echo "[info] Building play..."
cd playframework/framework
./build publish-local

