### define
underscore : _
../pagination_collection : PaginationCollection
./task_model : TaskModel
###

class TaskCollection extends PaginationCollection

  url : "/api/user" #CHANGEME

  parse : ->
    return [
      {
        "id":"52ff30077800009b0018ae65",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"18ae65",
        "seedIdHeidelberg":0,
        "projectName":"",
        "type":{
          "summary":"ek_0563_BipolarCells",
          "description":"Check those cells out!",
          "expectedTime":{
            "min":5,
            "max":10,
            "maxHard":15
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis",
              "arbitrary"
            ],
            "branchPointsAllowed":true,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"52ff2ff6780000780018ae64"
          }
        },
        "dataSet":"2012-11-23_ex144_st08x2",
        "editPosition":[
          0,
          0,
          0
        ],
        "neededExperience":{
          "domain":"",
          "value":0
        },
        "priority":100,
        "created":"2014-02-15 17:14",
        "status":{
          "open":9,
          "inProgress":1,
          "completed":0
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"50f932cbe4b00551ae7b9d12",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7b9d12",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":7,
          "inProgress":0,
          "completed":33
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"50fd1cb7e4b04e9323f742d4",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"f742d4",
        "seedIdHeidelberg":0,
        "projectName":"",
        "type":{
          "summary":"VideoTask",
          "description":"Tracing Tasks that are used to demonstrate Oxalis in an introduction video",
          "expectedTime":{
            "min":5,
            "max":10,
            "maxHard":15
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis",
              "arbitrary"
            ],
            "branchPointsAllowed":true,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"50fd1c80e4b04e9323f742d1"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"intro",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":196,
          "inProgress":0,
          "completed":4
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9e55e4b0d636137ff023",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff023",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":15,
          "inProgress":0,
          "completed":25
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9e60e4b0d636137ff024",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff024",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":16,
          "inProgress":0,
          "completed":24
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9e6be4b0d636137ff025",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff025",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":15,
          "inProgress":0,
          "completed":25
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9ea4e4b0d636137ff026",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff026",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":16,
          "inProgress":0,
          "completed":24
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9eade4b0d636137ff027",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff027",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":14,
          "inProgress":0,
          "completed":26
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9eb5e4b0d636137ff028",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff028",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":13,
          "inProgress":0,
          "completed":27
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9ebbe4b0d636137ff029",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff029",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":14,
          "inProgress":0,
          "completed":26
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9ec2e4b0d636137ff02a",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff02a",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":15,
          "inProgress":0,
          "completed":25
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9ecae4b0d636137ff02b",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff02b",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":13,
          "inProgress":0,
          "completed":27
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9ed9e4b0d636137ff02c",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff02c",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":16,
          "inProgress":0,
          "completed":24
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9ee1e4b0d636137ff02d",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff02d",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":16,
          "inProgress":0,
          "completed":24
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9eeae4b0d636137ff02e",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff02e",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":13,
          "inProgress":0,
          "completed":27
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9ef3e4b0d636137ff02f",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff02f",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":16,
          "inProgress":0,
          "completed":24
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9efde4b0d636137ff030",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff030",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":14,
          "inProgress":0,
          "completed":26
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9f05e4b0d636137ff031",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff031",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":12,
          "inProgress":0,
          "completed":28
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9f0ce4b0d636137ff032",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff032",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":16,
          "inProgress":0,
          "completed":24
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9f14e4b0d636137ff033",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff033",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":15,
          "inProgress":0,
          "completed":25
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9f2fe4b0d636137ff034",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff034",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":15,
          "inProgress":0,
          "completed":25
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"510e9f37e4b0d636137ff035",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"7ff035",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_regularTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "oxalis"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"5113621ce4b02448f8a1784d"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"normalTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":14,
          "inProgress":0,
          "completed":26
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"51136aaee4b02448f8a178af",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"a178af",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_arbitraryTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "arbitrary"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"51136235e4b02448f8a1784e"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"arbitraryTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":13,
          "inProgress":0,
          "completed":27
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"51136ab7e4b02448f8a178b3",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"a178b3",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_arbitraryTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "arbitrary"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"51136235e4b02448f8a1784e"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"arbitraryTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":14,
          "inProgress":0,
          "completed":26
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"51136abfe4b02448f8a178b7",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"a178b7",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_arbitraryTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "arbitrary"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"51136235e4b02448f8a1784e"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"arbitraryTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":15,
          "inProgress":0,
          "completed":25
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"51136ac8e4b02448f8a178bb",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"a178bb",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_arbitraryTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "arbitrary"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"51136235e4b02448f8a1784e"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"arbitraryTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":14,
          "inProgress":0,
          "completed":26
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"51136ad1e4b02448f8a178bf",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"a178bf",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_arbitraryTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "arbitrary"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"51136235e4b02448f8a1784e"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"arbitraryTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":13,
          "inProgress":0,
          "completed":27
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"51136adae4b02448f8a178c3",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"a178c3",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_arbitraryTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "arbitrary"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"51136235e4b02448f8a1784e"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"arbitraryTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":14,
          "inProgress":0,
          "completed":26
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"51136ae5e4b02448f8a178c7",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"a178c7",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_arbitraryTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "arbitrary"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"51136235e4b02448f8a1784e"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"arbitraryTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":14,
          "inProgress":0,
          "completed":26
        },
        "isTraining":false,
        "training":null
      },
      {
        "id":"51136af1e4b02448f8a178cb",
        "team":"Structure of Neocortical Circuits Group",
        "formattedHash":"a178cb",
        "seedIdHeidelberg":0,
        "projectName":"tracingMethodsComparison",
        "type":{
          "summary":"methodComaprison_arbitraryTracing",
          "description":"",
          "expectedTime":{
            "min":1,
            "max":5,
            "maxHard":10
          },
          "team":"Structure of Neocortical Circuits Group",
          "settings":{
            "allowedModes":[
              "arbitrary"
            ],
            "branchPointsAllowed":false,
            "somaClickingAllowed":true
          },
          "_id":{
            "$oid":"51136235e4b02448f8a1784e"
          }
        },
        "dataSet":"",
        "editPosition":[
          1,
          1,
          1
        ],
        "neededExperience":{
          "domain":"arbitraryTracing",
          "value":1
        },
        "priority":100,
        "created":"2014-02-17 15:11",
        "status":{
          "open":14,
          "inProgress":0,
          "completed":26
        },
        "isTraining":false,
        "training":null
      }
    ]
