/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scalableminds_webknossos_datastore_compresso_NativeCompressoCompressor */

#ifndef _Included_com_scalableminds_webknossos_datastore_compresso_NativeCompressoCompressor
#define _Included_com_scalableminds_webknossos_datastore_compresso_NativeCompressoCompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_scalableminds_webknossos_datastore_compresso_NativeCompressoCompressor
 * Method:     decompress
 * Signature:  ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_scalableminds_webknossos_datastore_compresso_NativeCompressoCompressor_decompress
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
