/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scalableminds_webknossos_datastore_helpers_NativeBucketScanner */

#ifndef _Included_com_scalableminds_webknossos_datastore_helpers_NativeBucketScanner
#define _Included_com_scalableminds_webknossos_datastore_helpers_NativeBucketScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_scalableminds_webknossos_datastore_helpers_NativeBucketScanner
 * Method:     collectSegmentIds
 * Signature:  ([BIZ)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_scalableminds_webknossos_datastore_helpers_NativeBucketScanner_collectSegmentIds
  (JNIEnv *, jobject, jbyteArray, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
