/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scalableminds_webknossos_datastore_draco_NativeDracoToStlConverter */

#ifndef _Included_com_scalableminds_webknossos_datastore_draco_NativeDracoToStlConverter
#define _Included_com_scalableminds_webknossos_datastore_draco_NativeDracoToStlConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_scalableminds_webknossos_datastore_draco_NativeDracoToStlConverter
 * Method:     dracoToStl
 * Signature:  ([BFFFDDDI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_scalableminds_webknossos_datastore_draco_NativeDracoToStlConverter_dracoToStl
  (JNIEnv *, jobject, jbyteArray, jfloat, jfloat, jfloat, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
