/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scalableminds_webknossos_datastore_services_mcubes_NativeMarchingCubes */

#ifndef _Included_com_scalableminds_webknossos_datastore_services_mcubes_NativeMarchingCubes
#define _Included_com_scalableminds_webknossos_datastore_services_mcubes_NativeMarchingCubes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_scalableminds_webknossos_datastore_services_mcubes_NativeMarchingCubes
 * Method:     marchingCubes
 * Signature:  ([BIZJIIIFFFFFFIIIIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_scalableminds_webknossos_datastore_services_mcubes_NativeMarchingCubes_marchingCubes
  (JNIEnv *, jobject, jbyteArray, jint, jboolean, jlong, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
