// flow-typed signature: 2bdfa5b871a9cd0aa9b6321d4bb61cf2
// flow-typed version: <<STUB>>/antd_v^2.7.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'antd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'antd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'antd/dist/antd-with-locales' {
  declare module.exports: any;
}

declare module 'antd/dist/antd-with-locales.min' {
  declare module.exports: any;
}

declare module 'antd/dist/antd' {
  declare module.exports: any;
}

declare module 'antd/dist/antd.min' {
  declare module.exports: any;
}

declare module 'antd/lib/_util/getLocale' {
  declare module.exports: any;
}

declare module 'antd/lib/_util/getRequestAnimationFrame' {
  declare module.exports: any;
}

declare module 'antd/lib/_util/getScroll' {
  declare module.exports: any;
}

declare module 'antd/lib/_util/isCssAnimationSupported' {
  declare module.exports: any;
}

declare module 'antd/lib/_util/isFlexSupported' {
  declare module.exports: any;
}

declare module 'antd/lib/_util/openAnimation' {
  declare module.exports: any;
}

declare module 'antd/lib/_util/throttleByAnimationFrame' {
  declare module.exports: any;
}

declare module 'antd/lib/_util/warning' {
  declare module.exports: any;
}

declare module 'antd/lib/affix/index' {
  declare module.exports: any;
}

declare module 'antd/lib/affix/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/affix/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/alert/index' {
  declare module.exports: any;
}

declare module 'antd/lib/alert/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/alert/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/anchor/anchorHelper' {
  declare module.exports: any;
}

declare module 'antd/lib/anchor/AnchorLink' {
  declare module.exports: any;
}

declare module 'antd/lib/anchor/index' {
  declare module.exports: any;
}

declare module 'antd/lib/anchor/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/anchor/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/auto-complete/index' {
  declare module.exports: any;
}

declare module 'antd/lib/auto-complete/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/auto-complete/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/back-top/index' {
  declare module.exports: any;
}

declare module 'antd/lib/back-top/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/back-top/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/badge/index' {
  declare module.exports: any;
}

declare module 'antd/lib/badge/ScrollNumber' {
  declare module.exports: any;
}

declare module 'antd/lib/badge/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/badge/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/breadcrumb/Breadcrumb' {
  declare module.exports: any;
}

declare module 'antd/lib/breadcrumb/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'antd/lib/breadcrumb/index' {
  declare module.exports: any;
}

declare module 'antd/lib/breadcrumb/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/breadcrumb/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/button/button-group' {
  declare module.exports: any;
}

declare module 'antd/lib/button/button' {
  declare module.exports: any;
}

declare module 'antd/lib/button/index' {
  declare module.exports: any;
}

declare module 'antd/lib/button/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/button/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/Constants' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/Header' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/index' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/locale/de_DE' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/locale/en_US' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/locale/fr_BE' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/locale/pt_BR' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/locale/ru_RU' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/locale/sv_SE' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/locale/zh_CN' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/calendar/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/card/index' {
  declare module.exports: any;
}

declare module 'antd/lib/card/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/card/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/carousel/index' {
  declare module.exports: any;
}

declare module 'antd/lib/carousel/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/carousel/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/cascader/index' {
  declare module.exports: any;
}

declare module 'antd/lib/cascader/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/cascader/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/checkbox/Group' {
  declare module.exports: any;
}

declare module 'antd/lib/checkbox/index' {
  declare module.exports: any;
}

declare module 'antd/lib/checkbox/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/checkbox/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/col/index' {
  declare module.exports: any;
}

declare module 'antd/lib/col/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/col/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/collapse/index' {
  declare module.exports: any;
}

declare module 'antd/lib/collapse/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/collapse/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/Calendar' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/createPicker' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/index' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/locale/de_DE' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/locale/en_US' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/locale/fr_BE' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/locale/pt_BR' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/locale/ru_RU' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/locale/sv_SE' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/locale/zh_CN' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/RangePicker' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/date-picker/wrapPicker' {
  declare module.exports: any;
}

declare module 'antd/lib/dropdown/dropdown-button' {
  declare module.exports: any;
}

declare module 'antd/lib/dropdown/dropdown' {
  declare module.exports: any;
}

declare module 'antd/lib/dropdown/index' {
  declare module.exports: any;
}

declare module 'antd/lib/dropdown/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/dropdown/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/form/constants' {
  declare module.exports: any;
}

declare module 'antd/lib/form/Form' {
  declare module.exports: any;
}

declare module 'antd/lib/form/FormItem' {
  declare module.exports: any;
}

declare module 'antd/lib/form/index' {
  declare module.exports: any;
}

declare module 'antd/lib/form/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/form/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/grid/col' {
  declare module.exports: any;
}

declare module 'antd/lib/grid/index' {
  declare module.exports: any;
}

declare module 'antd/lib/grid/row' {
  declare module.exports: any;
}

declare module 'antd/lib/grid/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/grid/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/icon/index' {
  declare module.exports: any;
}

declare module 'antd/lib/icon/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/icon/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/index' {
  declare module.exports: any;
}

declare module 'antd/lib/input-number/index' {
  declare module.exports: any;
}

declare module 'antd/lib/input-number/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/input-number/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/input/calculateNodeHeight' {
  declare module.exports: any;
}

declare module 'antd/lib/input/Group' {
  declare module.exports: any;
}

declare module 'antd/lib/input/index' {
  declare module.exports: any;
}

declare module 'antd/lib/input/Input' {
  declare module.exports: any;
}

declare module 'antd/lib/input/Search' {
  declare module.exports: any;
}

declare module 'antd/lib/input/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/input/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/layout/index' {
  declare module.exports: any;
}

declare module 'antd/lib/layout/layout' {
  declare module.exports: any;
}

declare module 'antd/lib/layout/Sider' {
  declare module.exports: any;
}

declare module 'antd/lib/layout/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/layout/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/locale-provider/de_DE' {
  declare module.exports: any;
}

declare module 'antd/lib/locale-provider/en_US' {
  declare module.exports: any;
}

declare module 'antd/lib/locale-provider/es_ES' {
  declare module.exports: any;
}

declare module 'antd/lib/locale-provider/fr_BE' {
  declare module.exports: any;
}

declare module 'antd/lib/locale-provider/index' {
  declare module.exports: any;
}

declare module 'antd/lib/locale-provider/pt_BR' {
  declare module.exports: any;
}

declare module 'antd/lib/locale-provider/ru_RU' {
  declare module.exports: any;
}

declare module 'antd/lib/locale-provider/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/locale-provider/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/locale-provider/sv_SE' {
  declare module.exports: any;
}

declare module 'antd/lib/mention/index' {
  declare module.exports: any;
}

declare module 'antd/lib/mention/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/mention/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/menu/index' {
  declare module.exports: any;
}

declare module 'antd/lib/menu/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/menu/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/message/index' {
  declare module.exports: any;
}

declare module 'antd/lib/message/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/message/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/modal/ActionButton' {
  declare module.exports: any;
}

declare module 'antd/lib/modal/confirm' {
  declare module.exports: any;
}

declare module 'antd/lib/modal/index' {
  declare module.exports: any;
}

declare module 'antd/lib/modal/locale' {
  declare module.exports: any;
}

declare module 'antd/lib/modal/Modal' {
  declare module.exports: any;
}

declare module 'antd/lib/modal/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/modal/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/notification/index' {
  declare module.exports: any;
}

declare module 'antd/lib/notification/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/notification/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/pagination/index' {
  declare module.exports: any;
}

declare module 'antd/lib/pagination/MiniSelect' {
  declare module.exports: any;
}

declare module 'antd/lib/pagination/Pagination' {
  declare module.exports: any;
}

declare module 'antd/lib/pagination/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/pagination/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/popconfirm/index' {
  declare module.exports: any;
}

declare module 'antd/lib/popconfirm/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/popconfirm/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/popover/index' {
  declare module.exports: any;
}

declare module 'antd/lib/popover/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/popover/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/progress/index' {
  declare module.exports: any;
}

declare module 'antd/lib/progress/progress' {
  declare module.exports: any;
}

declare module 'antd/lib/progress/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/progress/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/radio/group' {
  declare module.exports: any;
}

declare module 'antd/lib/radio/index' {
  declare module.exports: any;
}

declare module 'antd/lib/radio/radio' {
  declare module.exports: any;
}

declare module 'antd/lib/radio/radioButton' {
  declare module.exports: any;
}

declare module 'antd/lib/radio/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/radio/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/rate/index' {
  declare module.exports: any;
}

declare module 'antd/lib/rate/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/rate/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/row/index' {
  declare module.exports: any;
}

declare module 'antd/lib/row/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/row/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/select/index' {
  declare module.exports: any;
}

declare module 'antd/lib/select/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/select/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/slider/index' {
  declare module.exports: any;
}

declare module 'antd/lib/slider/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/slider/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/spin/index' {
  declare module.exports: any;
}

declare module 'antd/lib/spin/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/spin/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/steps/index' {
  declare module.exports: any;
}

declare module 'antd/lib/steps/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/steps/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/switch/index' {
  declare module.exports: any;
}

declare module 'antd/lib/switch/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/switch/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/table/Column' {
  declare module.exports: any;
}

declare module 'antd/lib/table/ColumnGroup' {
  declare module.exports: any;
}

declare module 'antd/lib/table/createStore' {
  declare module.exports: any;
}

declare module 'antd/lib/table/filterDropdown' {
  declare module.exports: any;
}

declare module 'antd/lib/table/FilterDropdownMenuWrapper' {
  declare module.exports: any;
}

declare module 'antd/lib/table/index' {
  declare module.exports: any;
}

declare module 'antd/lib/table/SelectionBox' {
  declare module.exports: any;
}

declare module 'antd/lib/table/SelectionCheckboxAll' {
  declare module.exports: any;
}

declare module 'antd/lib/table/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/table/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/table/Table' {
  declare module.exports: any;
}

declare module 'antd/lib/table/util' {
  declare module.exports: any;
}

declare module 'antd/lib/tabs/index' {
  declare module.exports: any;
}

declare module 'antd/lib/tabs/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/tabs/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/tag/CheckableTag' {
  declare module.exports: any;
}

declare module 'antd/lib/tag/index' {
  declare module.exports: any;
}

declare module 'antd/lib/tag/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/tag/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/time-picker/index' {
  declare module.exports: any;
}

declare module 'antd/lib/time-picker/locale/de_DE' {
  declare module.exports: any;
}

declare module 'antd/lib/time-picker/locale/en_US' {
  declare module.exports: any;
}

declare module 'antd/lib/time-picker/locale/fr_BE' {
  declare module.exports: any;
}

declare module 'antd/lib/time-picker/locale/pt_BR' {
  declare module.exports: any;
}

declare module 'antd/lib/time-picker/locale/ru_RU' {
  declare module.exports: any;
}

declare module 'antd/lib/time-picker/locale/sv_SE' {
  declare module.exports: any;
}

declare module 'antd/lib/time-picker/locale/zh_CN' {
  declare module.exports: any;
}

declare module 'antd/lib/time-picker/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/time-picker/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/timeline/index' {
  declare module.exports: any;
}

declare module 'antd/lib/timeline/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/timeline/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/timeline/Timeline' {
  declare module.exports: any;
}

declare module 'antd/lib/timeline/TimelineItem' {
  declare module.exports: any;
}

declare module 'antd/lib/tooltip/index' {
  declare module.exports: any;
}

declare module 'antd/lib/tooltip/placements' {
  declare module.exports: any;
}

declare module 'antd/lib/tooltip/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/tooltip/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/transfer/index' {
  declare module.exports: any;
}

declare module 'antd/lib/transfer/item' {
  declare module.exports: any;
}

declare module 'antd/lib/transfer/list' {
  declare module.exports: any;
}

declare module 'antd/lib/transfer/operation' {
  declare module.exports: any;
}

declare module 'antd/lib/transfer/search' {
  declare module.exports: any;
}

declare module 'antd/lib/transfer/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/transfer/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/tree-select/index' {
  declare module.exports: any;
}

declare module 'antd/lib/tree-select/interface' {
  declare module.exports: any;
}

declare module 'antd/lib/tree-select/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/tree-select/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/tree/index' {
  declare module.exports: any;
}

declare module 'antd/lib/tree/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/tree/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/upload/getFileItem' {
  declare module.exports: any;
}

declare module 'antd/lib/upload/index' {
  declare module.exports: any;
}

declare module 'antd/lib/upload/interface' {
  declare module.exports: any;
}

declare module 'antd/lib/upload/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/upload/style/index' {
  declare module.exports: any;
}

declare module 'antd/lib/upload/uploadList' {
  declare module.exports: any;
}

declare module 'antd/lib/version/index' {
  declare module.exports: any;
}

declare module 'antd/lib/version/style/css' {
  declare module.exports: any;
}

declare module 'antd/lib/version/style/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'antd/dist/antd-with-locales.js' {
  declare module.exports: $Exports<'antd/dist/antd-with-locales'>;
}
declare module 'antd/dist/antd-with-locales.min.js' {
  declare module.exports: $Exports<'antd/dist/antd-with-locales.min'>;
}
declare module 'antd/dist/antd.js' {
  declare module.exports: $Exports<'antd/dist/antd'>;
}
declare module 'antd/dist/antd.min.js' {
  declare module.exports: $Exports<'antd/dist/antd.min'>;
}
declare module 'antd/lib/_util/getLocale.js' {
  declare module.exports: $Exports<'antd/lib/_util/getLocale'>;
}
declare module 'antd/lib/_util/getRequestAnimationFrame.js' {
  declare module.exports: $Exports<'antd/lib/_util/getRequestAnimationFrame'>;
}
declare module 'antd/lib/_util/getScroll.js' {
  declare module.exports: $Exports<'antd/lib/_util/getScroll'>;
}
declare module 'antd/lib/_util/isCssAnimationSupported.js' {
  declare module.exports: $Exports<'antd/lib/_util/isCssAnimationSupported'>;
}
declare module 'antd/lib/_util/isFlexSupported.js' {
  declare module.exports: $Exports<'antd/lib/_util/isFlexSupported'>;
}
declare module 'antd/lib/_util/openAnimation.js' {
  declare module.exports: $Exports<'antd/lib/_util/openAnimation'>;
}
declare module 'antd/lib/_util/throttleByAnimationFrame.js' {
  declare module.exports: $Exports<'antd/lib/_util/throttleByAnimationFrame'>;
}
declare module 'antd/lib/_util/warning.js' {
  declare module.exports: $Exports<'antd/lib/_util/warning'>;
}
declare module 'antd/lib/affix/index.js' {
  declare module.exports: $Exports<'antd/lib/affix/index'>;
}
declare module 'antd/lib/affix/style/css.js' {
  declare module.exports: $Exports<'antd/lib/affix/style/css'>;
}
declare module 'antd/lib/affix/style/index.js' {
  declare module.exports: $Exports<'antd/lib/affix/style/index'>;
}
declare module 'antd/lib/alert/index.js' {
  declare module.exports: $Exports<'antd/lib/alert/index'>;
}
declare module 'antd/lib/alert/style/css.js' {
  declare module.exports: $Exports<'antd/lib/alert/style/css'>;
}
declare module 'antd/lib/alert/style/index.js' {
  declare module.exports: $Exports<'antd/lib/alert/style/index'>;
}
declare module 'antd/lib/anchor/anchorHelper.js' {
  declare module.exports: $Exports<'antd/lib/anchor/anchorHelper'>;
}
declare module 'antd/lib/anchor/AnchorLink.js' {
  declare module.exports: $Exports<'antd/lib/anchor/AnchorLink'>;
}
declare module 'antd/lib/anchor/index.js' {
  declare module.exports: $Exports<'antd/lib/anchor/index'>;
}
declare module 'antd/lib/anchor/style/css.js' {
  declare module.exports: $Exports<'antd/lib/anchor/style/css'>;
}
declare module 'antd/lib/anchor/style/index.js' {
  declare module.exports: $Exports<'antd/lib/anchor/style/index'>;
}
declare module 'antd/lib/auto-complete/index.js' {
  declare module.exports: $Exports<'antd/lib/auto-complete/index'>;
}
declare module 'antd/lib/auto-complete/style/css.js' {
  declare module.exports: $Exports<'antd/lib/auto-complete/style/css'>;
}
declare module 'antd/lib/auto-complete/style/index.js' {
  declare module.exports: $Exports<'antd/lib/auto-complete/style/index'>;
}
declare module 'antd/lib/back-top/index.js' {
  declare module.exports: $Exports<'antd/lib/back-top/index'>;
}
declare module 'antd/lib/back-top/style/css.js' {
  declare module.exports: $Exports<'antd/lib/back-top/style/css'>;
}
declare module 'antd/lib/back-top/style/index.js' {
  declare module.exports: $Exports<'antd/lib/back-top/style/index'>;
}
declare module 'antd/lib/badge/index.js' {
  declare module.exports: $Exports<'antd/lib/badge/index'>;
}
declare module 'antd/lib/badge/ScrollNumber.js' {
  declare module.exports: $Exports<'antd/lib/badge/ScrollNumber'>;
}
declare module 'antd/lib/badge/style/css.js' {
  declare module.exports: $Exports<'antd/lib/badge/style/css'>;
}
declare module 'antd/lib/badge/style/index.js' {
  declare module.exports: $Exports<'antd/lib/badge/style/index'>;
}
declare module 'antd/lib/breadcrumb/Breadcrumb.js' {
  declare module.exports: $Exports<'antd/lib/breadcrumb/Breadcrumb'>;
}
declare module 'antd/lib/breadcrumb/BreadcrumbItem.js' {
  declare module.exports: $Exports<'antd/lib/breadcrumb/BreadcrumbItem'>;
}
declare module 'antd/lib/breadcrumb/index.js' {
  declare module.exports: $Exports<'antd/lib/breadcrumb/index'>;
}
declare module 'antd/lib/breadcrumb/style/css.js' {
  declare module.exports: $Exports<'antd/lib/breadcrumb/style/css'>;
}
declare module 'antd/lib/breadcrumb/style/index.js' {
  declare module.exports: $Exports<'antd/lib/breadcrumb/style/index'>;
}
declare module 'antd/lib/button/button-group.js' {
  declare module.exports: $Exports<'antd/lib/button/button-group'>;
}
declare module 'antd/lib/button/button.js' {
  declare module.exports: $Exports<'antd/lib/button/button'>;
}
declare module 'antd/lib/button/index.js' {
  declare module.exports: $Exports<'antd/lib/button/index'>;
}
declare module 'antd/lib/button/style/css.js' {
  declare module.exports: $Exports<'antd/lib/button/style/css'>;
}
declare module 'antd/lib/button/style/index.js' {
  declare module.exports: $Exports<'antd/lib/button/style/index'>;
}
declare module 'antd/lib/calendar/Constants.js' {
  declare module.exports: $Exports<'antd/lib/calendar/Constants'>;
}
declare module 'antd/lib/calendar/Header.js' {
  declare module.exports: $Exports<'antd/lib/calendar/Header'>;
}
declare module 'antd/lib/calendar/index.js' {
  declare module.exports: $Exports<'antd/lib/calendar/index'>;
}
declare module 'antd/lib/calendar/locale/de_DE.js' {
  declare module.exports: $Exports<'antd/lib/calendar/locale/de_DE'>;
}
declare module 'antd/lib/calendar/locale/en_US.js' {
  declare module.exports: $Exports<'antd/lib/calendar/locale/en_US'>;
}
declare module 'antd/lib/calendar/locale/fr_BE.js' {
  declare module.exports: $Exports<'antd/lib/calendar/locale/fr_BE'>;
}
declare module 'antd/lib/calendar/locale/pt_BR.js' {
  declare module.exports: $Exports<'antd/lib/calendar/locale/pt_BR'>;
}
declare module 'antd/lib/calendar/locale/ru_RU.js' {
  declare module.exports: $Exports<'antd/lib/calendar/locale/ru_RU'>;
}
declare module 'antd/lib/calendar/locale/sv_SE.js' {
  declare module.exports: $Exports<'antd/lib/calendar/locale/sv_SE'>;
}
declare module 'antd/lib/calendar/locale/zh_CN.js' {
  declare module.exports: $Exports<'antd/lib/calendar/locale/zh_CN'>;
}
declare module 'antd/lib/calendar/style/css.js' {
  declare module.exports: $Exports<'antd/lib/calendar/style/css'>;
}
declare module 'antd/lib/calendar/style/index.js' {
  declare module.exports: $Exports<'antd/lib/calendar/style/index'>;
}
declare module 'antd/lib/card/index.js' {
  declare module.exports: $Exports<'antd/lib/card/index'>;
}
declare module 'antd/lib/card/style/css.js' {
  declare module.exports: $Exports<'antd/lib/card/style/css'>;
}
declare module 'antd/lib/card/style/index.js' {
  declare module.exports: $Exports<'antd/lib/card/style/index'>;
}
declare module 'antd/lib/carousel/index.js' {
  declare module.exports: $Exports<'antd/lib/carousel/index'>;
}
declare module 'antd/lib/carousel/style/css.js' {
  declare module.exports: $Exports<'antd/lib/carousel/style/css'>;
}
declare module 'antd/lib/carousel/style/index.js' {
  declare module.exports: $Exports<'antd/lib/carousel/style/index'>;
}
declare module 'antd/lib/cascader/index.js' {
  declare module.exports: $Exports<'antd/lib/cascader/index'>;
}
declare module 'antd/lib/cascader/style/css.js' {
  declare module.exports: $Exports<'antd/lib/cascader/style/css'>;
}
declare module 'antd/lib/cascader/style/index.js' {
  declare module.exports: $Exports<'antd/lib/cascader/style/index'>;
}
declare module 'antd/lib/checkbox/Group.js' {
  declare module.exports: $Exports<'antd/lib/checkbox/Group'>;
}
declare module 'antd/lib/checkbox/index.js' {
  declare module.exports: $Exports<'antd/lib/checkbox/index'>;
}
declare module 'antd/lib/checkbox/style/css.js' {
  declare module.exports: $Exports<'antd/lib/checkbox/style/css'>;
}
declare module 'antd/lib/checkbox/style/index.js' {
  declare module.exports: $Exports<'antd/lib/checkbox/style/index'>;
}
declare module 'antd/lib/col/index.js' {
  declare module.exports: $Exports<'antd/lib/col/index'>;
}
declare module 'antd/lib/col/style/css.js' {
  declare module.exports: $Exports<'antd/lib/col/style/css'>;
}
declare module 'antd/lib/col/style/index.js' {
  declare module.exports: $Exports<'antd/lib/col/style/index'>;
}
declare module 'antd/lib/collapse/index.js' {
  declare module.exports: $Exports<'antd/lib/collapse/index'>;
}
declare module 'antd/lib/collapse/style/css.js' {
  declare module.exports: $Exports<'antd/lib/collapse/style/css'>;
}
declare module 'antd/lib/collapse/style/index.js' {
  declare module.exports: $Exports<'antd/lib/collapse/style/index'>;
}
declare module 'antd/lib/date-picker/Calendar.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/Calendar'>;
}
declare module 'antd/lib/date-picker/createPicker.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/createPicker'>;
}
declare module 'antd/lib/date-picker/index.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/index'>;
}
declare module 'antd/lib/date-picker/locale/de_DE.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/locale/de_DE'>;
}
declare module 'antd/lib/date-picker/locale/en_US.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/locale/en_US'>;
}
declare module 'antd/lib/date-picker/locale/fr_BE.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/locale/fr_BE'>;
}
declare module 'antd/lib/date-picker/locale/pt_BR.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/locale/pt_BR'>;
}
declare module 'antd/lib/date-picker/locale/ru_RU.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/locale/ru_RU'>;
}
declare module 'antd/lib/date-picker/locale/sv_SE.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/locale/sv_SE'>;
}
declare module 'antd/lib/date-picker/locale/zh_CN.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/locale/zh_CN'>;
}
declare module 'antd/lib/date-picker/RangePicker.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/RangePicker'>;
}
declare module 'antd/lib/date-picker/style/css.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/style/css'>;
}
declare module 'antd/lib/date-picker/style/index.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/style/index'>;
}
declare module 'antd/lib/date-picker/wrapPicker.js' {
  declare module.exports: $Exports<'antd/lib/date-picker/wrapPicker'>;
}
declare module 'antd/lib/dropdown/dropdown-button.js' {
  declare module.exports: $Exports<'antd/lib/dropdown/dropdown-button'>;
}
declare module 'antd/lib/dropdown/dropdown.js' {
  declare module.exports: $Exports<'antd/lib/dropdown/dropdown'>;
}
declare module 'antd/lib/dropdown/index.js' {
  declare module.exports: $Exports<'antd/lib/dropdown/index'>;
}
declare module 'antd/lib/dropdown/style/css.js' {
  declare module.exports: $Exports<'antd/lib/dropdown/style/css'>;
}
declare module 'antd/lib/dropdown/style/index.js' {
  declare module.exports: $Exports<'antd/lib/dropdown/style/index'>;
}
declare module 'antd/lib/form/constants.js' {
  declare module.exports: $Exports<'antd/lib/form/constants'>;
}
declare module 'antd/lib/form/Form.js' {
  declare module.exports: $Exports<'antd/lib/form/Form'>;
}
declare module 'antd/lib/form/FormItem.js' {
  declare module.exports: $Exports<'antd/lib/form/FormItem'>;
}
declare module 'antd/lib/form/index.js' {
  declare module.exports: $Exports<'antd/lib/form/index'>;
}
declare module 'antd/lib/form/style/css.js' {
  declare module.exports: $Exports<'antd/lib/form/style/css'>;
}
declare module 'antd/lib/form/style/index.js' {
  declare module.exports: $Exports<'antd/lib/form/style/index'>;
}
declare module 'antd/lib/grid/col.js' {
  declare module.exports: $Exports<'antd/lib/grid/col'>;
}
declare module 'antd/lib/grid/index.js' {
  declare module.exports: $Exports<'antd/lib/grid/index'>;
}
declare module 'antd/lib/grid/row.js' {
  declare module.exports: $Exports<'antd/lib/grid/row'>;
}
declare module 'antd/lib/grid/style/css.js' {
  declare module.exports: $Exports<'antd/lib/grid/style/css'>;
}
declare module 'antd/lib/grid/style/index.js' {
  declare module.exports: $Exports<'antd/lib/grid/style/index'>;
}
declare module 'antd/lib/icon/index.js' {
  declare module.exports: $Exports<'antd/lib/icon/index'>;
}
declare module 'antd/lib/icon/style/css.js' {
  declare module.exports: $Exports<'antd/lib/icon/style/css'>;
}
declare module 'antd/lib/icon/style/index.js' {
  declare module.exports: $Exports<'antd/lib/icon/style/index'>;
}
declare module 'antd/lib/index.js' {
  declare module.exports: $Exports<'antd/lib/index'>;
}
declare module 'antd/lib/input-number/index.js' {
  declare module.exports: $Exports<'antd/lib/input-number/index'>;
}
declare module 'antd/lib/input-number/style/css.js' {
  declare module.exports: $Exports<'antd/lib/input-number/style/css'>;
}
declare module 'antd/lib/input-number/style/index.js' {
  declare module.exports: $Exports<'antd/lib/input-number/style/index'>;
}
declare module 'antd/lib/input/calculateNodeHeight.js' {
  declare module.exports: $Exports<'antd/lib/input/calculateNodeHeight'>;
}
declare module 'antd/lib/input/Group.js' {
  declare module.exports: $Exports<'antd/lib/input/Group'>;
}
declare module 'antd/lib/input/index.js' {
  declare module.exports: $Exports<'antd/lib/input/index'>;
}
declare module 'antd/lib/input/Input.js' {
  declare module.exports: $Exports<'antd/lib/input/Input'>;
}
declare module 'antd/lib/input/Search.js' {
  declare module.exports: $Exports<'antd/lib/input/Search'>;
}
declare module 'antd/lib/input/style/css.js' {
  declare module.exports: $Exports<'antd/lib/input/style/css'>;
}
declare module 'antd/lib/input/style/index.js' {
  declare module.exports: $Exports<'antd/lib/input/style/index'>;
}
declare module 'antd/lib/layout/index.js' {
  declare module.exports: $Exports<'antd/lib/layout/index'>;
}
declare module 'antd/lib/layout/layout.js' {
  declare module.exports: $Exports<'antd/lib/layout/layout'>;
}
declare module 'antd/lib/layout/Sider.js' {
  declare module.exports: $Exports<'antd/lib/layout/Sider'>;
}
declare module 'antd/lib/layout/style/css.js' {
  declare module.exports: $Exports<'antd/lib/layout/style/css'>;
}
declare module 'antd/lib/layout/style/index.js' {
  declare module.exports: $Exports<'antd/lib/layout/style/index'>;
}
declare module 'antd/lib/locale-provider/de_DE.js' {
  declare module.exports: $Exports<'antd/lib/locale-provider/de_DE'>;
}
declare module 'antd/lib/locale-provider/en_US.js' {
  declare module.exports: $Exports<'antd/lib/locale-provider/en_US'>;
}
declare module 'antd/lib/locale-provider/es_ES.js' {
  declare module.exports: $Exports<'antd/lib/locale-provider/es_ES'>;
}
declare module 'antd/lib/locale-provider/fr_BE.js' {
  declare module.exports: $Exports<'antd/lib/locale-provider/fr_BE'>;
}
declare module 'antd/lib/locale-provider/index.js' {
  declare module.exports: $Exports<'antd/lib/locale-provider/index'>;
}
declare module 'antd/lib/locale-provider/pt_BR.js' {
  declare module.exports: $Exports<'antd/lib/locale-provider/pt_BR'>;
}
declare module 'antd/lib/locale-provider/ru_RU.js' {
  declare module.exports: $Exports<'antd/lib/locale-provider/ru_RU'>;
}
declare module 'antd/lib/locale-provider/style/css.js' {
  declare module.exports: $Exports<'antd/lib/locale-provider/style/css'>;
}
declare module 'antd/lib/locale-provider/style/index.js' {
  declare module.exports: $Exports<'antd/lib/locale-provider/style/index'>;
}
declare module 'antd/lib/locale-provider/sv_SE.js' {
  declare module.exports: $Exports<'antd/lib/locale-provider/sv_SE'>;
}
declare module 'antd/lib/mention/index.js' {
  declare module.exports: $Exports<'antd/lib/mention/index'>;
}
declare module 'antd/lib/mention/style/css.js' {
  declare module.exports: $Exports<'antd/lib/mention/style/css'>;
}
declare module 'antd/lib/mention/style/index.js' {
  declare module.exports: $Exports<'antd/lib/mention/style/index'>;
}
declare module 'antd/lib/menu/index.js' {
  declare module.exports: $Exports<'antd/lib/menu/index'>;
}
declare module 'antd/lib/menu/style/css.js' {
  declare module.exports: $Exports<'antd/lib/menu/style/css'>;
}
declare module 'antd/lib/menu/style/index.js' {
  declare module.exports: $Exports<'antd/lib/menu/style/index'>;
}
declare module 'antd/lib/message/index.js' {
  declare module.exports: $Exports<'antd/lib/message/index'>;
}
declare module 'antd/lib/message/style/css.js' {
  declare module.exports: $Exports<'antd/lib/message/style/css'>;
}
declare module 'antd/lib/message/style/index.js' {
  declare module.exports: $Exports<'antd/lib/message/style/index'>;
}
declare module 'antd/lib/modal/ActionButton.js' {
  declare module.exports: $Exports<'antd/lib/modal/ActionButton'>;
}
declare module 'antd/lib/modal/confirm.js' {
  declare module.exports: $Exports<'antd/lib/modal/confirm'>;
}
declare module 'antd/lib/modal/index.js' {
  declare module.exports: $Exports<'antd/lib/modal/index'>;
}
declare module 'antd/lib/modal/locale.js' {
  declare module.exports: $Exports<'antd/lib/modal/locale'>;
}
declare module 'antd/lib/modal/Modal.js' {
  declare module.exports: $Exports<'antd/lib/modal/Modal'>;
}
declare module 'antd/lib/modal/style/css.js' {
  declare module.exports: $Exports<'antd/lib/modal/style/css'>;
}
declare module 'antd/lib/modal/style/index.js' {
  declare module.exports: $Exports<'antd/lib/modal/style/index'>;
}
declare module 'antd/lib/notification/index.js' {
  declare module.exports: $Exports<'antd/lib/notification/index'>;
}
declare module 'antd/lib/notification/style/css.js' {
  declare module.exports: $Exports<'antd/lib/notification/style/css'>;
}
declare module 'antd/lib/notification/style/index.js' {
  declare module.exports: $Exports<'antd/lib/notification/style/index'>;
}
declare module 'antd/lib/pagination/index.js' {
  declare module.exports: $Exports<'antd/lib/pagination/index'>;
}
declare module 'antd/lib/pagination/MiniSelect.js' {
  declare module.exports: $Exports<'antd/lib/pagination/MiniSelect'>;
}
declare module 'antd/lib/pagination/Pagination.js' {
  declare module.exports: $Exports<'antd/lib/pagination/Pagination'>;
}
declare module 'antd/lib/pagination/style/css.js' {
  declare module.exports: $Exports<'antd/lib/pagination/style/css'>;
}
declare module 'antd/lib/pagination/style/index.js' {
  declare module.exports: $Exports<'antd/lib/pagination/style/index'>;
}
declare module 'antd/lib/popconfirm/index.js' {
  declare module.exports: $Exports<'antd/lib/popconfirm/index'>;
}
declare module 'antd/lib/popconfirm/style/css.js' {
  declare module.exports: $Exports<'antd/lib/popconfirm/style/css'>;
}
declare module 'antd/lib/popconfirm/style/index.js' {
  declare module.exports: $Exports<'antd/lib/popconfirm/style/index'>;
}
declare module 'antd/lib/popover/index.js' {
  declare module.exports: $Exports<'antd/lib/popover/index'>;
}
declare module 'antd/lib/popover/style/css.js' {
  declare module.exports: $Exports<'antd/lib/popover/style/css'>;
}
declare module 'antd/lib/popover/style/index.js' {
  declare module.exports: $Exports<'antd/lib/popover/style/index'>;
}
declare module 'antd/lib/progress/index.js' {
  declare module.exports: $Exports<'antd/lib/progress/index'>;
}
declare module 'antd/lib/progress/progress.js' {
  declare module.exports: $Exports<'antd/lib/progress/progress'>;
}
declare module 'antd/lib/progress/style/css.js' {
  declare module.exports: $Exports<'antd/lib/progress/style/css'>;
}
declare module 'antd/lib/progress/style/index.js' {
  declare module.exports: $Exports<'antd/lib/progress/style/index'>;
}
declare module 'antd/lib/radio/group.js' {
  declare module.exports: $Exports<'antd/lib/radio/group'>;
}
declare module 'antd/lib/radio/index.js' {
  declare module.exports: $Exports<'antd/lib/radio/index'>;
}
declare module 'antd/lib/radio/radio.js' {
  declare module.exports: $Exports<'antd/lib/radio/radio'>;
}
declare module 'antd/lib/radio/radioButton.js' {
  declare module.exports: $Exports<'antd/lib/radio/radioButton'>;
}
declare module 'antd/lib/radio/style/css.js' {
  declare module.exports: $Exports<'antd/lib/radio/style/css'>;
}
declare module 'antd/lib/radio/style/index.js' {
  declare module.exports: $Exports<'antd/lib/radio/style/index'>;
}
declare module 'antd/lib/rate/index.js' {
  declare module.exports: $Exports<'antd/lib/rate/index'>;
}
declare module 'antd/lib/rate/style/css.js' {
  declare module.exports: $Exports<'antd/lib/rate/style/css'>;
}
declare module 'antd/lib/rate/style/index.js' {
  declare module.exports: $Exports<'antd/lib/rate/style/index'>;
}
declare module 'antd/lib/row/index.js' {
  declare module.exports: $Exports<'antd/lib/row/index'>;
}
declare module 'antd/lib/row/style/css.js' {
  declare module.exports: $Exports<'antd/lib/row/style/css'>;
}
declare module 'antd/lib/row/style/index.js' {
  declare module.exports: $Exports<'antd/lib/row/style/index'>;
}
declare module 'antd/lib/select/index.js' {
  declare module.exports: $Exports<'antd/lib/select/index'>;
}
declare module 'antd/lib/select/style/css.js' {
  declare module.exports: $Exports<'antd/lib/select/style/css'>;
}
declare module 'antd/lib/select/style/index.js' {
  declare module.exports: $Exports<'antd/lib/select/style/index'>;
}
declare module 'antd/lib/slider/index.js' {
  declare module.exports: $Exports<'antd/lib/slider/index'>;
}
declare module 'antd/lib/slider/style/css.js' {
  declare module.exports: $Exports<'antd/lib/slider/style/css'>;
}
declare module 'antd/lib/slider/style/index.js' {
  declare module.exports: $Exports<'antd/lib/slider/style/index'>;
}
declare module 'antd/lib/spin/index.js' {
  declare module.exports: $Exports<'antd/lib/spin/index'>;
}
declare module 'antd/lib/spin/style/css.js' {
  declare module.exports: $Exports<'antd/lib/spin/style/css'>;
}
declare module 'antd/lib/spin/style/index.js' {
  declare module.exports: $Exports<'antd/lib/spin/style/index'>;
}
declare module 'antd/lib/steps/index.js' {
  declare module.exports: $Exports<'antd/lib/steps/index'>;
}
declare module 'antd/lib/steps/style/css.js' {
  declare module.exports: $Exports<'antd/lib/steps/style/css'>;
}
declare module 'antd/lib/steps/style/index.js' {
  declare module.exports: $Exports<'antd/lib/steps/style/index'>;
}
declare module 'antd/lib/style/css.js' {
  declare module.exports: $Exports<'antd/lib/style/css'>;
}
declare module 'antd/lib/style/index.js' {
  declare module.exports: $Exports<'antd/lib/style/index'>;
}
declare module 'antd/lib/switch/index.js' {
  declare module.exports: $Exports<'antd/lib/switch/index'>;
}
declare module 'antd/lib/switch/style/css.js' {
  declare module.exports: $Exports<'antd/lib/switch/style/css'>;
}
declare module 'antd/lib/switch/style/index.js' {
  declare module.exports: $Exports<'antd/lib/switch/style/index'>;
}
declare module 'antd/lib/table/Column.js' {
  declare module.exports: $Exports<'antd/lib/table/Column'>;
}
declare module 'antd/lib/table/ColumnGroup.js' {
  declare module.exports: $Exports<'antd/lib/table/ColumnGroup'>;
}
declare module 'antd/lib/table/createStore.js' {
  declare module.exports: $Exports<'antd/lib/table/createStore'>;
}
declare module 'antd/lib/table/filterDropdown.js' {
  declare module.exports: $Exports<'antd/lib/table/filterDropdown'>;
}
declare module 'antd/lib/table/FilterDropdownMenuWrapper.js' {
  declare module.exports: $Exports<'antd/lib/table/FilterDropdownMenuWrapper'>;
}
declare module 'antd/lib/table/index.js' {
  declare module.exports: $Exports<'antd/lib/table/index'>;
}
declare module 'antd/lib/table/SelectionBox.js' {
  declare module.exports: $Exports<'antd/lib/table/SelectionBox'>;
}
declare module 'antd/lib/table/SelectionCheckboxAll.js' {
  declare module.exports: $Exports<'antd/lib/table/SelectionCheckboxAll'>;
}
declare module 'antd/lib/table/style/css.js' {
  declare module.exports: $Exports<'antd/lib/table/style/css'>;
}
declare module 'antd/lib/table/style/index.js' {
  declare module.exports: $Exports<'antd/lib/table/style/index'>;
}
declare module 'antd/lib/table/Table.js' {
  declare module.exports: $Exports<'antd/lib/table/Table'>;
}
declare module 'antd/lib/table/util.js' {
  declare module.exports: $Exports<'antd/lib/table/util'>;
}
declare module 'antd/lib/tabs/index.js' {
  declare module.exports: $Exports<'antd/lib/tabs/index'>;
}
declare module 'antd/lib/tabs/style/css.js' {
  declare module.exports: $Exports<'antd/lib/tabs/style/css'>;
}
declare module 'antd/lib/tabs/style/index.js' {
  declare module.exports: $Exports<'antd/lib/tabs/style/index'>;
}
declare module 'antd/lib/tag/CheckableTag.js' {
  declare module.exports: $Exports<'antd/lib/tag/CheckableTag'>;
}
declare module 'antd/lib/tag/index.js' {
  declare module.exports: $Exports<'antd/lib/tag/index'>;
}
declare module 'antd/lib/tag/style/css.js' {
  declare module.exports: $Exports<'antd/lib/tag/style/css'>;
}
declare module 'antd/lib/tag/style/index.js' {
  declare module.exports: $Exports<'antd/lib/tag/style/index'>;
}
declare module 'antd/lib/time-picker/index.js' {
  declare module.exports: $Exports<'antd/lib/time-picker/index'>;
}
declare module 'antd/lib/time-picker/locale/de_DE.js' {
  declare module.exports: $Exports<'antd/lib/time-picker/locale/de_DE'>;
}
declare module 'antd/lib/time-picker/locale/en_US.js' {
  declare module.exports: $Exports<'antd/lib/time-picker/locale/en_US'>;
}
declare module 'antd/lib/time-picker/locale/fr_BE.js' {
  declare module.exports: $Exports<'antd/lib/time-picker/locale/fr_BE'>;
}
declare module 'antd/lib/time-picker/locale/pt_BR.js' {
  declare module.exports: $Exports<'antd/lib/time-picker/locale/pt_BR'>;
}
declare module 'antd/lib/time-picker/locale/ru_RU.js' {
  declare module.exports: $Exports<'antd/lib/time-picker/locale/ru_RU'>;
}
declare module 'antd/lib/time-picker/locale/sv_SE.js' {
  declare module.exports: $Exports<'antd/lib/time-picker/locale/sv_SE'>;
}
declare module 'antd/lib/time-picker/locale/zh_CN.js' {
  declare module.exports: $Exports<'antd/lib/time-picker/locale/zh_CN'>;
}
declare module 'antd/lib/time-picker/style/css.js' {
  declare module.exports: $Exports<'antd/lib/time-picker/style/css'>;
}
declare module 'antd/lib/time-picker/style/index.js' {
  declare module.exports: $Exports<'antd/lib/time-picker/style/index'>;
}
declare module 'antd/lib/timeline/index.js' {
  declare module.exports: $Exports<'antd/lib/timeline/index'>;
}
declare module 'antd/lib/timeline/style/css.js' {
  declare module.exports: $Exports<'antd/lib/timeline/style/css'>;
}
declare module 'antd/lib/timeline/style/index.js' {
  declare module.exports: $Exports<'antd/lib/timeline/style/index'>;
}
declare module 'antd/lib/timeline/Timeline.js' {
  declare module.exports: $Exports<'antd/lib/timeline/Timeline'>;
}
declare module 'antd/lib/timeline/TimelineItem.js' {
  declare module.exports: $Exports<'antd/lib/timeline/TimelineItem'>;
}
declare module 'antd/lib/tooltip/index.js' {
  declare module.exports: $Exports<'antd/lib/tooltip/index'>;
}
declare module 'antd/lib/tooltip/placements.js' {
  declare module.exports: $Exports<'antd/lib/tooltip/placements'>;
}
declare module 'antd/lib/tooltip/style/css.js' {
  declare module.exports: $Exports<'antd/lib/tooltip/style/css'>;
}
declare module 'antd/lib/tooltip/style/index.js' {
  declare module.exports: $Exports<'antd/lib/tooltip/style/index'>;
}
declare module 'antd/lib/transfer/index.js' {
  declare module.exports: $Exports<'antd/lib/transfer/index'>;
}
declare module 'antd/lib/transfer/item.js' {
  declare module.exports: $Exports<'antd/lib/transfer/item'>;
}
declare module 'antd/lib/transfer/list.js' {
  declare module.exports: $Exports<'antd/lib/transfer/list'>;
}
declare module 'antd/lib/transfer/operation.js' {
  declare module.exports: $Exports<'antd/lib/transfer/operation'>;
}
declare module 'antd/lib/transfer/search.js' {
  declare module.exports: $Exports<'antd/lib/transfer/search'>;
}
declare module 'antd/lib/transfer/style/css.js' {
  declare module.exports: $Exports<'antd/lib/transfer/style/css'>;
}
declare module 'antd/lib/transfer/style/index.js' {
  declare module.exports: $Exports<'antd/lib/transfer/style/index'>;
}
declare module 'antd/lib/tree-select/index.js' {
  declare module.exports: $Exports<'antd/lib/tree-select/index'>;
}
declare module 'antd/lib/tree-select/interface.js' {
  declare module.exports: $Exports<'antd/lib/tree-select/interface'>;
}
declare module 'antd/lib/tree-select/style/css.js' {
  declare module.exports: $Exports<'antd/lib/tree-select/style/css'>;
}
declare module 'antd/lib/tree-select/style/index.js' {
  declare module.exports: $Exports<'antd/lib/tree-select/style/index'>;
}
declare module 'antd/lib/tree/index.js' {
  declare module.exports: $Exports<'antd/lib/tree/index'>;
}
declare module 'antd/lib/tree/style/css.js' {
  declare module.exports: $Exports<'antd/lib/tree/style/css'>;
}
declare module 'antd/lib/tree/style/index.js' {
  declare module.exports: $Exports<'antd/lib/tree/style/index'>;
}
declare module 'antd/lib/upload/getFileItem.js' {
  declare module.exports: $Exports<'antd/lib/upload/getFileItem'>;
}
declare module 'antd/lib/upload/index.js' {
  declare module.exports: $Exports<'antd/lib/upload/index'>;
}
declare module 'antd/lib/upload/interface.js' {
  declare module.exports: $Exports<'antd/lib/upload/interface'>;
}
declare module 'antd/lib/upload/style/css.js' {
  declare module.exports: $Exports<'antd/lib/upload/style/css'>;
}
declare module 'antd/lib/upload/style/index.js' {
  declare module.exports: $Exports<'antd/lib/upload/style/index'>;
}
declare module 'antd/lib/upload/uploadList.js' {
  declare module.exports: $Exports<'antd/lib/upload/uploadList'>;
}
declare module 'antd/lib/version/index.js' {
  declare module.exports: $Exports<'antd/lib/version/index'>;
}
declare module 'antd/lib/version/style/css.js' {
  declare module.exports: $Exports<'antd/lib/version/style/css'>;
}
declare module 'antd/lib/version/style/index.js' {
  declare module.exports: $Exports<'antd/lib/version/style/index'>;
}
