// flow-typed signature: 112001dd73d32c3d0a0c969cebfd5335
// flow-typed version: <<STUB>>/backbone.radio_v^2.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'backbone.radio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'backbone.radio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'backbone.radio/build/backbone.radio' {
  declare module.exports: any;
}

declare module 'backbone.radio/build/backbone.radio.min' {
  declare module.exports: any;
}

declare module 'backbone.radio/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'backbone.radio/src/backbone.radio' {
  declare module.exports: any;
}

declare module 'backbone.radio/test/setup/browser' {
  declare module.exports: any;
}

declare module 'backbone.radio/test/setup/node' {
  declare module.exports: any;
}

declare module 'backbone.radio/test/setup/setup' {
  declare module.exports: any;
}

declare module 'backbone.radio/test/unit/channel' {
  declare module.exports: any;
}

declare module 'backbone.radio/test/unit/debug' {
  declare module.exports: any;
}

declare module 'backbone.radio/test/unit/form' {
  declare module.exports: any;
}

declare module 'backbone.radio/test/unit/no-conflict' {
  declare module.exports: any;
}

declare module 'backbone.radio/test/unit/requests' {
  declare module.exports: any;
}

declare module 'backbone.radio/test/unit/top-level' {
  declare module.exports: any;
}

declare module 'backbone.radio/test/unit/tune-in' {
  declare module.exports: any;
}

// Filename aliases
declare module 'backbone.radio/build/backbone.radio.js' {
  declare module.exports: $Exports<'backbone.radio/build/backbone.radio'>;
}
declare module 'backbone.radio/build/backbone.radio.min.js' {
  declare module.exports: $Exports<'backbone.radio/build/backbone.radio.min'>;
}
declare module 'backbone.radio/gulpfile.babel.js' {
  declare module.exports: $Exports<'backbone.radio/gulpfile.babel'>;
}
declare module 'backbone.radio/src/backbone.radio.js' {
  declare module.exports: $Exports<'backbone.radio/src/backbone.radio'>;
}
declare module 'backbone.radio/test/setup/browser.js' {
  declare module.exports: $Exports<'backbone.radio/test/setup/browser'>;
}
declare module 'backbone.radio/test/setup/node.js' {
  declare module.exports: $Exports<'backbone.radio/test/setup/node'>;
}
declare module 'backbone.radio/test/setup/setup.js' {
  declare module.exports: $Exports<'backbone.radio/test/setup/setup'>;
}
declare module 'backbone.radio/test/unit/channel.js' {
  declare module.exports: $Exports<'backbone.radio/test/unit/channel'>;
}
declare module 'backbone.radio/test/unit/debug.js' {
  declare module.exports: $Exports<'backbone.radio/test/unit/debug'>;
}
declare module 'backbone.radio/test/unit/form.js' {
  declare module.exports: $Exports<'backbone.radio/test/unit/form'>;
}
declare module 'backbone.radio/test/unit/no-conflict.js' {
  declare module.exports: $Exports<'backbone.radio/test/unit/no-conflict'>;
}
declare module 'backbone.radio/test/unit/requests.js' {
  declare module.exports: $Exports<'backbone.radio/test/unit/requests'>;
}
declare module 'backbone.radio/test/unit/top-level.js' {
  declare module.exports: $Exports<'backbone.radio/test/unit/top-level'>;
}
declare module 'backbone.radio/test/unit/tune-in.js' {
  declare module.exports: $Exports<'backbone.radio/test/unit/tune-in'>;
}
