// flow-typed signature: 79da31432085deb45fb7a5a71b6dba00
// flow-typed version: <<STUB>>/backbone.marionette_v^3.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'backbone.marionette'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'backbone.marionette' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'backbone.marionette/lib/backbone.marionette' {
  declare module.exports: any;
}

declare module 'backbone.marionette/lib/backbone.marionette.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'backbone.marionette/lib/backbone.marionette.js' {
  declare module.exports: $Exports<'backbone.marionette/lib/backbone.marionette'>;
}
declare module 'backbone.marionette/lib/backbone.marionette.min.js' {
  declare module.exports: $Exports<'backbone.marionette/lib/backbone.marionette.min'>;
}
