// flow-typed signature: 5ca089f1ffa098cce6192a0231454b4a
// flow-typed version: <<STUB>>/backbone-subviews_v^0.7.4/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'backbone-subviews'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'backbone-subviews' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'backbone-subviews/backbone.subviews-debug' {
  declare module.exports: any;
}

declare module 'backbone-subviews/backbone.subviews' {
  declare module.exports: any;
}

declare module 'backbone-subviews/test/lib/backbone' {
  declare module.exports: any;
}

declare module 'backbone-subviews/test/lib/jquery-1.9.1' {
  declare module.exports: any;
}

declare module 'backbone-subviews/test/lib/qunit-1.11.0' {
  declare module.exports: any;
}

declare module 'backbone-subviews/test/lib/underscore' {
  declare module.exports: any;
}

declare module 'backbone-subviews/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'backbone-subviews/backbone.subviews-debug.js' {
  declare module.exports: $Exports<'backbone-subviews/backbone.subviews-debug'>;
}
declare module 'backbone-subviews/backbone.subviews.js' {
  declare module.exports: $Exports<'backbone-subviews/backbone.subviews'>;
}
declare module 'backbone-subviews/test/lib/backbone.js' {
  declare module.exports: $Exports<'backbone-subviews/test/lib/backbone'>;
}
declare module 'backbone-subviews/test/lib/jquery-1.9.1.js' {
  declare module.exports: $Exports<'backbone-subviews/test/lib/jquery-1.9.1'>;
}
declare module 'backbone-subviews/test/lib/qunit-1.11.0.js' {
  declare module.exports: $Exports<'backbone-subviews/test/lib/qunit-1.11.0'>;
}
declare module 'backbone-subviews/test/lib/underscore.js' {
  declare module.exports: $Exports<'backbone-subviews/test/lib/underscore'>;
}
declare module 'backbone-subviews/test/tests.js' {
  declare module.exports: $Exports<'backbone-subviews/test/tests'>;
}
