// flow-typed signature: 217a3e60346a7e88e04ed35eb3ea25d8
// flow-typed version: <<STUB>>/bootstrap-toggle_v^2.2.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-toggle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-toggle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-toggle/doc/script' {
  declare module.exports: any;
}

declare module 'bootstrap-toggle/Gruntfile' {
  declare module.exports: any;
}

declare module 'bootstrap-toggle/js/bootstrap-toggle' {
  declare module.exports: any;
}

declare module 'bootstrap-toggle/js/bootstrap-toggle.min' {
  declare module.exports: any;
}

declare module 'bootstrap-toggle/js/bootstrap2-toggle' {
  declare module.exports: any;
}

declare module 'bootstrap-toggle/js/bootstrap2-toggle.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-toggle/doc/script.js' {
  declare module.exports: $Exports<'bootstrap-toggle/doc/script'>;
}
declare module 'bootstrap-toggle/Gruntfile.js' {
  declare module.exports: $Exports<'bootstrap-toggle/Gruntfile'>;
}
declare module 'bootstrap-toggle/js/bootstrap-toggle.js' {
  declare module.exports: $Exports<'bootstrap-toggle/js/bootstrap-toggle'>;
}
declare module 'bootstrap-toggle/js/bootstrap-toggle.min.js' {
  declare module.exports: $Exports<'bootstrap-toggle/js/bootstrap-toggle.min'>;
}
declare module 'bootstrap-toggle/js/bootstrap2-toggle.js' {
  declare module.exports: $Exports<'bootstrap-toggle/js/bootstrap2-toggle'>;
}
declare module 'bootstrap-toggle/js/bootstrap2-toggle.min.js' {
  declare module.exports: $Exports<'bootstrap-toggle/js/bootstrap2-toggle.min'>;
}
