// flow-typed signature: 36860f4e8aa4adab1684b1d1e1eaa513
// flow-typed version: <<STUB>>/bootstrap-multiselect_v^0.9.13/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-multiselect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-multiselect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-multiselect/dist/js/bootstrap-multiselect-collapsible-groups' {
  declare module.exports: any;
}

declare module 'bootstrap-multiselect/dist/js/bootstrap-multiselect' {
  declare module.exports: any;
}

declare module 'bootstrap-multiselect/docs/js/bootstrap-3.3.2.min' {
  declare module.exports: any;
}

declare module 'bootstrap-multiselect/docs/js/jquery-2.1.3.min' {
  declare module.exports: any;
}

declare module 'bootstrap-multiselect/docs/js/prettify' {
  declare module.exports: any;
}

declare module 'bootstrap-multiselect/tests/lib/jasmine-2.0.2/boot' {
  declare module.exports: any;
}

declare module 'bootstrap-multiselect/tests/lib/jasmine-2.0.2/console' {
  declare module.exports: any;
}

declare module 'bootstrap-multiselect/tests/lib/jasmine-2.0.2/jasmine-html' {
  declare module.exports: any;
}

declare module 'bootstrap-multiselect/tests/lib/jasmine-2.0.2/jasmine' {
  declare module.exports: any;
}

declare module 'bootstrap-multiselect/tests/spec/bootstrap-multiselect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-multiselect/dist/js/bootstrap-multiselect-collapsible-groups.js' {
  declare module.exports: $Exports<'bootstrap-multiselect/dist/js/bootstrap-multiselect-collapsible-groups'>;
}
declare module 'bootstrap-multiselect/dist/js/bootstrap-multiselect.js' {
  declare module.exports: $Exports<'bootstrap-multiselect/dist/js/bootstrap-multiselect'>;
}
declare module 'bootstrap-multiselect/docs/js/bootstrap-3.3.2.min.js' {
  declare module.exports: $Exports<'bootstrap-multiselect/docs/js/bootstrap-3.3.2.min'>;
}
declare module 'bootstrap-multiselect/docs/js/jquery-2.1.3.min.js' {
  declare module.exports: $Exports<'bootstrap-multiselect/docs/js/jquery-2.1.3.min'>;
}
declare module 'bootstrap-multiselect/docs/js/prettify.js' {
  declare module.exports: $Exports<'bootstrap-multiselect/docs/js/prettify'>;
}
declare module 'bootstrap-multiselect/tests/lib/jasmine-2.0.2/boot.js' {
  declare module.exports: $Exports<'bootstrap-multiselect/tests/lib/jasmine-2.0.2/boot'>;
}
declare module 'bootstrap-multiselect/tests/lib/jasmine-2.0.2/console.js' {
  declare module.exports: $Exports<'bootstrap-multiselect/tests/lib/jasmine-2.0.2/console'>;
}
declare module 'bootstrap-multiselect/tests/lib/jasmine-2.0.2/jasmine-html.js' {
  declare module.exports: $Exports<'bootstrap-multiselect/tests/lib/jasmine-2.0.2/jasmine-html'>;
}
declare module 'bootstrap-multiselect/tests/lib/jasmine-2.0.2/jasmine.js' {
  declare module.exports: $Exports<'bootstrap-multiselect/tests/lib/jasmine-2.0.2/jasmine'>;
}
declare module 'bootstrap-multiselect/tests/spec/bootstrap-multiselect.js' {
  declare module.exports: $Exports<'bootstrap-multiselect/tests/spec/bootstrap-multiselect'>;
}
