// flow-typed signature: d809ff32665f9d422afb9de32e5faf13
// flow-typed version: <<STUB>>/bootstrap-daterangepicker_v^2.1.17/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-daterangepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-daterangepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-daterangepicker/daterangepicker' {
  declare module.exports: any;
}

declare module 'bootstrap-daterangepicker/example/amd/main' {
  declare module.exports: any;
}

declare module 'bootstrap-daterangepicker/example/amd/require' {
  declare module.exports: any;
}

declare module 'bootstrap-daterangepicker/example/browserify/bundle' {
  declare module.exports: any;
}

declare module 'bootstrap-daterangepicker/example/browserify/main' {
  declare module.exports: any;
}

declare module 'bootstrap-daterangepicker/moment' {
  declare module.exports: any;
}

declare module 'bootstrap-daterangepicker/moment.min' {
  declare module.exports: any;
}

declare module 'bootstrap-daterangepicker/package' {
  declare module.exports: any;
}

declare module 'bootstrap-daterangepicker/website' {
  declare module.exports: any;
}

declare module 'bootstrap-daterangepicker/website/website' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-daterangepicker/daterangepicker.js' {
  declare module.exports: $Exports<'bootstrap-daterangepicker/daterangepicker'>;
}
declare module 'bootstrap-daterangepicker/example/amd/main.js' {
  declare module.exports: $Exports<'bootstrap-daterangepicker/example/amd/main'>;
}
declare module 'bootstrap-daterangepicker/example/amd/require.js' {
  declare module.exports: $Exports<'bootstrap-daterangepicker/example/amd/require'>;
}
declare module 'bootstrap-daterangepicker/example/browserify/bundle.js' {
  declare module.exports: $Exports<'bootstrap-daterangepicker/example/browserify/bundle'>;
}
declare module 'bootstrap-daterangepicker/example/browserify/main.js' {
  declare module.exports: $Exports<'bootstrap-daterangepicker/example/browserify/main'>;
}
declare module 'bootstrap-daterangepicker/moment.js' {
  declare module.exports: $Exports<'bootstrap-daterangepicker/moment'>;
}
declare module 'bootstrap-daterangepicker/moment.min.js' {
  declare module.exports: $Exports<'bootstrap-daterangepicker/moment.min'>;
}
declare module 'bootstrap-daterangepicker/package.js' {
  declare module.exports: $Exports<'bootstrap-daterangepicker/package'>;
}
declare module 'bootstrap-daterangepicker/website.js' {
  declare module.exports: $Exports<'bootstrap-daterangepicker/website'>;
}
declare module 'bootstrap-daterangepicker/website/website.js' {
  declare module.exports: $Exports<'bootstrap-daterangepicker/website/website'>;
}
