// flow-typed signature: b7f3ec3c6c60df1d087d604bcaeb1a57
// flow-typed version: <<STUB>>/brace_v^0.8.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'brace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'brace/example/build' {
  declare module.exports: any;
}

declare module 'brace/example/coffee-editor' {
  declare module.exports: any;
}

declare module 'brace/example/css-editor' {
  declare module.exports: any;
}

declare module 'brace/example/javascript-editor' {
  declare module.exports: any;
}

declare module 'brace/example/json-editor' {
  declare module.exports: any;
}

declare module 'brace/example/lua-editor' {
  declare module.exports: any;
}

declare module 'brace/ext/beautify' {
  declare module.exports: any;
}

declare module 'brace/ext/chromevox' {
  declare module.exports: any;
}

declare module 'brace/ext/elastic_tabstops_lite' {
  declare module.exports: any;
}

declare module 'brace/ext/emmet' {
  declare module.exports: any;
}

declare module 'brace/ext/error_marker' {
  declare module.exports: any;
}

declare module 'brace/ext/keybinding_menu' {
  declare module.exports: any;
}

declare module 'brace/ext/language_tools' {
  declare module.exports: any;
}

declare module 'brace/ext/linking' {
  declare module.exports: any;
}

declare module 'brace/ext/modelist' {
  declare module.exports: any;
}

declare module 'brace/ext/old_ie' {
  declare module.exports: any;
}

declare module 'brace/ext/searchbox' {
  declare module.exports: any;
}

declare module 'brace/ext/settings_menu' {
  declare module.exports: any;
}

declare module 'brace/ext/spellcheck' {
  declare module.exports: any;
}

declare module 'brace/ext/split' {
  declare module.exports: any;
}

declare module 'brace/ext/static_highlight' {
  declare module.exports: any;
}

declare module 'brace/ext/statusbar' {
  declare module.exports: any;
}

declare module 'brace/ext/textarea' {
  declare module.exports: any;
}

declare module 'brace/ext/themelist' {
  declare module.exports: any;
}

declare module 'brace/ext/whitespace' {
  declare module.exports: any;
}

declare module 'brace/keybinding/emacs' {
  declare module.exports: any;
}

declare module 'brace/keybinding/vim' {
  declare module.exports: any;
}

declare module 'brace/mode/abap' {
  declare module.exports: any;
}

declare module 'brace/mode/abc' {
  declare module.exports: any;
}

declare module 'brace/mode/actionscript' {
  declare module.exports: any;
}

declare module 'brace/mode/ada' {
  declare module.exports: any;
}

declare module 'brace/mode/apache_conf' {
  declare module.exports: any;
}

declare module 'brace/mode/applescript' {
  declare module.exports: any;
}

declare module 'brace/mode/asciidoc' {
  declare module.exports: any;
}

declare module 'brace/mode/assembly_x86' {
  declare module.exports: any;
}

declare module 'brace/mode/autohotkey' {
  declare module.exports: any;
}

declare module 'brace/mode/batchfile' {
  declare module.exports: any;
}

declare module 'brace/mode/c_cpp' {
  declare module.exports: any;
}

declare module 'brace/mode/c9search' {
  declare module.exports: any;
}

declare module 'brace/mode/cirru' {
  declare module.exports: any;
}

declare module 'brace/mode/clojure' {
  declare module.exports: any;
}

declare module 'brace/mode/cobol' {
  declare module.exports: any;
}

declare module 'brace/mode/coffee' {
  declare module.exports: any;
}

declare module 'brace/mode/coldfusion' {
  declare module.exports: any;
}

declare module 'brace/mode/csharp' {
  declare module.exports: any;
}

declare module 'brace/mode/css' {
  declare module.exports: any;
}

declare module 'brace/mode/curly' {
  declare module.exports: any;
}

declare module 'brace/mode/d' {
  declare module.exports: any;
}

declare module 'brace/mode/dart' {
  declare module.exports: any;
}

declare module 'brace/mode/diff' {
  declare module.exports: any;
}

declare module 'brace/mode/django' {
  declare module.exports: any;
}

declare module 'brace/mode/dockerfile' {
  declare module.exports: any;
}

declare module 'brace/mode/dot' {
  declare module.exports: any;
}

declare module 'brace/mode/eiffel' {
  declare module.exports: any;
}

declare module 'brace/mode/ejs' {
  declare module.exports: any;
}

declare module 'brace/mode/elixir' {
  declare module.exports: any;
}

declare module 'brace/mode/elm' {
  declare module.exports: any;
}

declare module 'brace/mode/erlang' {
  declare module.exports: any;
}

declare module 'brace/mode/forth' {
  declare module.exports: any;
}

declare module 'brace/mode/ftl' {
  declare module.exports: any;
}

declare module 'brace/mode/gcode' {
  declare module.exports: any;
}

declare module 'brace/mode/gherkin' {
  declare module.exports: any;
}

declare module 'brace/mode/gitignore' {
  declare module.exports: any;
}

declare module 'brace/mode/glsl' {
  declare module.exports: any;
}

declare module 'brace/mode/gobstones' {
  declare module.exports: any;
}

declare module 'brace/mode/golang' {
  declare module.exports: any;
}

declare module 'brace/mode/groovy' {
  declare module.exports: any;
}

declare module 'brace/mode/haml' {
  declare module.exports: any;
}

declare module 'brace/mode/handlebars' {
  declare module.exports: any;
}

declare module 'brace/mode/haskell' {
  declare module.exports: any;
}

declare module 'brace/mode/haxe' {
  declare module.exports: any;
}

declare module 'brace/mode/html_elixir' {
  declare module.exports: any;
}

declare module 'brace/mode/html_ruby' {
  declare module.exports: any;
}

declare module 'brace/mode/html' {
  declare module.exports: any;
}

declare module 'brace/mode/ini' {
  declare module.exports: any;
}

declare module 'brace/mode/io' {
  declare module.exports: any;
}

declare module 'brace/mode/jack' {
  declare module.exports: any;
}

declare module 'brace/mode/jade' {
  declare module.exports: any;
}

declare module 'brace/mode/java' {
  declare module.exports: any;
}

declare module 'brace/mode/javascript' {
  declare module.exports: any;
}

declare module 'brace/mode/json' {
  declare module.exports: any;
}

declare module 'brace/mode/jsoniq' {
  declare module.exports: any;
}

declare module 'brace/mode/jsp' {
  declare module.exports: any;
}

declare module 'brace/mode/jsx' {
  declare module.exports: any;
}

declare module 'brace/mode/julia' {
  declare module.exports: any;
}

declare module 'brace/mode/latex' {
  declare module.exports: any;
}

declare module 'brace/mode/lean' {
  declare module.exports: any;
}

declare module 'brace/mode/less' {
  declare module.exports: any;
}

declare module 'brace/mode/liquid' {
  declare module.exports: any;
}

declare module 'brace/mode/lisp' {
  declare module.exports: any;
}

declare module 'brace/mode/live_script' {
  declare module.exports: any;
}

declare module 'brace/mode/livescript' {
  declare module.exports: any;
}

declare module 'brace/mode/logiql' {
  declare module.exports: any;
}

declare module 'brace/mode/lsl' {
  declare module.exports: any;
}

declare module 'brace/mode/lua' {
  declare module.exports: any;
}

declare module 'brace/mode/luapage' {
  declare module.exports: any;
}

declare module 'brace/mode/lucene' {
  declare module.exports: any;
}

declare module 'brace/mode/makefile' {
  declare module.exports: any;
}

declare module 'brace/mode/markdown' {
  declare module.exports: any;
}

declare module 'brace/mode/mask' {
  declare module.exports: any;
}

declare module 'brace/mode/matlab' {
  declare module.exports: any;
}

declare module 'brace/mode/mavens_mate_log' {
  declare module.exports: any;
}

declare module 'brace/mode/maze' {
  declare module.exports: any;
}

declare module 'brace/mode/mel' {
  declare module.exports: any;
}

declare module 'brace/mode/mips_assembler' {
  declare module.exports: any;
}

declare module 'brace/mode/mipsassembler' {
  declare module.exports: any;
}

declare module 'brace/mode/mushcode' {
  declare module.exports: any;
}

declare module 'brace/mode/mysql' {
  declare module.exports: any;
}

declare module 'brace/mode/nix' {
  declare module.exports: any;
}

declare module 'brace/mode/nsis' {
  declare module.exports: any;
}

declare module 'brace/mode/objectivec' {
  declare module.exports: any;
}

declare module 'brace/mode/ocaml' {
  declare module.exports: any;
}

declare module 'brace/mode/pascal' {
  declare module.exports: any;
}

declare module 'brace/mode/perl' {
  declare module.exports: any;
}

declare module 'brace/mode/pgsql' {
  declare module.exports: any;
}

declare module 'brace/mode/php' {
  declare module.exports: any;
}

declare module 'brace/mode/plain_text' {
  declare module.exports: any;
}

declare module 'brace/mode/powershell' {
  declare module.exports: any;
}

declare module 'brace/mode/praat' {
  declare module.exports: any;
}

declare module 'brace/mode/prolog' {
  declare module.exports: any;
}

declare module 'brace/mode/properties' {
  declare module.exports: any;
}

declare module 'brace/mode/protobuf' {
  declare module.exports: any;
}

declare module 'brace/mode/python' {
  declare module.exports: any;
}

declare module 'brace/mode/r' {
  declare module.exports: any;
}

declare module 'brace/mode/razor' {
  declare module.exports: any;
}

declare module 'brace/mode/rdoc' {
  declare module.exports: any;
}

declare module 'brace/mode/rhtml' {
  declare module.exports: any;
}

declare module 'brace/mode/rst' {
  declare module.exports: any;
}

declare module 'brace/mode/ruby' {
  declare module.exports: any;
}

declare module 'brace/mode/rust' {
  declare module.exports: any;
}

declare module 'brace/mode/sass' {
  declare module.exports: any;
}

declare module 'brace/mode/scad' {
  declare module.exports: any;
}

declare module 'brace/mode/scala' {
  declare module.exports: any;
}

declare module 'brace/mode/scheme' {
  declare module.exports: any;
}

declare module 'brace/mode/scss' {
  declare module.exports: any;
}

declare module 'brace/mode/sh' {
  declare module.exports: any;
}

declare module 'brace/mode/sjs' {
  declare module.exports: any;
}

declare module 'brace/mode/smarty' {
  declare module.exports: any;
}

declare module 'brace/mode/snippets' {
  declare module.exports: any;
}

declare module 'brace/mode/soy_template' {
  declare module.exports: any;
}

declare module 'brace/mode/space' {
  declare module.exports: any;
}

declare module 'brace/mode/sql' {
  declare module.exports: any;
}

declare module 'brace/mode/sqlserver' {
  declare module.exports: any;
}

declare module 'brace/mode/stylus' {
  declare module.exports: any;
}

declare module 'brace/mode/svg' {
  declare module.exports: any;
}

declare module 'brace/mode/swift' {
  declare module.exports: any;
}

declare module 'brace/mode/swig' {
  declare module.exports: any;
}

declare module 'brace/mode/tcl' {
  declare module.exports: any;
}

declare module 'brace/mode/tex' {
  declare module.exports: any;
}

declare module 'brace/mode/text' {
  declare module.exports: any;
}

declare module 'brace/mode/textile' {
  declare module.exports: any;
}

declare module 'brace/mode/toml' {
  declare module.exports: any;
}

declare module 'brace/mode/twig' {
  declare module.exports: any;
}

declare module 'brace/mode/typescript' {
  declare module.exports: any;
}

declare module 'brace/mode/vala' {
  declare module.exports: any;
}

declare module 'brace/mode/vbscript' {
  declare module.exports: any;
}

declare module 'brace/mode/velocity' {
  declare module.exports: any;
}

declare module 'brace/mode/verilog' {
  declare module.exports: any;
}

declare module 'brace/mode/vhdl' {
  declare module.exports: any;
}

declare module 'brace/mode/wollok' {
  declare module.exports: any;
}

declare module 'brace/mode/xml' {
  declare module.exports: any;
}

declare module 'brace/mode/xquery' {
  declare module.exports: any;
}

declare module 'brace/mode/yaml' {
  declare module.exports: any;
}

declare module 'brace/test/error-annotations' {
  declare module.exports: any;
}

declare module 'brace/test/fixtures/coffee-editor' {
  declare module.exports: any;
}

declare module 'brace/test/fixtures/javascript-editor' {
  declare module.exports: any;
}

declare module 'brace/test/fixtures/json-editor' {
  declare module.exports: any;
}

declare module 'brace/test/fixtures/lua-editor' {
  declare module.exports: any;
}

declare module 'brace/test/fixtures/xml-editor' {
  declare module.exports: any;
}

declare module 'brace/test/stringified/style' {
  declare module.exports: any;
}

declare module 'brace/theme/ambiance' {
  declare module.exports: any;
}

declare module 'brace/theme/chaos' {
  declare module.exports: any;
}

declare module 'brace/theme/chrome' {
  declare module.exports: any;
}

declare module 'brace/theme/clouds_midnight' {
  declare module.exports: any;
}

declare module 'brace/theme/clouds' {
  declare module.exports: any;
}

declare module 'brace/theme/cobalt' {
  declare module.exports: any;
}

declare module 'brace/theme/crimson_editor' {
  declare module.exports: any;
}

declare module 'brace/theme/dawn' {
  declare module.exports: any;
}

declare module 'brace/theme/dreamweaver' {
  declare module.exports: any;
}

declare module 'brace/theme/eclipse' {
  declare module.exports: any;
}

declare module 'brace/theme/github' {
  declare module.exports: any;
}

declare module 'brace/theme/idle_fingers' {
  declare module.exports: any;
}

declare module 'brace/theme/iplastic' {
  declare module.exports: any;
}

declare module 'brace/theme/katzenmilch' {
  declare module.exports: any;
}

declare module 'brace/theme/kr_theme' {
  declare module.exports: any;
}

declare module 'brace/theme/kuroir' {
  declare module.exports: any;
}

declare module 'brace/theme/merbivore_soft' {
  declare module.exports: any;
}

declare module 'brace/theme/merbivore' {
  declare module.exports: any;
}

declare module 'brace/theme/mono_industrial' {
  declare module.exports: any;
}

declare module 'brace/theme/monokai' {
  declare module.exports: any;
}

declare module 'brace/theme/pastel_on_dark' {
  declare module.exports: any;
}

declare module 'brace/theme/solarized_dark' {
  declare module.exports: any;
}

declare module 'brace/theme/solarized_light' {
  declare module.exports: any;
}

declare module 'brace/theme/sqlserver' {
  declare module.exports: any;
}

declare module 'brace/theme/terminal' {
  declare module.exports: any;
}

declare module 'brace/theme/textmate' {
  declare module.exports: any;
}

declare module 'brace/theme/tomorrow_night_blue' {
  declare module.exports: any;
}

declare module 'brace/theme/tomorrow_night_bright' {
  declare module.exports: any;
}

declare module 'brace/theme/tomorrow_night_eighties' {
  declare module.exports: any;
}

declare module 'brace/theme/tomorrow_night' {
  declare module.exports: any;
}

declare module 'brace/theme/tomorrow' {
  declare module.exports: any;
}

declare module 'brace/theme/twilight' {
  declare module.exports: any;
}

declare module 'brace/theme/vibrant_ink' {
  declare module.exports: any;
}

declare module 'brace/theme/xcode' {
  declare module.exports: any;
}

declare module 'brace/worker/coffee' {
  declare module.exports: any;
}

declare module 'brace/worker/css' {
  declare module.exports: any;
}

declare module 'brace/worker/html' {
  declare module.exports: any;
}

declare module 'brace/worker/javascript' {
  declare module.exports: any;
}

declare module 'brace/worker/json' {
  declare module.exports: any;
}

declare module 'brace/worker/lua' {
  declare module.exports: any;
}

declare module 'brace/worker/xml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'brace/example/build.js' {
  declare module.exports: $Exports<'brace/example/build'>;
}
declare module 'brace/example/coffee-editor.js' {
  declare module.exports: $Exports<'brace/example/coffee-editor'>;
}
declare module 'brace/example/css-editor.js' {
  declare module.exports: $Exports<'brace/example/css-editor'>;
}
declare module 'brace/example/javascript-editor.js' {
  declare module.exports: $Exports<'brace/example/javascript-editor'>;
}
declare module 'brace/example/json-editor.js' {
  declare module.exports: $Exports<'brace/example/json-editor'>;
}
declare module 'brace/example/lua-editor.js' {
  declare module.exports: $Exports<'brace/example/lua-editor'>;
}
declare module 'brace/ext/beautify.js' {
  declare module.exports: $Exports<'brace/ext/beautify'>;
}
declare module 'brace/ext/chromevox.js' {
  declare module.exports: $Exports<'brace/ext/chromevox'>;
}
declare module 'brace/ext/elastic_tabstops_lite.js' {
  declare module.exports: $Exports<'brace/ext/elastic_tabstops_lite'>;
}
declare module 'brace/ext/emmet.js' {
  declare module.exports: $Exports<'brace/ext/emmet'>;
}
declare module 'brace/ext/error_marker.js' {
  declare module.exports: $Exports<'brace/ext/error_marker'>;
}
declare module 'brace/ext/keybinding_menu.js' {
  declare module.exports: $Exports<'brace/ext/keybinding_menu'>;
}
declare module 'brace/ext/language_tools.js' {
  declare module.exports: $Exports<'brace/ext/language_tools'>;
}
declare module 'brace/ext/linking.js' {
  declare module.exports: $Exports<'brace/ext/linking'>;
}
declare module 'brace/ext/modelist.js' {
  declare module.exports: $Exports<'brace/ext/modelist'>;
}
declare module 'brace/ext/old_ie.js' {
  declare module.exports: $Exports<'brace/ext/old_ie'>;
}
declare module 'brace/ext/searchbox.js' {
  declare module.exports: $Exports<'brace/ext/searchbox'>;
}
declare module 'brace/ext/settings_menu.js' {
  declare module.exports: $Exports<'brace/ext/settings_menu'>;
}
declare module 'brace/ext/spellcheck.js' {
  declare module.exports: $Exports<'brace/ext/spellcheck'>;
}
declare module 'brace/ext/split.js' {
  declare module.exports: $Exports<'brace/ext/split'>;
}
declare module 'brace/ext/static_highlight.js' {
  declare module.exports: $Exports<'brace/ext/static_highlight'>;
}
declare module 'brace/ext/statusbar.js' {
  declare module.exports: $Exports<'brace/ext/statusbar'>;
}
declare module 'brace/ext/textarea.js' {
  declare module.exports: $Exports<'brace/ext/textarea'>;
}
declare module 'brace/ext/themelist.js' {
  declare module.exports: $Exports<'brace/ext/themelist'>;
}
declare module 'brace/ext/whitespace.js' {
  declare module.exports: $Exports<'brace/ext/whitespace'>;
}
declare module 'brace/index' {
  declare module.exports: $Exports<'brace'>;
}
declare module 'brace/index.js' {
  declare module.exports: $Exports<'brace'>;
}
declare module 'brace/keybinding/emacs.js' {
  declare module.exports: $Exports<'brace/keybinding/emacs'>;
}
declare module 'brace/keybinding/vim.js' {
  declare module.exports: $Exports<'brace/keybinding/vim'>;
}
declare module 'brace/mode/abap.js' {
  declare module.exports: $Exports<'brace/mode/abap'>;
}
declare module 'brace/mode/abc.js' {
  declare module.exports: $Exports<'brace/mode/abc'>;
}
declare module 'brace/mode/actionscript.js' {
  declare module.exports: $Exports<'brace/mode/actionscript'>;
}
declare module 'brace/mode/ada.js' {
  declare module.exports: $Exports<'brace/mode/ada'>;
}
declare module 'brace/mode/apache_conf.js' {
  declare module.exports: $Exports<'brace/mode/apache_conf'>;
}
declare module 'brace/mode/applescript.js' {
  declare module.exports: $Exports<'brace/mode/applescript'>;
}
declare module 'brace/mode/asciidoc.js' {
  declare module.exports: $Exports<'brace/mode/asciidoc'>;
}
declare module 'brace/mode/assembly_x86.js' {
  declare module.exports: $Exports<'brace/mode/assembly_x86'>;
}
declare module 'brace/mode/autohotkey.js' {
  declare module.exports: $Exports<'brace/mode/autohotkey'>;
}
declare module 'brace/mode/batchfile.js' {
  declare module.exports: $Exports<'brace/mode/batchfile'>;
}
declare module 'brace/mode/c_cpp.js' {
  declare module.exports: $Exports<'brace/mode/c_cpp'>;
}
declare module 'brace/mode/c9search.js' {
  declare module.exports: $Exports<'brace/mode/c9search'>;
}
declare module 'brace/mode/cirru.js' {
  declare module.exports: $Exports<'brace/mode/cirru'>;
}
declare module 'brace/mode/clojure.js' {
  declare module.exports: $Exports<'brace/mode/clojure'>;
}
declare module 'brace/mode/cobol.js' {
  declare module.exports: $Exports<'brace/mode/cobol'>;
}
declare module 'brace/mode/coffee.js' {
  declare module.exports: $Exports<'brace/mode/coffee'>;
}
declare module 'brace/mode/coldfusion.js' {
  declare module.exports: $Exports<'brace/mode/coldfusion'>;
}
declare module 'brace/mode/csharp.js' {
  declare module.exports: $Exports<'brace/mode/csharp'>;
}
declare module 'brace/mode/css.js' {
  declare module.exports: $Exports<'brace/mode/css'>;
}
declare module 'brace/mode/curly.js' {
  declare module.exports: $Exports<'brace/mode/curly'>;
}
declare module 'brace/mode/d.js' {
  declare module.exports: $Exports<'brace/mode/d'>;
}
declare module 'brace/mode/dart.js' {
  declare module.exports: $Exports<'brace/mode/dart'>;
}
declare module 'brace/mode/diff.js' {
  declare module.exports: $Exports<'brace/mode/diff'>;
}
declare module 'brace/mode/django.js' {
  declare module.exports: $Exports<'brace/mode/django'>;
}
declare module 'brace/mode/dockerfile.js' {
  declare module.exports: $Exports<'brace/mode/dockerfile'>;
}
declare module 'brace/mode/dot.js' {
  declare module.exports: $Exports<'brace/mode/dot'>;
}
declare module 'brace/mode/eiffel.js' {
  declare module.exports: $Exports<'brace/mode/eiffel'>;
}
declare module 'brace/mode/ejs.js' {
  declare module.exports: $Exports<'brace/mode/ejs'>;
}
declare module 'brace/mode/elixir.js' {
  declare module.exports: $Exports<'brace/mode/elixir'>;
}
declare module 'brace/mode/elm.js' {
  declare module.exports: $Exports<'brace/mode/elm'>;
}
declare module 'brace/mode/erlang.js' {
  declare module.exports: $Exports<'brace/mode/erlang'>;
}
declare module 'brace/mode/forth.js' {
  declare module.exports: $Exports<'brace/mode/forth'>;
}
declare module 'brace/mode/ftl.js' {
  declare module.exports: $Exports<'brace/mode/ftl'>;
}
declare module 'brace/mode/gcode.js' {
  declare module.exports: $Exports<'brace/mode/gcode'>;
}
declare module 'brace/mode/gherkin.js' {
  declare module.exports: $Exports<'brace/mode/gherkin'>;
}
declare module 'brace/mode/gitignore.js' {
  declare module.exports: $Exports<'brace/mode/gitignore'>;
}
declare module 'brace/mode/glsl.js' {
  declare module.exports: $Exports<'brace/mode/glsl'>;
}
declare module 'brace/mode/gobstones.js' {
  declare module.exports: $Exports<'brace/mode/gobstones'>;
}
declare module 'brace/mode/golang.js' {
  declare module.exports: $Exports<'brace/mode/golang'>;
}
declare module 'brace/mode/groovy.js' {
  declare module.exports: $Exports<'brace/mode/groovy'>;
}
declare module 'brace/mode/haml.js' {
  declare module.exports: $Exports<'brace/mode/haml'>;
}
declare module 'brace/mode/handlebars.js' {
  declare module.exports: $Exports<'brace/mode/handlebars'>;
}
declare module 'brace/mode/haskell.js' {
  declare module.exports: $Exports<'brace/mode/haskell'>;
}
declare module 'brace/mode/haxe.js' {
  declare module.exports: $Exports<'brace/mode/haxe'>;
}
declare module 'brace/mode/html_elixir.js' {
  declare module.exports: $Exports<'brace/mode/html_elixir'>;
}
declare module 'brace/mode/html_ruby.js' {
  declare module.exports: $Exports<'brace/mode/html_ruby'>;
}
declare module 'brace/mode/html.js' {
  declare module.exports: $Exports<'brace/mode/html'>;
}
declare module 'brace/mode/ini.js' {
  declare module.exports: $Exports<'brace/mode/ini'>;
}
declare module 'brace/mode/io.js' {
  declare module.exports: $Exports<'brace/mode/io'>;
}
declare module 'brace/mode/jack.js' {
  declare module.exports: $Exports<'brace/mode/jack'>;
}
declare module 'brace/mode/jade.js' {
  declare module.exports: $Exports<'brace/mode/jade'>;
}
declare module 'brace/mode/java.js' {
  declare module.exports: $Exports<'brace/mode/java'>;
}
declare module 'brace/mode/javascript.js' {
  declare module.exports: $Exports<'brace/mode/javascript'>;
}
declare module 'brace/mode/json.js' {
  declare module.exports: $Exports<'brace/mode/json'>;
}
declare module 'brace/mode/jsoniq.js' {
  declare module.exports: $Exports<'brace/mode/jsoniq'>;
}
declare module 'brace/mode/jsp.js' {
  declare module.exports: $Exports<'brace/mode/jsp'>;
}
declare module 'brace/mode/jsx.js' {
  declare module.exports: $Exports<'brace/mode/jsx'>;
}
declare module 'brace/mode/julia.js' {
  declare module.exports: $Exports<'brace/mode/julia'>;
}
declare module 'brace/mode/latex.js' {
  declare module.exports: $Exports<'brace/mode/latex'>;
}
declare module 'brace/mode/lean.js' {
  declare module.exports: $Exports<'brace/mode/lean'>;
}
declare module 'brace/mode/less.js' {
  declare module.exports: $Exports<'brace/mode/less'>;
}
declare module 'brace/mode/liquid.js' {
  declare module.exports: $Exports<'brace/mode/liquid'>;
}
declare module 'brace/mode/lisp.js' {
  declare module.exports: $Exports<'brace/mode/lisp'>;
}
declare module 'brace/mode/live_script.js' {
  declare module.exports: $Exports<'brace/mode/live_script'>;
}
declare module 'brace/mode/livescript.js' {
  declare module.exports: $Exports<'brace/mode/livescript'>;
}
declare module 'brace/mode/logiql.js' {
  declare module.exports: $Exports<'brace/mode/logiql'>;
}
declare module 'brace/mode/lsl.js' {
  declare module.exports: $Exports<'brace/mode/lsl'>;
}
declare module 'brace/mode/lua.js' {
  declare module.exports: $Exports<'brace/mode/lua'>;
}
declare module 'brace/mode/luapage.js' {
  declare module.exports: $Exports<'brace/mode/luapage'>;
}
declare module 'brace/mode/lucene.js' {
  declare module.exports: $Exports<'brace/mode/lucene'>;
}
declare module 'brace/mode/makefile.js' {
  declare module.exports: $Exports<'brace/mode/makefile'>;
}
declare module 'brace/mode/markdown.js' {
  declare module.exports: $Exports<'brace/mode/markdown'>;
}
declare module 'brace/mode/mask.js' {
  declare module.exports: $Exports<'brace/mode/mask'>;
}
declare module 'brace/mode/matlab.js' {
  declare module.exports: $Exports<'brace/mode/matlab'>;
}
declare module 'brace/mode/mavens_mate_log.js' {
  declare module.exports: $Exports<'brace/mode/mavens_mate_log'>;
}
declare module 'brace/mode/maze.js' {
  declare module.exports: $Exports<'brace/mode/maze'>;
}
declare module 'brace/mode/mel.js' {
  declare module.exports: $Exports<'brace/mode/mel'>;
}
declare module 'brace/mode/mips_assembler.js' {
  declare module.exports: $Exports<'brace/mode/mips_assembler'>;
}
declare module 'brace/mode/mipsassembler.js' {
  declare module.exports: $Exports<'brace/mode/mipsassembler'>;
}
declare module 'brace/mode/mushcode.js' {
  declare module.exports: $Exports<'brace/mode/mushcode'>;
}
declare module 'brace/mode/mysql.js' {
  declare module.exports: $Exports<'brace/mode/mysql'>;
}
declare module 'brace/mode/nix.js' {
  declare module.exports: $Exports<'brace/mode/nix'>;
}
declare module 'brace/mode/nsis.js' {
  declare module.exports: $Exports<'brace/mode/nsis'>;
}
declare module 'brace/mode/objectivec.js' {
  declare module.exports: $Exports<'brace/mode/objectivec'>;
}
declare module 'brace/mode/ocaml.js' {
  declare module.exports: $Exports<'brace/mode/ocaml'>;
}
declare module 'brace/mode/pascal.js' {
  declare module.exports: $Exports<'brace/mode/pascal'>;
}
declare module 'brace/mode/perl.js' {
  declare module.exports: $Exports<'brace/mode/perl'>;
}
declare module 'brace/mode/pgsql.js' {
  declare module.exports: $Exports<'brace/mode/pgsql'>;
}
declare module 'brace/mode/php.js' {
  declare module.exports: $Exports<'brace/mode/php'>;
}
declare module 'brace/mode/plain_text.js' {
  declare module.exports: $Exports<'brace/mode/plain_text'>;
}
declare module 'brace/mode/powershell.js' {
  declare module.exports: $Exports<'brace/mode/powershell'>;
}
declare module 'brace/mode/praat.js' {
  declare module.exports: $Exports<'brace/mode/praat'>;
}
declare module 'brace/mode/prolog.js' {
  declare module.exports: $Exports<'brace/mode/prolog'>;
}
declare module 'brace/mode/properties.js' {
  declare module.exports: $Exports<'brace/mode/properties'>;
}
declare module 'brace/mode/protobuf.js' {
  declare module.exports: $Exports<'brace/mode/protobuf'>;
}
declare module 'brace/mode/python.js' {
  declare module.exports: $Exports<'brace/mode/python'>;
}
declare module 'brace/mode/r.js' {
  declare module.exports: $Exports<'brace/mode/r'>;
}
declare module 'brace/mode/razor.js' {
  declare module.exports: $Exports<'brace/mode/razor'>;
}
declare module 'brace/mode/rdoc.js' {
  declare module.exports: $Exports<'brace/mode/rdoc'>;
}
declare module 'brace/mode/rhtml.js' {
  declare module.exports: $Exports<'brace/mode/rhtml'>;
}
declare module 'brace/mode/rst.js' {
  declare module.exports: $Exports<'brace/mode/rst'>;
}
declare module 'brace/mode/ruby.js' {
  declare module.exports: $Exports<'brace/mode/ruby'>;
}
declare module 'brace/mode/rust.js' {
  declare module.exports: $Exports<'brace/mode/rust'>;
}
declare module 'brace/mode/sass.js' {
  declare module.exports: $Exports<'brace/mode/sass'>;
}
declare module 'brace/mode/scad.js' {
  declare module.exports: $Exports<'brace/mode/scad'>;
}
declare module 'brace/mode/scala.js' {
  declare module.exports: $Exports<'brace/mode/scala'>;
}
declare module 'brace/mode/scheme.js' {
  declare module.exports: $Exports<'brace/mode/scheme'>;
}
declare module 'brace/mode/scss.js' {
  declare module.exports: $Exports<'brace/mode/scss'>;
}
declare module 'brace/mode/sh.js' {
  declare module.exports: $Exports<'brace/mode/sh'>;
}
declare module 'brace/mode/sjs.js' {
  declare module.exports: $Exports<'brace/mode/sjs'>;
}
declare module 'brace/mode/smarty.js' {
  declare module.exports: $Exports<'brace/mode/smarty'>;
}
declare module 'brace/mode/snippets.js' {
  declare module.exports: $Exports<'brace/mode/snippets'>;
}
declare module 'brace/mode/soy_template.js' {
  declare module.exports: $Exports<'brace/mode/soy_template'>;
}
declare module 'brace/mode/space.js' {
  declare module.exports: $Exports<'brace/mode/space'>;
}
declare module 'brace/mode/sql.js' {
  declare module.exports: $Exports<'brace/mode/sql'>;
}
declare module 'brace/mode/sqlserver.js' {
  declare module.exports: $Exports<'brace/mode/sqlserver'>;
}
declare module 'brace/mode/stylus.js' {
  declare module.exports: $Exports<'brace/mode/stylus'>;
}
declare module 'brace/mode/svg.js' {
  declare module.exports: $Exports<'brace/mode/svg'>;
}
declare module 'brace/mode/swift.js' {
  declare module.exports: $Exports<'brace/mode/swift'>;
}
declare module 'brace/mode/swig.js' {
  declare module.exports: $Exports<'brace/mode/swig'>;
}
declare module 'brace/mode/tcl.js' {
  declare module.exports: $Exports<'brace/mode/tcl'>;
}
declare module 'brace/mode/tex.js' {
  declare module.exports: $Exports<'brace/mode/tex'>;
}
declare module 'brace/mode/text.js' {
  declare module.exports: $Exports<'brace/mode/text'>;
}
declare module 'brace/mode/textile.js' {
  declare module.exports: $Exports<'brace/mode/textile'>;
}
declare module 'brace/mode/toml.js' {
  declare module.exports: $Exports<'brace/mode/toml'>;
}
declare module 'brace/mode/twig.js' {
  declare module.exports: $Exports<'brace/mode/twig'>;
}
declare module 'brace/mode/typescript.js' {
  declare module.exports: $Exports<'brace/mode/typescript'>;
}
declare module 'brace/mode/vala.js' {
  declare module.exports: $Exports<'brace/mode/vala'>;
}
declare module 'brace/mode/vbscript.js' {
  declare module.exports: $Exports<'brace/mode/vbscript'>;
}
declare module 'brace/mode/velocity.js' {
  declare module.exports: $Exports<'brace/mode/velocity'>;
}
declare module 'brace/mode/verilog.js' {
  declare module.exports: $Exports<'brace/mode/verilog'>;
}
declare module 'brace/mode/vhdl.js' {
  declare module.exports: $Exports<'brace/mode/vhdl'>;
}
declare module 'brace/mode/wollok.js' {
  declare module.exports: $Exports<'brace/mode/wollok'>;
}
declare module 'brace/mode/xml.js' {
  declare module.exports: $Exports<'brace/mode/xml'>;
}
declare module 'brace/mode/xquery.js' {
  declare module.exports: $Exports<'brace/mode/xquery'>;
}
declare module 'brace/mode/yaml.js' {
  declare module.exports: $Exports<'brace/mode/yaml'>;
}
declare module 'brace/test/error-annotations.js' {
  declare module.exports: $Exports<'brace/test/error-annotations'>;
}
declare module 'brace/test/fixtures/coffee-editor.js' {
  declare module.exports: $Exports<'brace/test/fixtures/coffee-editor'>;
}
declare module 'brace/test/fixtures/javascript-editor.js' {
  declare module.exports: $Exports<'brace/test/fixtures/javascript-editor'>;
}
declare module 'brace/test/fixtures/json-editor.js' {
  declare module.exports: $Exports<'brace/test/fixtures/json-editor'>;
}
declare module 'brace/test/fixtures/lua-editor.js' {
  declare module.exports: $Exports<'brace/test/fixtures/lua-editor'>;
}
declare module 'brace/test/fixtures/xml-editor.js' {
  declare module.exports: $Exports<'brace/test/fixtures/xml-editor'>;
}
declare module 'brace/test/stringified/style.js' {
  declare module.exports: $Exports<'brace/test/stringified/style'>;
}
declare module 'brace/theme/ambiance.js' {
  declare module.exports: $Exports<'brace/theme/ambiance'>;
}
declare module 'brace/theme/chaos.js' {
  declare module.exports: $Exports<'brace/theme/chaos'>;
}
declare module 'brace/theme/chrome.js' {
  declare module.exports: $Exports<'brace/theme/chrome'>;
}
declare module 'brace/theme/clouds_midnight.js' {
  declare module.exports: $Exports<'brace/theme/clouds_midnight'>;
}
declare module 'brace/theme/clouds.js' {
  declare module.exports: $Exports<'brace/theme/clouds'>;
}
declare module 'brace/theme/cobalt.js' {
  declare module.exports: $Exports<'brace/theme/cobalt'>;
}
declare module 'brace/theme/crimson_editor.js' {
  declare module.exports: $Exports<'brace/theme/crimson_editor'>;
}
declare module 'brace/theme/dawn.js' {
  declare module.exports: $Exports<'brace/theme/dawn'>;
}
declare module 'brace/theme/dreamweaver.js' {
  declare module.exports: $Exports<'brace/theme/dreamweaver'>;
}
declare module 'brace/theme/eclipse.js' {
  declare module.exports: $Exports<'brace/theme/eclipse'>;
}
declare module 'brace/theme/github.js' {
  declare module.exports: $Exports<'brace/theme/github'>;
}
declare module 'brace/theme/idle_fingers.js' {
  declare module.exports: $Exports<'brace/theme/idle_fingers'>;
}
declare module 'brace/theme/iplastic.js' {
  declare module.exports: $Exports<'brace/theme/iplastic'>;
}
declare module 'brace/theme/katzenmilch.js' {
  declare module.exports: $Exports<'brace/theme/katzenmilch'>;
}
declare module 'brace/theme/kr_theme.js' {
  declare module.exports: $Exports<'brace/theme/kr_theme'>;
}
declare module 'brace/theme/kuroir.js' {
  declare module.exports: $Exports<'brace/theme/kuroir'>;
}
declare module 'brace/theme/merbivore_soft.js' {
  declare module.exports: $Exports<'brace/theme/merbivore_soft'>;
}
declare module 'brace/theme/merbivore.js' {
  declare module.exports: $Exports<'brace/theme/merbivore'>;
}
declare module 'brace/theme/mono_industrial.js' {
  declare module.exports: $Exports<'brace/theme/mono_industrial'>;
}
declare module 'brace/theme/monokai.js' {
  declare module.exports: $Exports<'brace/theme/monokai'>;
}
declare module 'brace/theme/pastel_on_dark.js' {
  declare module.exports: $Exports<'brace/theme/pastel_on_dark'>;
}
declare module 'brace/theme/solarized_dark.js' {
  declare module.exports: $Exports<'brace/theme/solarized_dark'>;
}
declare module 'brace/theme/solarized_light.js' {
  declare module.exports: $Exports<'brace/theme/solarized_light'>;
}
declare module 'brace/theme/sqlserver.js' {
  declare module.exports: $Exports<'brace/theme/sqlserver'>;
}
declare module 'brace/theme/terminal.js' {
  declare module.exports: $Exports<'brace/theme/terminal'>;
}
declare module 'brace/theme/textmate.js' {
  declare module.exports: $Exports<'brace/theme/textmate'>;
}
declare module 'brace/theme/tomorrow_night_blue.js' {
  declare module.exports: $Exports<'brace/theme/tomorrow_night_blue'>;
}
declare module 'brace/theme/tomorrow_night_bright.js' {
  declare module.exports: $Exports<'brace/theme/tomorrow_night_bright'>;
}
declare module 'brace/theme/tomorrow_night_eighties.js' {
  declare module.exports: $Exports<'brace/theme/tomorrow_night_eighties'>;
}
declare module 'brace/theme/tomorrow_night.js' {
  declare module.exports: $Exports<'brace/theme/tomorrow_night'>;
}
declare module 'brace/theme/tomorrow.js' {
  declare module.exports: $Exports<'brace/theme/tomorrow'>;
}
declare module 'brace/theme/twilight.js' {
  declare module.exports: $Exports<'brace/theme/twilight'>;
}
declare module 'brace/theme/vibrant_ink.js' {
  declare module.exports: $Exports<'brace/theme/vibrant_ink'>;
}
declare module 'brace/theme/xcode.js' {
  declare module.exports: $Exports<'brace/theme/xcode'>;
}
declare module 'brace/worker/coffee.js' {
  declare module.exports: $Exports<'brace/worker/coffee'>;
}
declare module 'brace/worker/css.js' {
  declare module.exports: $Exports<'brace/worker/css'>;
}
declare module 'brace/worker/html.js' {
  declare module.exports: $Exports<'brace/worker/html'>;
}
declare module 'brace/worker/javascript.js' {
  declare module.exports: $Exports<'brace/worker/javascript'>;
}
declare module 'brace/worker/json.js' {
  declare module.exports: $Exports<'brace/worker/json'>;
}
declare module 'brace/worker/lua.js' {
  declare module.exports: $Exports<'brace/worker/lua'>;
}
declare module 'brace/worker/xml.js' {
  declare module.exports: $Exports<'brace/worker/xml'>;
}
