// flow-typed signature: 8492b93118484d4fdf4b7a63fb5555bc
// flow-typed version: <<STUB>>/c3_v^0.4.10/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'c3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'c3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'c3/c3' {
  declare module.exports: any;
}

declare module 'c3/c3.min' {
  declare module.exports: any;
}

declare module 'c3/extensions/chart-bubble/bubble' {
  declare module.exports: any;
}

declare module 'c3/extensions/exporter/phantom-exporter' {
  declare module.exports: any;
}

declare module 'c3/extensions/js/c3ext' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/console/console' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/boot' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/spec/PlayerSpec' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/spec/SpecHelper' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/src/Player' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/src/Song' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/spec/PlayerSpec' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/spec/SpecHelper' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/src/Player' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/src/Song' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/jasmine-html' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/jasmine' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/json2' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/node_boot' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine/lib/jasmine-2.0.2/boot' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine/lib/jasmine-2.0.2/console' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine/lib/jasmine-2.0.2/jasmine-html' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine/lib/jasmine-2.0.2/jasmine' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine/spec/PlayerSpec' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine/spec/SpecHelper' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine/src/Player' {
  declare module.exports: any;
}

declare module 'c3/htdocs/jasmine/src/Song' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/angular.min' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/c3-0.4.0.min' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/c3-0.4.8.min' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/c3-0.4.9.min' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/c3.org' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/d3-3.4.13.min' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/d3-3.5.0.min' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/d3-3.5.1.min' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/d3-3.5.2.min' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/d3-3.5.6' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/jasmine' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/moment-range' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/moment' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/moment.min' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/require' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/samples/angularjs' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/samples/plugin' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/samples/requirejs' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/samples/zoom_reduction' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/test' {
  declare module.exports: any;
}

declare module 'c3/karma.conf' {
  declare module.exports: any;
}

declare module 'c3/spec/api.axis-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.data-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.focus-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.grid-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.load-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.region-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.zoom-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/arc-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/axis-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/c3-helper' {
  declare module.exports: any;
}

declare module 'c3/spec/c3-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/class-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/core-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/data-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/domain-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/grid-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/interaction-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/legend-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/shape.bar-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/shape.line-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/svg-helper' {
  declare module.exports: any;
}

declare module 'c3/spec/title-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/tooltip-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/type-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/zoom-spec' {
  declare module.exports: any;
}

declare module 'c3/src/api.axis' {
  declare module.exports: any;
}

declare module 'c3/src/api.category' {
  declare module.exports: any;
}

declare module 'c3/src/api.chart' {
  declare module.exports: any;
}

declare module 'c3/src/api.color' {
  declare module.exports: any;
}

declare module 'c3/src/api.data' {
  declare module.exports: any;
}

declare module 'c3/src/api.flow' {
  declare module.exports: any;
}

declare module 'c3/src/api.focus' {
  declare module.exports: any;
}

declare module 'c3/src/api.grid' {
  declare module.exports: any;
}

declare module 'c3/src/api.group' {
  declare module.exports: any;
}

declare module 'c3/src/api.legend' {
  declare module.exports: any;
}

declare module 'c3/src/api.load' {
  declare module.exports: any;
}

declare module 'c3/src/api.region' {
  declare module.exports: any;
}

declare module 'c3/src/api.selection' {
  declare module.exports: any;
}

declare module 'c3/src/api.show' {
  declare module.exports: any;
}

declare module 'c3/src/api.tooltip' {
  declare module.exports: any;
}

declare module 'c3/src/api.transform' {
  declare module.exports: any;
}

declare module 'c3/src/api.x' {
  declare module.exports: any;
}

declare module 'c3/src/api.zoom' {
  declare module.exports: any;
}

declare module 'c3/src/arc' {
  declare module.exports: any;
}

declare module 'c3/src/axis' {
  declare module.exports: any;
}

declare module 'c3/src/c3.axis' {
  declare module.exports: any;
}

declare module 'c3/src/cache' {
  declare module.exports: any;
}

declare module 'c3/src/category' {
  declare module.exports: any;
}

declare module 'c3/src/class' {
  declare module.exports: any;
}

declare module 'c3/src/clip' {
  declare module.exports: any;
}

declare module 'c3/src/color' {
  declare module.exports: any;
}

declare module 'c3/src/config' {
  declare module.exports: any;
}

declare module 'c3/src/core' {
  declare module.exports: any;
}

declare module 'c3/src/data.convert' {
  declare module.exports: any;
}

declare module 'c3/src/data' {
  declare module.exports: any;
}

declare module 'c3/src/data.load' {
  declare module.exports: any;
}

declare module 'c3/src/domain' {
  declare module.exports: any;
}

declare module 'c3/src/drag' {
  declare module.exports: any;
}

declare module 'c3/src/format' {
  declare module.exports: any;
}

declare module 'c3/src/grid' {
  declare module.exports: any;
}

declare module 'c3/src/head' {
  declare module.exports: any;
}

declare module 'c3/src/interaction' {
  declare module.exports: any;
}

declare module 'c3/src/legend' {
  declare module.exports: any;
}

declare module 'c3/src/polyfill' {
  declare module.exports: any;
}

declare module 'c3/src/region' {
  declare module.exports: any;
}

declare module 'c3/src/scale' {
  declare module.exports: any;
}

declare module 'c3/src/selection' {
  declare module.exports: any;
}

declare module 'c3/src/shape.bar' {
  declare module.exports: any;
}

declare module 'c3/src/shape' {
  declare module.exports: any;
}

declare module 'c3/src/shape.line' {
  declare module.exports: any;
}

declare module 'c3/src/size' {
  declare module.exports: any;
}

declare module 'c3/src/subchart' {
  declare module.exports: any;
}

declare module 'c3/src/tail' {
  declare module.exports: any;
}

declare module 'c3/src/text' {
  declare module.exports: any;
}

declare module 'c3/src/title' {
  declare module.exports: any;
}

declare module 'c3/src/tooltip' {
  declare module.exports: any;
}

declare module 'c3/src/type' {
  declare module.exports: any;
}

declare module 'c3/src/ua' {
  declare module.exports: any;
}

declare module 'c3/src/util' {
  declare module.exports: any;
}

declare module 'c3/src/zoom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'c3/c3.js' {
  declare module.exports: $Exports<'c3/c3'>;
}
declare module 'c3/c3.min.js' {
  declare module.exports: $Exports<'c3/c3.min'>;
}
declare module 'c3/extensions/chart-bubble/bubble.js' {
  declare module.exports: $Exports<'c3/extensions/chart-bubble/bubble'>;
}
declare module 'c3/extensions/exporter/phantom-exporter.js' {
  declare module.exports: $Exports<'c3/extensions/exporter/phantom-exporter'>;
}
declare module 'c3/extensions/js/c3ext.js' {
  declare module.exports: $Exports<'c3/extensions/js/c3ext'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/console/console.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/console/console'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/boot.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/boot'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/spec/PlayerSpec.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/spec/PlayerSpec'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/spec/SpecHelper.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/spec/SpecHelper'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/src/Player.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/src/Player'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/src/Song.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/node_example/src/Song'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/spec/PlayerSpec.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/spec/PlayerSpec'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/spec/SpecHelper.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/spec/SpecHelper'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/src/Player.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/src/Player'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/src/Song.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/example/src/Song'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/jasmine-html.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/jasmine-html'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/jasmine.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/jasmine'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/json2.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/json2'>;
}
declare module 'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/node_boot.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine-2.1.3/lib/jasmine-core/node_boot'>;
}
declare module 'c3/htdocs/jasmine/lib/jasmine-2.0.2/boot.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine/lib/jasmine-2.0.2/boot'>;
}
declare module 'c3/htdocs/jasmine/lib/jasmine-2.0.2/console.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine/lib/jasmine-2.0.2/console'>;
}
declare module 'c3/htdocs/jasmine/lib/jasmine-2.0.2/jasmine-html.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine/lib/jasmine-2.0.2/jasmine-html'>;
}
declare module 'c3/htdocs/jasmine/lib/jasmine-2.0.2/jasmine.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine/lib/jasmine-2.0.2/jasmine'>;
}
declare module 'c3/htdocs/jasmine/spec/PlayerSpec.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine/spec/PlayerSpec'>;
}
declare module 'c3/htdocs/jasmine/spec/SpecHelper.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine/spec/SpecHelper'>;
}
declare module 'c3/htdocs/jasmine/src/Player.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine/src/Player'>;
}
declare module 'c3/htdocs/jasmine/src/Song.js' {
  declare module.exports: $Exports<'c3/htdocs/jasmine/src/Song'>;
}
declare module 'c3/htdocs/js/angular.min.js' {
  declare module.exports: $Exports<'c3/htdocs/js/angular.min'>;
}
declare module 'c3/htdocs/js/bootstrap.min.js' {
  declare module.exports: $Exports<'c3/htdocs/js/bootstrap.min'>;
}
declare module 'c3/htdocs/js/c3-0.4.0.min.js' {
  declare module.exports: $Exports<'c3/htdocs/js/c3-0.4.0.min'>;
}
declare module 'c3/htdocs/js/c3-0.4.8.min.js' {
  declare module.exports: $Exports<'c3/htdocs/js/c3-0.4.8.min'>;
}
declare module 'c3/htdocs/js/c3-0.4.9.min.js' {
  declare module.exports: $Exports<'c3/htdocs/js/c3-0.4.9.min'>;
}
declare module 'c3/htdocs/js/c3.org.js' {
  declare module.exports: $Exports<'c3/htdocs/js/c3.org'>;
}
declare module 'c3/htdocs/js/d3-3.4.13.min.js' {
  declare module.exports: $Exports<'c3/htdocs/js/d3-3.4.13.min'>;
}
declare module 'c3/htdocs/js/d3-3.5.0.min.js' {
  declare module.exports: $Exports<'c3/htdocs/js/d3-3.5.0.min'>;
}
declare module 'c3/htdocs/js/d3-3.5.1.min.js' {
  declare module.exports: $Exports<'c3/htdocs/js/d3-3.5.1.min'>;
}
declare module 'c3/htdocs/js/d3-3.5.2.min.js' {
  declare module.exports: $Exports<'c3/htdocs/js/d3-3.5.2.min'>;
}
declare module 'c3/htdocs/js/d3-3.5.6.js' {
  declare module.exports: $Exports<'c3/htdocs/js/d3-3.5.6'>;
}
declare module 'c3/htdocs/js/jasmine.js' {
  declare module.exports: $Exports<'c3/htdocs/js/jasmine'>;
}
declare module 'c3/htdocs/js/moment-range.js' {
  declare module.exports: $Exports<'c3/htdocs/js/moment-range'>;
}
declare module 'c3/htdocs/js/moment.js' {
  declare module.exports: $Exports<'c3/htdocs/js/moment'>;
}
declare module 'c3/htdocs/js/moment.min.js' {
  declare module.exports: $Exports<'c3/htdocs/js/moment.min'>;
}
declare module 'c3/htdocs/js/require.js' {
  declare module.exports: $Exports<'c3/htdocs/js/require'>;
}
declare module 'c3/htdocs/js/samples/angularjs.js' {
  declare module.exports: $Exports<'c3/htdocs/js/samples/angularjs'>;
}
declare module 'c3/htdocs/js/samples/plugin.js' {
  declare module.exports: $Exports<'c3/htdocs/js/samples/plugin'>;
}
declare module 'c3/htdocs/js/samples/requirejs.js' {
  declare module.exports: $Exports<'c3/htdocs/js/samples/requirejs'>;
}
declare module 'c3/htdocs/js/samples/zoom_reduction.js' {
  declare module.exports: $Exports<'c3/htdocs/js/samples/zoom_reduction'>;
}
declare module 'c3/htdocs/js/test.js' {
  declare module.exports: $Exports<'c3/htdocs/js/test'>;
}
declare module 'c3/karma.conf.js' {
  declare module.exports: $Exports<'c3/karma.conf'>;
}
declare module 'c3/spec/api.axis-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.axis-spec'>;
}
declare module 'c3/spec/api.data-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.data-spec'>;
}
declare module 'c3/spec/api.focus-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.focus-spec'>;
}
declare module 'c3/spec/api.grid-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.grid-spec'>;
}
declare module 'c3/spec/api.load-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.load-spec'>;
}
declare module 'c3/spec/api.region-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.region-spec'>;
}
declare module 'c3/spec/api.zoom-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.zoom-spec'>;
}
declare module 'c3/spec/arc-spec.js' {
  declare module.exports: $Exports<'c3/spec/arc-spec'>;
}
declare module 'c3/spec/axis-spec.js' {
  declare module.exports: $Exports<'c3/spec/axis-spec'>;
}
declare module 'c3/spec/c3-helper.js' {
  declare module.exports: $Exports<'c3/spec/c3-helper'>;
}
declare module 'c3/spec/c3-spec.js' {
  declare module.exports: $Exports<'c3/spec/c3-spec'>;
}
declare module 'c3/spec/class-spec.js' {
  declare module.exports: $Exports<'c3/spec/class-spec'>;
}
declare module 'c3/spec/core-spec.js' {
  declare module.exports: $Exports<'c3/spec/core-spec'>;
}
declare module 'c3/spec/data-spec.js' {
  declare module.exports: $Exports<'c3/spec/data-spec'>;
}
declare module 'c3/spec/domain-spec.js' {
  declare module.exports: $Exports<'c3/spec/domain-spec'>;
}
declare module 'c3/spec/grid-spec.js' {
  declare module.exports: $Exports<'c3/spec/grid-spec'>;
}
declare module 'c3/spec/interaction-spec.js' {
  declare module.exports: $Exports<'c3/spec/interaction-spec'>;
}
declare module 'c3/spec/legend-spec.js' {
  declare module.exports: $Exports<'c3/spec/legend-spec'>;
}
declare module 'c3/spec/shape.bar-spec.js' {
  declare module.exports: $Exports<'c3/spec/shape.bar-spec'>;
}
declare module 'c3/spec/shape.line-spec.js' {
  declare module.exports: $Exports<'c3/spec/shape.line-spec'>;
}
declare module 'c3/spec/svg-helper.js' {
  declare module.exports: $Exports<'c3/spec/svg-helper'>;
}
declare module 'c3/spec/title-spec.js' {
  declare module.exports: $Exports<'c3/spec/title-spec'>;
}
declare module 'c3/spec/tooltip-spec.js' {
  declare module.exports: $Exports<'c3/spec/tooltip-spec'>;
}
declare module 'c3/spec/type-spec.js' {
  declare module.exports: $Exports<'c3/spec/type-spec'>;
}
declare module 'c3/spec/zoom-spec.js' {
  declare module.exports: $Exports<'c3/spec/zoom-spec'>;
}
declare module 'c3/src/api.axis.js' {
  declare module.exports: $Exports<'c3/src/api.axis'>;
}
declare module 'c3/src/api.category.js' {
  declare module.exports: $Exports<'c3/src/api.category'>;
}
declare module 'c3/src/api.chart.js' {
  declare module.exports: $Exports<'c3/src/api.chart'>;
}
declare module 'c3/src/api.color.js' {
  declare module.exports: $Exports<'c3/src/api.color'>;
}
declare module 'c3/src/api.data.js' {
  declare module.exports: $Exports<'c3/src/api.data'>;
}
declare module 'c3/src/api.flow.js' {
  declare module.exports: $Exports<'c3/src/api.flow'>;
}
declare module 'c3/src/api.focus.js' {
  declare module.exports: $Exports<'c3/src/api.focus'>;
}
declare module 'c3/src/api.grid.js' {
  declare module.exports: $Exports<'c3/src/api.grid'>;
}
declare module 'c3/src/api.group.js' {
  declare module.exports: $Exports<'c3/src/api.group'>;
}
declare module 'c3/src/api.legend.js' {
  declare module.exports: $Exports<'c3/src/api.legend'>;
}
declare module 'c3/src/api.load.js' {
  declare module.exports: $Exports<'c3/src/api.load'>;
}
declare module 'c3/src/api.region.js' {
  declare module.exports: $Exports<'c3/src/api.region'>;
}
declare module 'c3/src/api.selection.js' {
  declare module.exports: $Exports<'c3/src/api.selection'>;
}
declare module 'c3/src/api.show.js' {
  declare module.exports: $Exports<'c3/src/api.show'>;
}
declare module 'c3/src/api.tooltip.js' {
  declare module.exports: $Exports<'c3/src/api.tooltip'>;
}
declare module 'c3/src/api.transform.js' {
  declare module.exports: $Exports<'c3/src/api.transform'>;
}
declare module 'c3/src/api.x.js' {
  declare module.exports: $Exports<'c3/src/api.x'>;
}
declare module 'c3/src/api.zoom.js' {
  declare module.exports: $Exports<'c3/src/api.zoom'>;
}
declare module 'c3/src/arc.js' {
  declare module.exports: $Exports<'c3/src/arc'>;
}
declare module 'c3/src/axis.js' {
  declare module.exports: $Exports<'c3/src/axis'>;
}
declare module 'c3/src/c3.axis.js' {
  declare module.exports: $Exports<'c3/src/c3.axis'>;
}
declare module 'c3/src/cache.js' {
  declare module.exports: $Exports<'c3/src/cache'>;
}
declare module 'c3/src/category.js' {
  declare module.exports: $Exports<'c3/src/category'>;
}
declare module 'c3/src/class.js' {
  declare module.exports: $Exports<'c3/src/class'>;
}
declare module 'c3/src/clip.js' {
  declare module.exports: $Exports<'c3/src/clip'>;
}
declare module 'c3/src/color.js' {
  declare module.exports: $Exports<'c3/src/color'>;
}
declare module 'c3/src/config.js' {
  declare module.exports: $Exports<'c3/src/config'>;
}
declare module 'c3/src/core.js' {
  declare module.exports: $Exports<'c3/src/core'>;
}
declare module 'c3/src/data.convert.js' {
  declare module.exports: $Exports<'c3/src/data.convert'>;
}
declare module 'c3/src/data.js' {
  declare module.exports: $Exports<'c3/src/data'>;
}
declare module 'c3/src/data.load.js' {
  declare module.exports: $Exports<'c3/src/data.load'>;
}
declare module 'c3/src/domain.js' {
  declare module.exports: $Exports<'c3/src/domain'>;
}
declare module 'c3/src/drag.js' {
  declare module.exports: $Exports<'c3/src/drag'>;
}
declare module 'c3/src/format.js' {
  declare module.exports: $Exports<'c3/src/format'>;
}
declare module 'c3/src/grid.js' {
  declare module.exports: $Exports<'c3/src/grid'>;
}
declare module 'c3/src/head.js' {
  declare module.exports: $Exports<'c3/src/head'>;
}
declare module 'c3/src/interaction.js' {
  declare module.exports: $Exports<'c3/src/interaction'>;
}
declare module 'c3/src/legend.js' {
  declare module.exports: $Exports<'c3/src/legend'>;
}
declare module 'c3/src/polyfill.js' {
  declare module.exports: $Exports<'c3/src/polyfill'>;
}
declare module 'c3/src/region.js' {
  declare module.exports: $Exports<'c3/src/region'>;
}
declare module 'c3/src/scale.js' {
  declare module.exports: $Exports<'c3/src/scale'>;
}
declare module 'c3/src/selection.js' {
  declare module.exports: $Exports<'c3/src/selection'>;
}
declare module 'c3/src/shape.bar.js' {
  declare module.exports: $Exports<'c3/src/shape.bar'>;
}
declare module 'c3/src/shape.js' {
  declare module.exports: $Exports<'c3/src/shape'>;
}
declare module 'c3/src/shape.line.js' {
  declare module.exports: $Exports<'c3/src/shape.line'>;
}
declare module 'c3/src/size.js' {
  declare module.exports: $Exports<'c3/src/size'>;
}
declare module 'c3/src/subchart.js' {
  declare module.exports: $Exports<'c3/src/subchart'>;
}
declare module 'c3/src/tail.js' {
  declare module.exports: $Exports<'c3/src/tail'>;
}
declare module 'c3/src/text.js' {
  declare module.exports: $Exports<'c3/src/text'>;
}
declare module 'c3/src/title.js' {
  declare module.exports: $Exports<'c3/src/title'>;
}
declare module 'c3/src/tooltip.js' {
  declare module.exports: $Exports<'c3/src/tooltip'>;
}
declare module 'c3/src/type.js' {
  declare module.exports: $Exports<'c3/src/type'>;
}
declare module 'c3/src/ua.js' {
  declare module.exports: $Exports<'c3/src/ua'>;
}
declare module 'c3/src/util.js' {
  declare module.exports: $Exports<'c3/src/util'>;
}
declare module 'c3/src/zoom.js' {
  declare module.exports: $Exports<'c3/src/zoom'>;
}
