// flow-typed signature: 9f641c556437d6f2b85a7ba2f1f968ec
// flow-typed version: <<STUB>>/clipboard-js_v^0.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clipboard-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'clipboard-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clipboard-js/clipboard' {
  declare module.exports: any;
}

declare module 'clipboard-js/clipboard.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clipboard-js/clipboard.js' {
  declare module.exports: $Exports<'clipboard-js/clipboard'>;
}
declare module 'clipboard-js/clipboard.min.js' {
  declare module.exports: $Exports<'clipboard-js/clipboard.min'>;
}
