// flow-typed signature: da631b243d8ded7eed6fdbc17146d46c
// flow-typed version: <<STUB>>/exports-loader_v^0.6.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exports-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'exports-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exports-loader/index' {
  declare module.exports: $Exports<'exports-loader'>;
}
declare module 'exports-loader/index.js' {
  declare module.exports: $Exports<'exports-loader'>;
}
