// flow-typed signature: e7681f1d67ac3bdf875695be5912b5c0
// flow-typed version: <<STUB>>/font-awesome_v^4.5.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome' {
  declare module.exports: any;
}
