// flow-typed signature: ebc86e0e65302a5fb28be30b1c138429
// flow-typed version: <<STUB>>/form-syphon_v0.0.5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'form-syphon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'form-syphon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'form-syphon/gulpfile' {
  declare module.exports: any;
}

declare module 'form-syphon/lib/index' {
  declare module.exports: any;
}

declare module 'form-syphon/src/footer' {
  declare module.exports: any;
}

declare module 'form-syphon/src/header' {
  declare module.exports: any;
}

// Filename aliases
declare module 'form-syphon/gulpfile.js' {
  declare module.exports: $Exports<'form-syphon/gulpfile'>;
}
declare module 'form-syphon/lib/index.js' {
  declare module.exports: $Exports<'form-syphon/lib/index'>;
}
declare module 'form-syphon/src/footer.js' {
  declare module.exports: $Exports<'form-syphon/src/footer'>;
}
declare module 'form-syphon/src/header.js' {
  declare module.exports: $Exports<'form-syphon/src/header'>;
}
