// flow-typed signature: 58d2520cfa25c92af1ba5aee6ca218d3
// flow-typed version: <<STUB>>/jasmine-spec-reporter_v^3.2.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-spec-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-spec-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-spec-reporter/built/configuration-parser' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/configuration' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/display/colors-display' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/display/colors-theme' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/display/display-processor' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/display/processors/default-processor' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/display/processors/spec-colors-processor' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/display/processors/spec-durations-processor' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/display/processors/spec-prefixes-processor' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/display/processors/suite-numbering-processor' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/execution-display' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/execution-metrics' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/main' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/built/spec-reporter' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/examples/node/spec/helpers/reporter' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/examples/node/spec/node-spec' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/examples/protractor/protractor.conf' {
  declare module.exports: any;
}

declare module 'jasmine-spec-reporter/examples/protractor/spec/protractor-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-spec-reporter/built/configuration-parser.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/configuration-parser'>;
}
declare module 'jasmine-spec-reporter/built/configuration.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/configuration'>;
}
declare module 'jasmine-spec-reporter/built/display/colors-display.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/display/colors-display'>;
}
declare module 'jasmine-spec-reporter/built/display/colors-theme.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/display/colors-theme'>;
}
declare module 'jasmine-spec-reporter/built/display/display-processor.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/display/display-processor'>;
}
declare module 'jasmine-spec-reporter/built/display/processors/default-processor.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/display/processors/default-processor'>;
}
declare module 'jasmine-spec-reporter/built/display/processors/spec-colors-processor.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/display/processors/spec-colors-processor'>;
}
declare module 'jasmine-spec-reporter/built/display/processors/spec-durations-processor.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/display/processors/spec-durations-processor'>;
}
declare module 'jasmine-spec-reporter/built/display/processors/spec-prefixes-processor.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/display/processors/spec-prefixes-processor'>;
}
declare module 'jasmine-spec-reporter/built/display/processors/suite-numbering-processor.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/display/processors/suite-numbering-processor'>;
}
declare module 'jasmine-spec-reporter/built/execution-display.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/execution-display'>;
}
declare module 'jasmine-spec-reporter/built/execution-metrics.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/execution-metrics'>;
}
declare module 'jasmine-spec-reporter/built/main.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/main'>;
}
declare module 'jasmine-spec-reporter/built/spec-reporter.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/built/spec-reporter'>;
}
declare module 'jasmine-spec-reporter/examples/node/spec/helpers/reporter.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/examples/node/spec/helpers/reporter'>;
}
declare module 'jasmine-spec-reporter/examples/node/spec/node-spec.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/examples/node/spec/node-spec'>;
}
declare module 'jasmine-spec-reporter/examples/protractor/protractor.conf.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/examples/protractor/protractor.conf'>;
}
declare module 'jasmine-spec-reporter/examples/protractor/spec/protractor-spec.js' {
  declare module.exports: $Exports<'jasmine-spec-reporter/examples/protractor/spec/protractor-spec'>;
}
