// flow-typed signature: 8ec8fddf54b62ea08fe8c6629b01650d
// flow-typed version: <<STUB>>/jasny-bootstrap_v^3.1.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasny-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasny-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasny-bootstrap/dist/js/jasny-bootstrap' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/dist/js/jasny-bootstrap.min' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/application' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/customize.min' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/customizer' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/docs.min' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/ie8-responsive-file-warning' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/raw-files.min' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/vendor/blob' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/vendor/filesaver' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/vendor/holder' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/vendor/jszip.min' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/vendor/less.min' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/assets/js/vendor/uglify.min' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/docs/dist/js/jasny-bootstrap.min' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/grunt/bs-lessdoc-parser' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/grunt/bs-raw-files-generator' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/grunt/shrinkwrap' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/Gruntfile' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/fileinput' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/inputmask' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/offcanvas' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/rowlink' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/tests/unit/fileinput' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/tests/unit/inputmask' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/tests/unit/offcanvas' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/tests/unit/phantom' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/tests/unit/rowlink' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/tests/vendor/jquery' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/tests/vendor/qunit' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/transition' {
  declare module.exports: any;
}

declare module 'jasny-bootstrap/js/wizard' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasny-bootstrap/dist/js/jasny-bootstrap.js' {
  declare module.exports: $Exports<'jasny-bootstrap/dist/js/jasny-bootstrap'>;
}
declare module 'jasny-bootstrap/dist/js/jasny-bootstrap.min.js' {
  declare module.exports: $Exports<'jasny-bootstrap/dist/js/jasny-bootstrap.min'>;
}
declare module 'jasny-bootstrap/docs/assets/js/application.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/application'>;
}
declare module 'jasny-bootstrap/docs/assets/js/customize.min.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/customize.min'>;
}
declare module 'jasny-bootstrap/docs/assets/js/customizer.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/customizer'>;
}
declare module 'jasny-bootstrap/docs/assets/js/docs.min.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/docs.min'>;
}
declare module 'jasny-bootstrap/docs/assets/js/ie8-responsive-file-warning.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/ie8-responsive-file-warning'>;
}
declare module 'jasny-bootstrap/docs/assets/js/raw-files.min.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/raw-files.min'>;
}
declare module 'jasny-bootstrap/docs/assets/js/vendor/blob.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/vendor/blob'>;
}
declare module 'jasny-bootstrap/docs/assets/js/vendor/filesaver.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/vendor/filesaver'>;
}
declare module 'jasny-bootstrap/docs/assets/js/vendor/holder.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/vendor/holder'>;
}
declare module 'jasny-bootstrap/docs/assets/js/vendor/jszip.min.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/vendor/jszip.min'>;
}
declare module 'jasny-bootstrap/docs/assets/js/vendor/less.min.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/vendor/less.min'>;
}
declare module 'jasny-bootstrap/docs/assets/js/vendor/uglify.min.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/assets/js/vendor/uglify.min'>;
}
declare module 'jasny-bootstrap/docs/dist/js/jasny-bootstrap.min.js' {
  declare module.exports: $Exports<'jasny-bootstrap/docs/dist/js/jasny-bootstrap.min'>;
}
declare module 'jasny-bootstrap/grunt/bs-lessdoc-parser.js' {
  declare module.exports: $Exports<'jasny-bootstrap/grunt/bs-lessdoc-parser'>;
}
declare module 'jasny-bootstrap/grunt/bs-raw-files-generator.js' {
  declare module.exports: $Exports<'jasny-bootstrap/grunt/bs-raw-files-generator'>;
}
declare module 'jasny-bootstrap/grunt/shrinkwrap.js' {
  declare module.exports: $Exports<'jasny-bootstrap/grunt/shrinkwrap'>;
}
declare module 'jasny-bootstrap/Gruntfile.js' {
  declare module.exports: $Exports<'jasny-bootstrap/Gruntfile'>;
}
declare module 'jasny-bootstrap/js/fileinput.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/fileinput'>;
}
declare module 'jasny-bootstrap/js/inputmask.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/inputmask'>;
}
declare module 'jasny-bootstrap/js/offcanvas.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/offcanvas'>;
}
declare module 'jasny-bootstrap/js/rowlink.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/rowlink'>;
}
declare module 'jasny-bootstrap/js/tests/unit/fileinput.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/tests/unit/fileinput'>;
}
declare module 'jasny-bootstrap/js/tests/unit/inputmask.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/tests/unit/inputmask'>;
}
declare module 'jasny-bootstrap/js/tests/unit/offcanvas.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/tests/unit/offcanvas'>;
}
declare module 'jasny-bootstrap/js/tests/unit/phantom.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/tests/unit/phantom'>;
}
declare module 'jasny-bootstrap/js/tests/unit/rowlink.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/tests/unit/rowlink'>;
}
declare module 'jasny-bootstrap/js/tests/vendor/jquery.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/tests/vendor/jquery'>;
}
declare module 'jasny-bootstrap/js/tests/vendor/qunit.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/tests/vendor/qunit'>;
}
declare module 'jasny-bootstrap/js/transition.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/transition'>;
}
declare module 'jasny-bootstrap/js/wizard.js' {
  declare module.exports: $Exports<'jasny-bootstrap/js/wizard'>;
}
