// flow-typed signature: 053420c868856b126bec478e363b9a72
// flow-typed version: <<STUB>>/keyboardjs_v^2.2.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keyboardjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'keyboardjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keyboardjs/dist/keyboard' {
  declare module.exports: any;
}

declare module 'keyboardjs/dist/keyboard.min' {
  declare module.exports: any;
}

declare module 'keyboardjs/lib/key-combo' {
  declare module.exports: any;
}

declare module 'keyboardjs/lib/keyboard' {
  declare module.exports: any;
}

declare module 'keyboardjs/lib/locale' {
  declare module.exports: any;
}

declare module 'keyboardjs/locales/us' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keyboardjs/dist/keyboard.js' {
  declare module.exports: $Exports<'keyboardjs/dist/keyboard'>;
}
declare module 'keyboardjs/dist/keyboard.min.js' {
  declare module.exports: $Exports<'keyboardjs/dist/keyboard.min'>;
}
declare module 'keyboardjs/index' {
  declare module.exports: $Exports<'keyboardjs'>;
}
declare module 'keyboardjs/index.js' {
  declare module.exports: $Exports<'keyboardjs'>;
}
declare module 'keyboardjs/lib/key-combo.js' {
  declare module.exports: $Exports<'keyboardjs/lib/key-combo'>;
}
declare module 'keyboardjs/lib/keyboard.js' {
  declare module.exports: $Exports<'keyboardjs/lib/keyboard'>;
}
declare module 'keyboardjs/lib/locale.js' {
  declare module.exports: $Exports<'keyboardjs/lib/locale'>;
}
declare module 'keyboardjs/locales/us.js' {
  declare module.exports: $Exports<'keyboardjs/locales/us'>;
}
