// flow-typed signature: e9a46e436f07e23cc755bc866dcc2ac6
// flow-typed version: <<STUB>>/less-loader_v^2.2.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less-loader/stringify.loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less-loader/index' {
  declare module.exports: $Exports<'less-loader'>;
}
declare module 'less-loader/index.js' {
  declare module.exports: $Exports<'less-loader'>;
}
declare module 'less-loader/stringify.loader.js' {
  declare module.exports: $Exports<'less-loader/stringify.loader'>;
}
