// flow-typed signature: db125d754ea49742426e24b46c240681
// flow-typed version: <<STUB>>/mjs_v^1.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mjs/index' {
  declare module.exports: $Exports<'mjs'>;
}
declare module 'mjs/index.js' {
  declare module.exports: $Exports<'mjs'>;
}
