// flow-typed signature: 4adf24f7385b47fb43f95f9dfd49859c
// flow-typed version: <<STUB>>/mock-require_v^1.2.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-require/test/exported-fn' {
  declare module.exports: any;
}

declare module 'mock-require/test/exported-obj' {
  declare module.exports: any;
}

declare module 'mock-require/test/index' {
  declare module.exports: any;
}

declare module 'mock-require/test/module-a' {
  declare module.exports: any;
}

declare module 'mock-require/test/module-b' {
  declare module.exports: any;
}

declare module 'mock-require/test/nested/module-c' {
  declare module.exports: any;
}

declare module 'mock-require/test/throw-exception-runner' {
  declare module.exports: any;
}

declare module 'mock-require/test/throw-exception' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-require/index' {
  declare module.exports: $Exports<'mock-require'>;
}
declare module 'mock-require/index.js' {
  declare module.exports: $Exports<'mock-require'>;
}
declare module 'mock-require/test/exported-fn.js' {
  declare module.exports: $Exports<'mock-require/test/exported-fn'>;
}
declare module 'mock-require/test/exported-obj.js' {
  declare module.exports: $Exports<'mock-require/test/exported-obj'>;
}
declare module 'mock-require/test/index.js' {
  declare module.exports: $Exports<'mock-require/test/index'>;
}
declare module 'mock-require/test/module-a.js' {
  declare module.exports: $Exports<'mock-require/test/module-a'>;
}
declare module 'mock-require/test/module-b.js' {
  declare module.exports: $Exports<'mock-require/test/module-b'>;
}
declare module 'mock-require/test/nested/module-c.js' {
  declare module.exports: $Exports<'mock-require/test/nested/module-c'>;
}
declare module 'mock-require/test/throw-exception-runner.js' {
  declare module.exports: $Exports<'mock-require/test/throw-exception-runner'>;
}
declare module 'mock-require/test/throw-exception.js' {
  declare module.exports: $Exports<'mock-require/test/throw-exception'>;
}
