// flow-typed signature: 5516e815d596aad5641fad356c9a070c
// flow-typed version: <<STUB>>/nouislider_v^8.2.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nouislider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nouislider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nouislider/distribute/nouislider' {
  declare module.exports: any;
}

declare module 'nouislider/distribute/nouislider.min' {
  declare module.exports: any;
}

declare module 'nouislider/Gruntfile' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/constants' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/helpers' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/interface' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/intro' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/options' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/outro' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/pips' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/range' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope_end' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope_events' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope_helpers' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope_start' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/structure' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/tooltips' {
  declare module.exports: any;
}

declare module 'nouislider/tests/addon_pips' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_binding' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_errors' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_get-step' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_limit' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_non-linear-rtl' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_rtl_update_options' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_rtl' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_rtl2' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_setting-getting' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_step' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_unordered' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_update-numbers' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_update' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_values' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nouislider/distribute/nouislider.js' {
  declare module.exports: $Exports<'nouislider/distribute/nouislider'>;
}
declare module 'nouislider/distribute/nouislider.min.js' {
  declare module.exports: $Exports<'nouislider/distribute/nouislider.min'>;
}
declare module 'nouislider/Gruntfile.js' {
  declare module.exports: $Exports<'nouislider/Gruntfile'>;
}
declare module 'nouislider/src/js/constants.js' {
  declare module.exports: $Exports<'nouislider/src/js/constants'>;
}
declare module 'nouislider/src/js/helpers.js' {
  declare module.exports: $Exports<'nouislider/src/js/helpers'>;
}
declare module 'nouislider/src/js/interface.js' {
  declare module.exports: $Exports<'nouislider/src/js/interface'>;
}
declare module 'nouislider/src/js/intro.js' {
  declare module.exports: $Exports<'nouislider/src/js/intro'>;
}
declare module 'nouislider/src/js/options.js' {
  declare module.exports: $Exports<'nouislider/src/js/options'>;
}
declare module 'nouislider/src/js/outro.js' {
  declare module.exports: $Exports<'nouislider/src/js/outro'>;
}
declare module 'nouislider/src/js/pips.js' {
  declare module.exports: $Exports<'nouislider/src/js/pips'>;
}
declare module 'nouislider/src/js/range.js' {
  declare module.exports: $Exports<'nouislider/src/js/range'>;
}
declare module 'nouislider/src/js/scope_end.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope_end'>;
}
declare module 'nouislider/src/js/scope_events.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope_events'>;
}
declare module 'nouislider/src/js/scope_helpers.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope_helpers'>;
}
declare module 'nouislider/src/js/scope_start.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope_start'>;
}
declare module 'nouislider/src/js/scope.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope'>;
}
declare module 'nouislider/src/js/structure.js' {
  declare module.exports: $Exports<'nouislider/src/js/structure'>;
}
declare module 'nouislider/src/js/tooltips.js' {
  declare module.exports: $Exports<'nouislider/src/js/tooltips'>;
}
declare module 'nouislider/tests/addon_pips.js' {
  declare module.exports: $Exports<'nouislider/tests/addon_pips'>;
}
declare module 'nouislider/tests/slider_binding.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_binding'>;
}
declare module 'nouislider/tests/slider_errors.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_errors'>;
}
declare module 'nouislider/tests/slider_get-step.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_get-step'>;
}
declare module 'nouislider/tests/slider_limit.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_limit'>;
}
declare module 'nouislider/tests/slider_non-linear-rtl.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_non-linear-rtl'>;
}
declare module 'nouislider/tests/slider_rtl_update_options.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_rtl_update_options'>;
}
declare module 'nouislider/tests/slider_rtl.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_rtl'>;
}
declare module 'nouislider/tests/slider_rtl2.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_rtl2'>;
}
declare module 'nouislider/tests/slider_setting-getting.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_setting-getting'>;
}
declare module 'nouislider/tests/slider_step.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_step'>;
}
declare module 'nouislider/tests/slider_unordered.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_unordered'>;
}
declare module 'nouislider/tests/slider_update-numbers.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_update-numbers'>;
}
declare module 'nouislider/tests/slider_update.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_update'>;
}
declare module 'nouislider/tests/slider_values.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_values'>;
}
