// flow-typed signature: 08ac9dc480845460b5d289895331698d
// flow-typed version: <<STUB>>/stats.js_v^1.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stats.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stats.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stats.js/build/stats.min' {
  declare module.exports: any;
}

declare module 'stats.js/src/Stats' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stats.js/build/stats.min.js' {
  declare module.exports: $Exports<'stats.js/build/stats.min'>;
}
declare module 'stats.js/src/Stats.js' {
  declare module.exports: $Exports<'stats.js/src/Stats'>;
}
