// flow-typed signature: 4d53e13f300d2e10529b69aa60ab1aab
// flow-typed version: <<STUB>>/three.js_vgeorgwiese/three.js#scm_oxalis/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'three.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'three.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'three.js/build/three' {
  declare module.exports: any;
}

declare module 'three.js/build/three.min' {
  declare module.exports: any;
}

declare module 'three.js/examples/js/controls/TrackballControls' {
  declare module.exports: any;
}

declare module 'three.js/examples/js/math/ColorConverter' {
  declare module.exports: any;
}

declare module 'three.js/src/cameras/Camera' {
  declare module.exports: any;
}

declare module 'three.js/src/cameras/OrthographicCamera' {
  declare module.exports: any;
}

declare module 'three.js/src/cameras/PerspectiveCamera' {
  declare module.exports: any;
}

declare module 'three.js/src/core/BufferGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/core/Clock' {
  declare module.exports: any;
}

declare module 'three.js/src/core/EventDispatcher' {
  declare module.exports: any;
}

declare module 'three.js/src/core/Face3' {
  declare module.exports: any;
}

declare module 'three.js/src/core/Face4' {
  declare module.exports: any;
}

declare module 'three.js/src/core/Geometry' {
  declare module.exports: any;
}

declare module 'three.js/src/core/Object3D' {
  declare module.exports: any;
}

declare module 'three.js/src/core/Projector' {
  declare module.exports: any;
}

declare module 'three.js/src/core/Raycaster' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/animation/Animation' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/animation/AnimationHandler' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/animation/AnimationMorphTarget' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/animation/KeyFrameAnimation' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/cameras/CombinedCamera' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/cameras/CubeCamera' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/core/Curve' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/core/CurvePath' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/core/Gyroscope' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/core/Path' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/core/Shape' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/ArcCurve' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/ClosedSplineCurve3' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/CubicBezierCurve' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/CubicBezierCurve3' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/EllipseCurve' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/LineCurve' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/LineCurve3' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/QuadraticBezierCurve' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/QuadraticBezierCurve3' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/SplineCurve' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/curves/SplineCurve3' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/FontUtils' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/CircleGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/CubeGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/CylinderGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/ExtrudeGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/IcosahedronGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/LatheGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/OctahedronGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/ParametricGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/PlaneGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/PolyhedronGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/RingGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/ShapeGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/SphereGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/TetrahedronGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/TextGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/TorusGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/TorusKnotGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/geometries/TubeGeometry' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/GeometryUtils' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/ArrowHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/AxisHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/BoundingBoxHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/BoxHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/CameraHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/DirectionalLightHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/EdgesHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/FaceNormalsHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/GridHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/HemisphereLightHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/PointLightHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/SpotLightHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/VertexNormalsHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/VertexTangentsHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/helpers/WireframeHelper' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/ImageUtils' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/objects/ImmediateRenderObject' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/objects/LensFlare' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/objects/MorphBlendMesh' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/renderers/plugins/DepthPassPlugin' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/renderers/plugins/LensFlarePlugin' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/renderers/plugins/ShadowMapPlugin' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/renderers/plugins/SpritePlugin' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/SceneUtils' {
  declare module.exports: any;
}

declare module 'three.js/src/extras/shaders/ShaderFlares' {
  declare module.exports: any;
}

declare module 'three.js/src/lights/AmbientLight' {
  declare module.exports: any;
}

declare module 'three.js/src/lights/AreaLight' {
  declare module.exports: any;
}

declare module 'three.js/src/lights/DirectionalLight' {
  declare module.exports: any;
}

declare module 'three.js/src/lights/HemisphereLight' {
  declare module.exports: any;
}

declare module 'three.js/src/lights/Light' {
  declare module.exports: any;
}

declare module 'three.js/src/lights/PointLight' {
  declare module.exports: any;
}

declare module 'three.js/src/lights/SpotLight' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/BufferGeometryLoader' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/GeometryLoader' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/ImageLoader' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/JSONLoader' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/Loader' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/LoadingManager' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/MaterialLoader' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/ObjectLoader' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/SceneLoader' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/TextureLoader' {
  declare module.exports: any;
}

declare module 'three.js/src/loaders/XHRLoader' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/LineBasicMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/LineDashedMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/Material' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/MeshBasicMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/MeshDepthMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/MeshFaceMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/MeshLambertMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/MeshNormalMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/MeshPhongMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/ParticleSystemMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/ShaderMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/SpriteCanvasMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/materials/SpriteMaterial' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Box2' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Box3' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Color' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Euler' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Frustum' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Line3' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Math' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Matrix3' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Matrix4' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Plane' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Quaternion' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Ray' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Sphere' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Spline' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Triangle' {
  declare module.exports: any;
}

declare module 'three.js/src/math/UV' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Vector2' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Vector3' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Vector4' {
  declare module.exports: any;
}

declare module 'three.js/src/math/Vertex' {
  declare module.exports: any;
}

declare module 'three.js/src/objects/Bone' {
  declare module.exports: any;
}

declare module 'three.js/src/objects/Line' {
  declare module.exports: any;
}

declare module 'three.js/src/objects/LOD' {
  declare module.exports: any;
}

declare module 'three.js/src/objects/Mesh' {
  declare module.exports: any;
}

declare module 'three.js/src/objects/MorphAnimMesh' {
  declare module.exports: any;
}

declare module 'three.js/src/objects/ParticleSystem' {
  declare module.exports: any;
}

declare module 'three.js/src/objects/SkinnedMesh' {
  declare module.exports: any;
}

declare module 'three.js/src/objects/Sprite' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/CanvasRenderer' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/renderables/RenderableFace3' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/renderables/RenderableLine' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/renderables/RenderableObject' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/renderables/RenderableSprite' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/renderables/RenderableVertex' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/shaders/ShaderChunk' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/shaders/ShaderLib' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/shaders/UniformsLib' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/shaders/UniformsUtils' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/WebGLRenderer' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/WebGLRenderTarget' {
  declare module.exports: any;
}

declare module 'three.js/src/renderers/WebGLRenderTargetCube' {
  declare module.exports: any;
}

declare module 'three.js/src/scenes/Fog' {
  declare module.exports: any;
}

declare module 'three.js/src/scenes/FogExp2' {
  declare module.exports: any;
}

declare module 'three.js/src/scenes/Scene' {
  declare module.exports: any;
}

declare module 'three.js/src/textures/CompressedTexture' {
  declare module.exports: any;
}

declare module 'three.js/src/textures/DataTexture' {
  declare module.exports: any;
}

declare module 'three.js/src/textures/Texture' {
  declare module.exports: any;
}

declare module 'three.js/src/Three' {
  declare module.exports: any;
}

// Filename aliases
declare module 'three.js/build/three.js' {
  declare module.exports: $Exports<'three.js/build/three'>;
}
declare module 'three.js/build/three.min.js' {
  declare module.exports: $Exports<'three.js/build/three.min'>;
}
declare module 'three.js/examples/js/controls/TrackballControls.js' {
  declare module.exports: $Exports<'three.js/examples/js/controls/TrackballControls'>;
}
declare module 'three.js/examples/js/math/ColorConverter.js' {
  declare module.exports: $Exports<'three.js/examples/js/math/ColorConverter'>;
}
declare module 'three.js/src/cameras/Camera.js' {
  declare module.exports: $Exports<'three.js/src/cameras/Camera'>;
}
declare module 'three.js/src/cameras/OrthographicCamera.js' {
  declare module.exports: $Exports<'three.js/src/cameras/OrthographicCamera'>;
}
declare module 'three.js/src/cameras/PerspectiveCamera.js' {
  declare module.exports: $Exports<'three.js/src/cameras/PerspectiveCamera'>;
}
declare module 'three.js/src/core/BufferGeometry.js' {
  declare module.exports: $Exports<'three.js/src/core/BufferGeometry'>;
}
declare module 'three.js/src/core/Clock.js' {
  declare module.exports: $Exports<'three.js/src/core/Clock'>;
}
declare module 'three.js/src/core/EventDispatcher.js' {
  declare module.exports: $Exports<'three.js/src/core/EventDispatcher'>;
}
declare module 'three.js/src/core/Face3.js' {
  declare module.exports: $Exports<'three.js/src/core/Face3'>;
}
declare module 'three.js/src/core/Face4.js' {
  declare module.exports: $Exports<'three.js/src/core/Face4'>;
}
declare module 'three.js/src/core/Geometry.js' {
  declare module.exports: $Exports<'three.js/src/core/Geometry'>;
}
declare module 'three.js/src/core/Object3D.js' {
  declare module.exports: $Exports<'three.js/src/core/Object3D'>;
}
declare module 'three.js/src/core/Projector.js' {
  declare module.exports: $Exports<'three.js/src/core/Projector'>;
}
declare module 'three.js/src/core/Raycaster.js' {
  declare module.exports: $Exports<'three.js/src/core/Raycaster'>;
}
declare module 'three.js/src/extras/animation/Animation.js' {
  declare module.exports: $Exports<'three.js/src/extras/animation/Animation'>;
}
declare module 'three.js/src/extras/animation/AnimationHandler.js' {
  declare module.exports: $Exports<'three.js/src/extras/animation/AnimationHandler'>;
}
declare module 'three.js/src/extras/animation/AnimationMorphTarget.js' {
  declare module.exports: $Exports<'three.js/src/extras/animation/AnimationMorphTarget'>;
}
declare module 'three.js/src/extras/animation/KeyFrameAnimation.js' {
  declare module.exports: $Exports<'three.js/src/extras/animation/KeyFrameAnimation'>;
}
declare module 'three.js/src/extras/cameras/CombinedCamera.js' {
  declare module.exports: $Exports<'three.js/src/extras/cameras/CombinedCamera'>;
}
declare module 'three.js/src/extras/cameras/CubeCamera.js' {
  declare module.exports: $Exports<'three.js/src/extras/cameras/CubeCamera'>;
}
declare module 'three.js/src/extras/core/Curve.js' {
  declare module.exports: $Exports<'three.js/src/extras/core/Curve'>;
}
declare module 'three.js/src/extras/core/CurvePath.js' {
  declare module.exports: $Exports<'three.js/src/extras/core/CurvePath'>;
}
declare module 'three.js/src/extras/core/Gyroscope.js' {
  declare module.exports: $Exports<'three.js/src/extras/core/Gyroscope'>;
}
declare module 'three.js/src/extras/core/Path.js' {
  declare module.exports: $Exports<'three.js/src/extras/core/Path'>;
}
declare module 'three.js/src/extras/core/Shape.js' {
  declare module.exports: $Exports<'three.js/src/extras/core/Shape'>;
}
declare module 'three.js/src/extras/curves/ArcCurve.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/ArcCurve'>;
}
declare module 'three.js/src/extras/curves/ClosedSplineCurve3.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/ClosedSplineCurve3'>;
}
declare module 'three.js/src/extras/curves/CubicBezierCurve.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/CubicBezierCurve'>;
}
declare module 'three.js/src/extras/curves/CubicBezierCurve3.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/CubicBezierCurve3'>;
}
declare module 'three.js/src/extras/curves/EllipseCurve.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/EllipseCurve'>;
}
declare module 'three.js/src/extras/curves/LineCurve.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/LineCurve'>;
}
declare module 'three.js/src/extras/curves/LineCurve3.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/LineCurve3'>;
}
declare module 'three.js/src/extras/curves/QuadraticBezierCurve.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/QuadraticBezierCurve'>;
}
declare module 'three.js/src/extras/curves/QuadraticBezierCurve3.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/QuadraticBezierCurve3'>;
}
declare module 'three.js/src/extras/curves/SplineCurve.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/SplineCurve'>;
}
declare module 'three.js/src/extras/curves/SplineCurve3.js' {
  declare module.exports: $Exports<'three.js/src/extras/curves/SplineCurve3'>;
}
declare module 'three.js/src/extras/FontUtils.js' {
  declare module.exports: $Exports<'three.js/src/extras/FontUtils'>;
}
declare module 'three.js/src/extras/geometries/CircleGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/CircleGeometry'>;
}
declare module 'three.js/src/extras/geometries/CubeGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/CubeGeometry'>;
}
declare module 'three.js/src/extras/geometries/CylinderGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/CylinderGeometry'>;
}
declare module 'three.js/src/extras/geometries/ExtrudeGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/ExtrudeGeometry'>;
}
declare module 'three.js/src/extras/geometries/IcosahedronGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/IcosahedronGeometry'>;
}
declare module 'three.js/src/extras/geometries/LatheGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/LatheGeometry'>;
}
declare module 'three.js/src/extras/geometries/OctahedronGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/OctahedronGeometry'>;
}
declare module 'three.js/src/extras/geometries/ParametricGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/ParametricGeometry'>;
}
declare module 'three.js/src/extras/geometries/PlaneGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/PlaneGeometry'>;
}
declare module 'three.js/src/extras/geometries/PolyhedronGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/PolyhedronGeometry'>;
}
declare module 'three.js/src/extras/geometries/RingGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/RingGeometry'>;
}
declare module 'three.js/src/extras/geometries/ShapeGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/ShapeGeometry'>;
}
declare module 'three.js/src/extras/geometries/SphereGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/SphereGeometry'>;
}
declare module 'three.js/src/extras/geometries/TetrahedronGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/TetrahedronGeometry'>;
}
declare module 'three.js/src/extras/geometries/TextGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/TextGeometry'>;
}
declare module 'three.js/src/extras/geometries/TorusGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/TorusGeometry'>;
}
declare module 'three.js/src/extras/geometries/TorusKnotGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/TorusKnotGeometry'>;
}
declare module 'three.js/src/extras/geometries/TubeGeometry.js' {
  declare module.exports: $Exports<'three.js/src/extras/geometries/TubeGeometry'>;
}
declare module 'three.js/src/extras/GeometryUtils.js' {
  declare module.exports: $Exports<'three.js/src/extras/GeometryUtils'>;
}
declare module 'three.js/src/extras/helpers/ArrowHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/ArrowHelper'>;
}
declare module 'three.js/src/extras/helpers/AxisHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/AxisHelper'>;
}
declare module 'three.js/src/extras/helpers/BoundingBoxHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/BoundingBoxHelper'>;
}
declare module 'three.js/src/extras/helpers/BoxHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/BoxHelper'>;
}
declare module 'three.js/src/extras/helpers/CameraHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/CameraHelper'>;
}
declare module 'three.js/src/extras/helpers/DirectionalLightHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/DirectionalLightHelper'>;
}
declare module 'three.js/src/extras/helpers/EdgesHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/EdgesHelper'>;
}
declare module 'three.js/src/extras/helpers/FaceNormalsHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/FaceNormalsHelper'>;
}
declare module 'three.js/src/extras/helpers/GridHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/GridHelper'>;
}
declare module 'three.js/src/extras/helpers/HemisphereLightHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/HemisphereLightHelper'>;
}
declare module 'three.js/src/extras/helpers/PointLightHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/PointLightHelper'>;
}
declare module 'three.js/src/extras/helpers/SpotLightHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/SpotLightHelper'>;
}
declare module 'three.js/src/extras/helpers/VertexNormalsHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/VertexNormalsHelper'>;
}
declare module 'three.js/src/extras/helpers/VertexTangentsHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/VertexTangentsHelper'>;
}
declare module 'three.js/src/extras/helpers/WireframeHelper.js' {
  declare module.exports: $Exports<'three.js/src/extras/helpers/WireframeHelper'>;
}
declare module 'three.js/src/extras/ImageUtils.js' {
  declare module.exports: $Exports<'three.js/src/extras/ImageUtils'>;
}
declare module 'three.js/src/extras/objects/ImmediateRenderObject.js' {
  declare module.exports: $Exports<'three.js/src/extras/objects/ImmediateRenderObject'>;
}
declare module 'three.js/src/extras/objects/LensFlare.js' {
  declare module.exports: $Exports<'three.js/src/extras/objects/LensFlare'>;
}
declare module 'three.js/src/extras/objects/MorphBlendMesh.js' {
  declare module.exports: $Exports<'three.js/src/extras/objects/MorphBlendMesh'>;
}
declare module 'three.js/src/extras/renderers/plugins/DepthPassPlugin.js' {
  declare module.exports: $Exports<'three.js/src/extras/renderers/plugins/DepthPassPlugin'>;
}
declare module 'three.js/src/extras/renderers/plugins/LensFlarePlugin.js' {
  declare module.exports: $Exports<'three.js/src/extras/renderers/plugins/LensFlarePlugin'>;
}
declare module 'three.js/src/extras/renderers/plugins/ShadowMapPlugin.js' {
  declare module.exports: $Exports<'three.js/src/extras/renderers/plugins/ShadowMapPlugin'>;
}
declare module 'three.js/src/extras/renderers/plugins/SpritePlugin.js' {
  declare module.exports: $Exports<'three.js/src/extras/renderers/plugins/SpritePlugin'>;
}
declare module 'three.js/src/extras/SceneUtils.js' {
  declare module.exports: $Exports<'three.js/src/extras/SceneUtils'>;
}
declare module 'three.js/src/extras/shaders/ShaderFlares.js' {
  declare module.exports: $Exports<'three.js/src/extras/shaders/ShaderFlares'>;
}
declare module 'three.js/src/lights/AmbientLight.js' {
  declare module.exports: $Exports<'three.js/src/lights/AmbientLight'>;
}
declare module 'three.js/src/lights/AreaLight.js' {
  declare module.exports: $Exports<'three.js/src/lights/AreaLight'>;
}
declare module 'three.js/src/lights/DirectionalLight.js' {
  declare module.exports: $Exports<'three.js/src/lights/DirectionalLight'>;
}
declare module 'three.js/src/lights/HemisphereLight.js' {
  declare module.exports: $Exports<'three.js/src/lights/HemisphereLight'>;
}
declare module 'three.js/src/lights/Light.js' {
  declare module.exports: $Exports<'three.js/src/lights/Light'>;
}
declare module 'three.js/src/lights/PointLight.js' {
  declare module.exports: $Exports<'three.js/src/lights/PointLight'>;
}
declare module 'three.js/src/lights/SpotLight.js' {
  declare module.exports: $Exports<'three.js/src/lights/SpotLight'>;
}
declare module 'three.js/src/loaders/BufferGeometryLoader.js' {
  declare module.exports: $Exports<'three.js/src/loaders/BufferGeometryLoader'>;
}
declare module 'three.js/src/loaders/GeometryLoader.js' {
  declare module.exports: $Exports<'three.js/src/loaders/GeometryLoader'>;
}
declare module 'three.js/src/loaders/ImageLoader.js' {
  declare module.exports: $Exports<'three.js/src/loaders/ImageLoader'>;
}
declare module 'three.js/src/loaders/JSONLoader.js' {
  declare module.exports: $Exports<'three.js/src/loaders/JSONLoader'>;
}
declare module 'three.js/src/loaders/Loader.js' {
  declare module.exports: $Exports<'three.js/src/loaders/Loader'>;
}
declare module 'three.js/src/loaders/LoadingManager.js' {
  declare module.exports: $Exports<'three.js/src/loaders/LoadingManager'>;
}
declare module 'three.js/src/loaders/MaterialLoader.js' {
  declare module.exports: $Exports<'three.js/src/loaders/MaterialLoader'>;
}
declare module 'three.js/src/loaders/ObjectLoader.js' {
  declare module.exports: $Exports<'three.js/src/loaders/ObjectLoader'>;
}
declare module 'three.js/src/loaders/SceneLoader.js' {
  declare module.exports: $Exports<'three.js/src/loaders/SceneLoader'>;
}
declare module 'three.js/src/loaders/TextureLoader.js' {
  declare module.exports: $Exports<'three.js/src/loaders/TextureLoader'>;
}
declare module 'three.js/src/loaders/XHRLoader.js' {
  declare module.exports: $Exports<'three.js/src/loaders/XHRLoader'>;
}
declare module 'three.js/src/materials/LineBasicMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/LineBasicMaterial'>;
}
declare module 'three.js/src/materials/LineDashedMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/LineDashedMaterial'>;
}
declare module 'three.js/src/materials/Material.js' {
  declare module.exports: $Exports<'three.js/src/materials/Material'>;
}
declare module 'three.js/src/materials/MeshBasicMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/MeshBasicMaterial'>;
}
declare module 'three.js/src/materials/MeshDepthMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/MeshDepthMaterial'>;
}
declare module 'three.js/src/materials/MeshFaceMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/MeshFaceMaterial'>;
}
declare module 'three.js/src/materials/MeshLambertMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/MeshLambertMaterial'>;
}
declare module 'three.js/src/materials/MeshNormalMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/MeshNormalMaterial'>;
}
declare module 'three.js/src/materials/MeshPhongMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/MeshPhongMaterial'>;
}
declare module 'three.js/src/materials/ParticleSystemMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/ParticleSystemMaterial'>;
}
declare module 'three.js/src/materials/ShaderMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/ShaderMaterial'>;
}
declare module 'three.js/src/materials/SpriteCanvasMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/SpriteCanvasMaterial'>;
}
declare module 'three.js/src/materials/SpriteMaterial.js' {
  declare module.exports: $Exports<'three.js/src/materials/SpriteMaterial'>;
}
declare module 'three.js/src/math/Box2.js' {
  declare module.exports: $Exports<'three.js/src/math/Box2'>;
}
declare module 'three.js/src/math/Box3.js' {
  declare module.exports: $Exports<'three.js/src/math/Box3'>;
}
declare module 'three.js/src/math/Color.js' {
  declare module.exports: $Exports<'three.js/src/math/Color'>;
}
declare module 'three.js/src/math/Euler.js' {
  declare module.exports: $Exports<'three.js/src/math/Euler'>;
}
declare module 'three.js/src/math/Frustum.js' {
  declare module.exports: $Exports<'three.js/src/math/Frustum'>;
}
declare module 'three.js/src/math/Line3.js' {
  declare module.exports: $Exports<'three.js/src/math/Line3'>;
}
declare module 'three.js/src/math/Math.js' {
  declare module.exports: $Exports<'three.js/src/math/Math'>;
}
declare module 'three.js/src/math/Matrix3.js' {
  declare module.exports: $Exports<'three.js/src/math/Matrix3'>;
}
declare module 'three.js/src/math/Matrix4.js' {
  declare module.exports: $Exports<'three.js/src/math/Matrix4'>;
}
declare module 'three.js/src/math/Plane.js' {
  declare module.exports: $Exports<'three.js/src/math/Plane'>;
}
declare module 'three.js/src/math/Quaternion.js' {
  declare module.exports: $Exports<'three.js/src/math/Quaternion'>;
}
declare module 'three.js/src/math/Ray.js' {
  declare module.exports: $Exports<'three.js/src/math/Ray'>;
}
declare module 'three.js/src/math/Sphere.js' {
  declare module.exports: $Exports<'three.js/src/math/Sphere'>;
}
declare module 'three.js/src/math/Spline.js' {
  declare module.exports: $Exports<'three.js/src/math/Spline'>;
}
declare module 'three.js/src/math/Triangle.js' {
  declare module.exports: $Exports<'three.js/src/math/Triangle'>;
}
declare module 'three.js/src/math/UV.js' {
  declare module.exports: $Exports<'three.js/src/math/UV'>;
}
declare module 'three.js/src/math/Vector2.js' {
  declare module.exports: $Exports<'three.js/src/math/Vector2'>;
}
declare module 'three.js/src/math/Vector3.js' {
  declare module.exports: $Exports<'three.js/src/math/Vector3'>;
}
declare module 'three.js/src/math/Vector4.js' {
  declare module.exports: $Exports<'three.js/src/math/Vector4'>;
}
declare module 'three.js/src/math/Vertex.js' {
  declare module.exports: $Exports<'three.js/src/math/Vertex'>;
}
declare module 'three.js/src/objects/Bone.js' {
  declare module.exports: $Exports<'three.js/src/objects/Bone'>;
}
declare module 'three.js/src/objects/Line.js' {
  declare module.exports: $Exports<'three.js/src/objects/Line'>;
}
declare module 'three.js/src/objects/LOD.js' {
  declare module.exports: $Exports<'three.js/src/objects/LOD'>;
}
declare module 'three.js/src/objects/Mesh.js' {
  declare module.exports: $Exports<'three.js/src/objects/Mesh'>;
}
declare module 'three.js/src/objects/MorphAnimMesh.js' {
  declare module.exports: $Exports<'three.js/src/objects/MorphAnimMesh'>;
}
declare module 'three.js/src/objects/ParticleSystem.js' {
  declare module.exports: $Exports<'three.js/src/objects/ParticleSystem'>;
}
declare module 'three.js/src/objects/SkinnedMesh.js' {
  declare module.exports: $Exports<'three.js/src/objects/SkinnedMesh'>;
}
declare module 'three.js/src/objects/Sprite.js' {
  declare module.exports: $Exports<'three.js/src/objects/Sprite'>;
}
declare module 'three.js/src/renderers/CanvasRenderer.js' {
  declare module.exports: $Exports<'three.js/src/renderers/CanvasRenderer'>;
}
declare module 'three.js/src/renderers/renderables/RenderableFace3.js' {
  declare module.exports: $Exports<'three.js/src/renderers/renderables/RenderableFace3'>;
}
declare module 'three.js/src/renderers/renderables/RenderableLine.js' {
  declare module.exports: $Exports<'three.js/src/renderers/renderables/RenderableLine'>;
}
declare module 'three.js/src/renderers/renderables/RenderableObject.js' {
  declare module.exports: $Exports<'three.js/src/renderers/renderables/RenderableObject'>;
}
declare module 'three.js/src/renderers/renderables/RenderableSprite.js' {
  declare module.exports: $Exports<'three.js/src/renderers/renderables/RenderableSprite'>;
}
declare module 'three.js/src/renderers/renderables/RenderableVertex.js' {
  declare module.exports: $Exports<'three.js/src/renderers/renderables/RenderableVertex'>;
}
declare module 'three.js/src/renderers/shaders/ShaderChunk.js' {
  declare module.exports: $Exports<'three.js/src/renderers/shaders/ShaderChunk'>;
}
declare module 'three.js/src/renderers/shaders/ShaderLib.js' {
  declare module.exports: $Exports<'three.js/src/renderers/shaders/ShaderLib'>;
}
declare module 'three.js/src/renderers/shaders/UniformsLib.js' {
  declare module.exports: $Exports<'three.js/src/renderers/shaders/UniformsLib'>;
}
declare module 'three.js/src/renderers/shaders/UniformsUtils.js' {
  declare module.exports: $Exports<'three.js/src/renderers/shaders/UniformsUtils'>;
}
declare module 'three.js/src/renderers/WebGLRenderer.js' {
  declare module.exports: $Exports<'three.js/src/renderers/WebGLRenderer'>;
}
declare module 'three.js/src/renderers/WebGLRenderTarget.js' {
  declare module.exports: $Exports<'three.js/src/renderers/WebGLRenderTarget'>;
}
declare module 'three.js/src/renderers/WebGLRenderTargetCube.js' {
  declare module.exports: $Exports<'three.js/src/renderers/WebGLRenderTargetCube'>;
}
declare module 'three.js/src/scenes/Fog.js' {
  declare module.exports: $Exports<'three.js/src/scenes/Fog'>;
}
declare module 'three.js/src/scenes/FogExp2.js' {
  declare module.exports: $Exports<'three.js/src/scenes/FogExp2'>;
}
declare module 'three.js/src/scenes/Scene.js' {
  declare module.exports: $Exports<'three.js/src/scenes/Scene'>;
}
declare module 'three.js/src/textures/CompressedTexture.js' {
  declare module.exports: $Exports<'three.js/src/textures/CompressedTexture'>;
}
declare module 'three.js/src/textures/DataTexture.js' {
  declare module.exports: $Exports<'three.js/src/textures/DataTexture'>;
}
declare module 'three.js/src/textures/Texture.js' {
  declare module.exports: $Exports<'three.js/src/textures/Texture'>;
}
declare module 'three.js/src/Three.js' {
  declare module.exports: $Exports<'three.js/src/Three'>;
}
