// flow-typed signature: 45d63d16f1de787e171a606b2deb1c5f
// flow-typed version: <<STUB>>/tween.js_v^16.3.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tween.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tween.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tween.js/src/Tween' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tween.js/src/Tween.js' {
  declare module.exports: $Exports<'tween.js/src/Tween'>;
}
