// flow-typed signature: e019d54f556b55083f66cb43f541c156
// flow-typed version: <<STUB>>/wdio-spec-reporter_v0.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-spec-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-spec-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-spec-reporter/build/reporter' {
  declare module.exports: any;
}

declare module 'wdio-spec-reporter/gruntfile' {
  declare module.exports: any;
}

declare module 'wdio-spec-reporter/lib/reporter' {
  declare module.exports: any;
}

declare module 'wdio-spec-reporter/test/fixtures' {
  declare module.exports: any;
}

declare module 'wdio-spec-reporter/test/reporter.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-spec-reporter/build/reporter.js' {
  declare module.exports: $Exports<'wdio-spec-reporter/build/reporter'>;
}
declare module 'wdio-spec-reporter/gruntfile.js' {
  declare module.exports: $Exports<'wdio-spec-reporter/gruntfile'>;
}
declare module 'wdio-spec-reporter/lib/reporter.js' {
  declare module.exports: $Exports<'wdio-spec-reporter/lib/reporter'>;
}
declare module 'wdio-spec-reporter/test/fixtures.js' {
  declare module.exports: $Exports<'wdio-spec-reporter/test/fixtures'>;
}
declare module 'wdio-spec-reporter/test/reporter.spec.js' {
  declare module.exports: $Exports<'wdio-spec-reporter/test/reporter.spec'>;
}
