// flow-typed signature: cfc6dcb8c5ad79631ab1e587ab74e05c
// flow-typed version: <<STUB>>/wdio-selenium-standalone-service_v0.0.7/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-selenium-standalone-service'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-selenium-standalone-service' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-selenium-standalone-service/build/launcher' {
  declare module.exports: any;
}

declare module 'wdio-selenium-standalone-service/build/utils/getFilePath' {
  declare module.exports: any;
}

declare module 'wdio-selenium-standalone-service/gruntfile' {
  declare module.exports: any;
}

declare module 'wdio-selenium-standalone-service/launcher' {
  declare module.exports: any;
}

declare module 'wdio-selenium-standalone-service/test/integration/main.spec' {
  declare module.exports: any;
}

declare module 'wdio-selenium-standalone-service/test/integration/wdio.conf' {
  declare module.exports: any;
}

declare module 'wdio-selenium-standalone-service/test/unit/utils/getFilePath.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-selenium-standalone-service/build/launcher.js' {
  declare module.exports: $Exports<'wdio-selenium-standalone-service/build/launcher'>;
}
declare module 'wdio-selenium-standalone-service/build/utils/getFilePath.js' {
  declare module.exports: $Exports<'wdio-selenium-standalone-service/build/utils/getFilePath'>;
}
declare module 'wdio-selenium-standalone-service/gruntfile.js' {
  declare module.exports: $Exports<'wdio-selenium-standalone-service/gruntfile'>;
}
declare module 'wdio-selenium-standalone-service/index' {
  declare module.exports: $Exports<'wdio-selenium-standalone-service'>;
}
declare module 'wdio-selenium-standalone-service/index.js' {
  declare module.exports: $Exports<'wdio-selenium-standalone-service'>;
}
declare module 'wdio-selenium-standalone-service/launcher.js' {
  declare module.exports: $Exports<'wdio-selenium-standalone-service/launcher'>;
}
declare module 'wdio-selenium-standalone-service/test/integration/main.spec.js' {
  declare module.exports: $Exports<'wdio-selenium-standalone-service/test/integration/main.spec'>;
}
declare module 'wdio-selenium-standalone-service/test/integration/wdio.conf.js' {
  declare module.exports: $Exports<'wdio-selenium-standalone-service/test/integration/wdio.conf'>;
}
declare module 'wdio-selenium-standalone-service/test/unit/utils/getFilePath.spec.js' {
  declare module.exports: $Exports<'wdio-selenium-standalone-service/test/unit/utils/getFilePath.spec'>;
}
