// flow-typed signature: 7051c264b7436272e8aa79af4ea5210b
// flow-typed version: <<STUB>>/wdio-jasmine-framework_v^0.2.19/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-jasmine-framework'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-jasmine-framework' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-jasmine-framework/build/adapter' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/build/reporter' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/gruntfile' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/lib/adapter' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/lib/reporter' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/adapter.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/error.handling.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/error.handling.async.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/error.handling.promise.async.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/error.handling.promise.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/error.handling.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/hook.failure.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/hooks.using.async.conf' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/hooks.using.custom.commands' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/hooks.using.native.promises' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/hooks.using.q.promises' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/hooks.using.wdio.commands' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/sample.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/sample2.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/sample3.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/sample4.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/sample5.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.async.failures.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.async.promise.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.async.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.fdescribe.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.fit.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.retry.async.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.retry.sync.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.sync.async.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.sync.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.xdescribe.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/fixtures/tests.xit.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/hooks.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/reporter.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/retry.spec' {
  declare module.exports: any;
}

declare module 'wdio-jasmine-framework/test/tests.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-jasmine-framework/build/adapter.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/build/adapter'>;
}
declare module 'wdio-jasmine-framework/build/reporter.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/build/reporter'>;
}
declare module 'wdio-jasmine-framework/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/coverage/lcov-report/prettify'>;
}
declare module 'wdio-jasmine-framework/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/coverage/lcov-report/sorter'>;
}
declare module 'wdio-jasmine-framework/gruntfile.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/gruntfile'>;
}
declare module 'wdio-jasmine-framework/lib/adapter.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/lib/adapter'>;
}
declare module 'wdio-jasmine-framework/lib/reporter.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/lib/reporter'>;
}
declare module 'wdio-jasmine-framework/test/adapter.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/adapter.spec'>;
}
declare module 'wdio-jasmine-framework/test/error.handling.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/error.handling.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/error.handling.async.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/error.handling.async.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/error.handling.promise.async.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/error.handling.promise.async.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/error.handling.promise.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/error.handling.promise.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/error.handling.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/error.handling.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/hook.failure.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/hook.failure.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/hooks.using.async.conf.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/hooks.using.async.conf'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/hooks.using.custom.commands.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/hooks.using.custom.commands'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/hooks.using.native.promises.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/hooks.using.native.promises'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/hooks.using.q.promises.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/hooks.using.q.promises'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/hooks.using.wdio.commands.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/hooks.using.wdio.commands'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/sample.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/sample.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/sample2.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/sample2.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/sample3.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/sample3.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/sample4.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/sample4.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/sample5.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/sample5.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.async.failures.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.async.failures.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.async.promise.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.async.promise.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.async.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.async.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.fdescribe.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.fdescribe.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.fit.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.fit.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.retry.async.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.retry.async.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.retry.sync.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.retry.sync.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.sync.async.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.sync.async.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.sync.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.sync.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.xdescribe.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.xdescribe.spec'>;
}
declare module 'wdio-jasmine-framework/test/fixtures/tests.xit.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/fixtures/tests.xit.spec'>;
}
declare module 'wdio-jasmine-framework/test/hooks.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/hooks.spec'>;
}
declare module 'wdio-jasmine-framework/test/reporter.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/reporter.spec'>;
}
declare module 'wdio-jasmine-framework/test/retry.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/retry.spec'>;
}
declare module 'wdio-jasmine-framework/test/tests.spec.js' {
  declare module.exports: $Exports<'wdio-jasmine-framework/test/tests.spec'>;
}
