// flow-typed signature: 8f2474910c068bace21ed2182c7869e8
// flow-typed version: <<STUB>>/webcola_v3.3.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webcola'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webcola' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webcola/Gruntfile' {
  declare module.exports: any;
}

declare module 'webcola/tasks/examples' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/cola' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/cola.min' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/index' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/linklengths' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/test/node_modules/qunitjs/qunit/qunit' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/test/qunit' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/test/tests' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/test/vpsctests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webcola/Gruntfile.js' {
  declare module.exports: $Exports<'webcola/Gruntfile'>;
}
declare module 'webcola/tasks/examples.js' {
  declare module.exports: $Exports<'webcola/tasks/examples'>;
}
declare module 'webcola/WebCola/cola.js' {
  declare module.exports: $Exports<'webcola/WebCola/cola'>;
}
declare module 'webcola/WebCola/cola.min.js' {
  declare module.exports: $Exports<'webcola/WebCola/cola.min'>;
}
declare module 'webcola/WebCola/index.js' {
  declare module.exports: $Exports<'webcola/WebCola/index'>;
}
declare module 'webcola/WebCola/linklengths.js' {
  declare module.exports: $Exports<'webcola/WebCola/linklengths'>;
}
declare module 'webcola/WebCola/test/node_modules/qunitjs/qunit/qunit.js' {
  declare module.exports: $Exports<'webcola/WebCola/test/node_modules/qunitjs/qunit/qunit'>;
}
declare module 'webcola/WebCola/test/qunit.js' {
  declare module.exports: $Exports<'webcola/WebCola/test/qunit'>;
}
declare module 'webcola/WebCola/test/tests.js' {
  declare module.exports: $Exports<'webcola/WebCola/test/tests'>;
}
declare module 'webcola/WebCola/test/vpsctests.js' {
  declare module.exports: $Exports<'webcola/WebCola/test/vpsctests'>;
}
