// flow-typed signature: 0c485d248bccf1e3c0e1994b44a95c84
// flow-typed version: <<STUB>>/worker-loader_v^0.7.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'worker-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'worker-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'worker-loader/createInlineWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'worker-loader/createInlineWorker.js' {
  declare module.exports: $Exports<'worker-loader/createInlineWorker'>;
}
declare module 'worker-loader/index' {
  declare module.exports: $Exports<'worker-loader'>;
}
declare module 'worker-loader/index.js' {
  declare module.exports: $Exports<'worker-loader'>;
}
