version: "2.1"

services:
  webknossos-tracingstore:
    image: scalableminds/webknossos-tracingstore:${DATASTORE_TAG}
    command:
      - -J-Xmx20G
      - -J-Xms1G
      - -J-XX:+UseG1GC
      - -jvm-debug
      - "5011"
      - -Dconfig.file=conf/docker.conf
      - $DATASTORE_ARGS_1
      - $DATASTORE_ARGS_2
    links:
      - fossildb
      - redis
    ports:
      - $TRACINGSTORE_PORT:9090
      - $TRACINGSTORE_DEBUG_PORT:5011
    user: $USER_UID:$USER_GID
    group_add:
      - $USER_GROUP_1
      - $USER_GROUP_2
    volumes:
      - ./tmp:/tmp
      - ./config/tracingstore-docker.conf:/webknossos-tracingstore/conf/docker.conf

  fossildb:
    image: scalableminds/fossildb:${FOSSILDB_TAG}
    command:
      - fossildb
      - -c
      - skeletons,skeletonUpdates,volumes,volumeData,volumeUpdates
    ports:
      - $FOSSILDB_PORT:7155
    user: $USER_UID:$USER_GID
    group_add:
      - $USER_GROUP_1
    volumes:
      - "./fossildb/data:/fossildb/data"
      - "./fossildb/backup:/fossildb/backup"

  fossildb-backup:
    image: scalableminds/fossildb-client:${FOSSILDB_TAG}
    command:
      - fossildb
      - backup
    links:
      - fossildb

  # Redis
  redis:
    image: redis:5.0-alpine
    command:
      - redis-server
      - --appendonly
      - "yes"
    volumes:
      - "./redis:/data"
