version: "2.1"

services:
  webknossos-datastore:
    image: scalableminds/webknossos-datastore:${DATASTORE_TAG}
    command:
      - -J-Xmx20G
      - -J-Xms1G
      - -J-XX:+UseG1GC
      - -jvm-debug
      - "5011"
      - -Dconfig.file=conf/docker.conf
      - $DATASTORE_ARGS_1
      - $DATASTORE_ARGS_2
    links:
      - redis
    ports:
      - $DATASTORE_PORT:9090
      - $DATASTORE_DEBUG_PORT:5011
    user: $USER_UID:$USER_GID
    group_add:
      - $USER_GROUP_1
      - $USER_GROUP_2
    volumes:
      - $BINARY_DATA_PATH:/webknossos-datastore/binaryData
      - ./tmp:/tmp
      - ./config/datastore-docker.conf:/webknossos-datastore/conf/docker.conf

  # Redis
  redis:
    image: redis:5.0-alpine
    command:
      - redis-server
      - --appendonly
      - "yes"
    volumes:
      - "./redis:/data"
