# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EditableMapping.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x45\x64itableMapping.proto\x12&com.scalableminds.webknossos.datastore\x1a\x0egeometry.proto\"1\n\x0f\x41gglomerateEdge\x12\x0e\n\x06source\x18\x01 \x02(\x03\x12\x0e\n\x06target\x18\x02 \x02(\x03\"\xc9\x01\n\x10\x41gglomerateGraph\x12\x10\n\x08segments\x18\x01 \x03(\x03\x12\x46\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x37.com.scalableminds.webknossos.datastore.AgglomerateEdge\x12G\n\tpositions\x18\x03 \x03(\x0b\x32\x34.com.scalableminds.webknossos.datastore.Vec3IntProto\x12\x12\n\naffinities\x18\x04 \x03(\x02\"\x83\x01\n\x16\x41gglomerateToGraphPair\x12\x15\n\ragglomerateId\x18\x01 \x02(\x03\x12R\n\x10\x61gglomerateGraph\x18\x02 \x02(\x0b\x32\x38.com.scalableminds.webknossos.datastore.AgglomerateGraph\"D\n\x18SegmentToAgglomeratePair\x12\x11\n\tsegmentId\x18\x01 \x02(\x03\x12\x15\n\ragglomerateId\x18\x02 \x02(\x03\"\x85\x02\n\x14\x45\x64itableMappingProto\x12\x17\n\x0f\x62\x61seMappingName\x18\x01 \x02(\t\x12^\n\x14segmentToAgglomerate\x18\x02 \x03(\x0b\x32@.com.scalableminds.webknossos.datastore.SegmentToAgglomeratePair\x12Z\n\x12\x61gglomerateToGraph\x18\x03 \x03(\x0b\x32>.com.scalableminds.webknossos.datastore.AgglomerateToGraphPair\x12\x18\n\x10\x63reatedTimestamp\x18\x04 \x02(\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EditableMapping_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AGGLOMERATEEDGE._serialized_start=81
  _AGGLOMERATEEDGE._serialized_end=130
  _AGGLOMERATEGRAPH._serialized_start=133
  _AGGLOMERATEGRAPH._serialized_end=334
  _AGGLOMERATETOGRAPHPAIR._serialized_start=337
  _AGGLOMERATETOGRAPHPAIR._serialized_end=468
  _SEGMENTTOAGGLOMERATEPAIR._serialized_start=470
  _SEGMENTTOAGGLOMERATEPAIR._serialized_end=538
  _EDITABLEMAPPINGPROTO._serialized_start=541
  _EDITABLEMAPPINGPROTO._serialized_end=802
# @@protoc_insertion_point(module_scope)
