# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EditableMappingInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x45\x64itableMappingInfo.proto\x12&com.scalableminds.webknossos.datastore\"f\n\x13\x45\x64itableMappingInfo\x12\x17\n\x0f\x62\x61seMappingName\x18\x01 \x02(\t\x12\x18\n\x10\x63reatedTimestamp\x18\x02 \x02(\x03\x12\x1c\n\x14largestAgglomerateId\x18\x03 \x02(\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EditableMappingInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EDITABLEMAPPINGINFO._serialized_start=69
  _EDITABLEMAPPINGINFO._serialized_end=171
# @@protoc_insertion_point(module_scope)
