# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egeometry.proto\x12&com.scalableminds.webknossos.datastore\"/\n\x0cVec3IntProto\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\t\n\x01z\x18\x03 \x02(\x05\"$\n\x0cVec2IntProto\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\"Z\n\x12ListOfVec3IntProto\x12\x44\n\x06values\x18\x01 \x03(\x0b\x32\x34.com.scalableminds.webknossos.datastore.Vec3IntProto\"2\n\x0fVec3DoubleProto\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\"8\n\nColorProto\x12\t\n\x01r\x18\x01 \x02(\x01\x12\t\n\x01g\x18\x02 \x02(\x01\x12\t\n\x01\x62\x18\x03 \x02(\x01\x12\t\n\x01\x61\x18\x04 \x02(\x01\"\x87\x01\n\x10\x42oundingBoxProto\x12\x45\n\x07topLeft\x18\x01 \x02(\x0b\x32\x34.com.scalableminds.webknossos.datastore.Vec3IntProto\x12\r\n\x05width\x18\x02 \x02(\x05\x12\x0e\n\x06height\x18\x03 \x02(\x05\x12\r\n\x05\x64\x65pth\x18\x04 \x02(\x05\"\xd6\x01\n\x15NamedBoundingBoxProto\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tisVisible\x18\x03 \x01(\x08\x12\x41\n\x05\x63olor\x18\x04 \x01(\x0b\x32\x32.com.scalableminds.webknossos.datastore.ColorProto\x12M\n\x0b\x62oundingBox\x18\x05 \x02(\x0b\x32\x38.com.scalableminds.webknossos.datastore.BoundingBoxProto\"8\n\x19\x41\x64\x64itionalCoordinateProto\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x05\"x\n\x13\x41\x64\x64itionalAxisProto\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05index\x18\x02 \x02(\x05\x12\x44\n\x06\x62ounds\x18\x03 \x02(\x0b\x32\x34.com.scalableminds.webknossos.datastore.Vec2IntProto')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geometry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEC3INTPROTO._serialized_start=58
  _VEC3INTPROTO._serialized_end=105
  _VEC2INTPROTO._serialized_start=107
  _VEC2INTPROTO._serialized_end=143
  _LISTOFVEC3INTPROTO._serialized_start=145
  _LISTOFVEC3INTPROTO._serialized_end=235
  _VEC3DOUBLEPROTO._serialized_start=237
  _VEC3DOUBLEPROTO._serialized_end=287
  _COLORPROTO._serialized_start=289
  _COLORPROTO._serialized_end=345
  _BOUNDINGBOXPROTO._serialized_start=348
  _BOUNDINGBOXPROTO._serialized_end=483
  _NAMEDBOUNDINGBOXPROTO._serialized_start=486
  _NAMEDBOUNDINGBOXPROTO._serialized_end=700
  _ADDITIONALCOORDINATEPROTO._serialized_start=702
  _ADDITIONALCOORDINATEPROTO._serialized_end=758
  _ADDITIONALAXISPROTO._serialized_start=760
  _ADDITIONALAXISPROTO._serialized_end=880
# @@protoc_insertion_point(module_scope)
