# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MetadataEntry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13MetadataEntry.proto\x12&com.scalableminds.webknossos.datastore\"w\n\x12MetadataEntryProto\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x13\n\x0bstringValue\x18\x02 \x01(\t\x12\x11\n\tboolValue\x18\x03 \x01(\x08\x12\x13\n\x0bnumberValue\x18\x04 \x01(\x01\x12\x17\n\x0fstringListValue\x18\x05 \x03(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MetadataEntry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METADATAENTRYPROTO._serialized_start=63
  _METADATAENTRYPROTO._serialized_end=182
# @@protoc_insertion_point(module_scope)
