/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scalableminds_webknossos_datastore_draco_NativeDracoDecoder */

#ifndef _Included_com_scalableminds_webknossos_datastore_draco_NativeDracoDecoder
#define _Included_com_scalableminds_webknossos_datastore_draco_NativeDracoDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_scalableminds_webknossos_datastore_draco_NativeDracoDecoder
 * Method:     decode
 * Signature:  ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_scalableminds_webknossos_datastore_draco_NativeDracoDecoder_decode
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
