/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scalableminds_webknossos_datastore_NativeArrayAdder */

#ifndef _Included_com_scalableminds_webknossos_datastore_NativeArrayAdder
#define _Included_com_scalableminds_webknossos_datastore_NativeArrayAdder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_scalableminds_webknossos_datastore_NativeArrayAdder
 * Method:     add
 * Signature:  ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_scalableminds_webknossos_datastore_NativeArrayAdder_add
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
