/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scalableminds_webknossos_datastore_NativeDracoToStlConverter */

#ifndef _Included_com_scalableminds_webknossos_datastore_NativeDracoToStlConverter
#define _Included_com_scalableminds_webknossos_datastore_NativeDracoToStlConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_scalableminds_webknossos_datastore_NativeDracoToStlConverter
 * Method:     dracoToStl
 * Signature:  ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_scalableminds_webknossos_datastore_NativeDracoToStlConverter_dracoToStl
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
