/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scalableminds_webknossos_datastore_NativeAdder */

#ifndef _Included_com_scalableminds_webknossos_datastore_NativeAdder
#define _Included_com_scalableminds_webknossos_datastore_NativeAdder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_scalableminds_webknossos_datastore_NativeAdder
 * Method:     add
 * Signature:  (II)I
 */
JNIEXPORT jint JNICALL Java_com_scalableminds_webknossos_datastore_NativeAdder_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
