import type { ServerVolumeTracing } from "types/api_types";
const a: ServerVolumeTracing = {
  userBoundingBoxes: [],
  mags: [
    { x: 1, y: 1, z: 1 },
    { x: 2, y: 2, z: 2 },
    { x: 4, y: 4, z: 4 },
    { x: 8, y: 8, z: 8 },
    { x: 16, y: 16, z: 16 },
  ],
  segments: [],
  segmentGroups: [],
  editPositionAdditionalCoordinates: [],
  additionalAxes: [],
  userStates: [],
  boundingBox: { topLeft: { x: 0, y: 0, z: 0 }, width: 512, height: 512, depth: 256 },
  createdTimestamp: 1762190586109,
  editPosition: { x: 256, y: 256, z: 128 },
  editRotation: { x: 0, y: 0, z: 0 },
  elementClass: "uint32",
  largestSegmentId: 0,
  zoomLevel: 1,
  hasSegmentIndex: true,
  volumeBucketDataHasChanged: false,
  id: "b8517f7f-0b80-4a07-a6cf-9ad8dc9591a1",
  typ: "Volume",
};
