import type { APIAnnotationWithTask } from "types/api_types";
const a: APIAnnotationWithTask = {
  modified: 1762190595245,
  state: "Active",
  isLockedByOwner: false,
  id: "6908e5030d0000d100d8a646",
  name: "",
  description: "",
  viewConfiguration: null,
  typ: "Task",
  task: {
    id: "6908e5030d0000e000d8a644",
    projectId: "58135bfd2faeb3190181c05a",
    projectName: "Test_Project4",
    team: "team_X1",
    type: {
      id: "570b9f4c2a7c0e4c008da6ee",
      summary: "ek_0563_BipolarCells",
      description: "Check those cells out!",
      teamId: "570b9f4b2a7c0e3b008da6ec",
      teamName: "team_X1",
      settings: {
        allowedModes: ["orthogonal", "oblique", "flight"],
        branchPointsAllowed: true,
        somaClickingAllowed: true,
        volumeInterpolationAllowed: false,
        mergerMode: false,
        magRestrictions: {},
      },
      recommendedConfiguration: null,
      tracingType: "skeleton",
    },
    datasetName: "confocal-multi_knossos",
    datasetId: "59e9cfbdba632ac2ab8b23b3",
    neededExperience: { domain: "abc", value: 1 },
    created: 1762190595136,
    status: { pending: 2, active: 1, finished: 0 },
    script: null,
    tracingTime: null,
    creationInfo: null,
    boundingBox: null,
    editPosition: [1, 2, 3],
    editRotation: [4, 5, 6],
  },
  stats: {},
  restrictions: { allowAccess: true, allowUpdate: true, allowFinish: true, allowDownload: true },
  annotationLayers: [
    {
      tracingId: "6341d452-6c56-4d82-bba5-ed40e60513b7",
      typ: "Skeleton",
      name: "Skeleton",
      stats: {},
    },
  ],
  datasetId: "59e9cfbdba632ac2ab8b23b3",
  dataSetName: "confocal-multi_knossos",
  organization: "Organization_X",
  dataStore: {
    name: "localhost",
    url: "http://localhost:9000",
    allowsUpload: true,
    jobsSupportedByAvailableWorkers: [],
    jobsEnabled: false,
  },
  tracingStore: { name: "localhost", url: "http://localhost:9000" },
  visibility: "Internal",
  settings: {
    allowedModes: ["orthogonal", "oblique", "flight"],
    branchPointsAllowed: true,
    somaClickingAllowed: true,
    volumeInterpolationAllowed: false,
    mergerMode: false,
    magRestrictions: {},
  },
  tracingTime: null,
  teams: [],
  tags: ["confocal-multi_knossos", "skeleton"],
  user: {
    id: "570b9f4d2a7c0e4d008da6ef",
    email: "user_a@scalableminds.com",
    firstName: "user_A",
    lastName: "last_A",
    isAdmin: true,
    isDatasetManager: true,
    isAnonymous: false,
    teams: [
      { id: "570b9f4b2a7c0e3b008da6ec", name: "team_X1", isTeamManager: true },
      { id: "59882b370d889b84020efd3f", name: "team_X3", isTeamManager: false },
      { id: "59882b370d889b84020efd6f", name: "team_X4", isTeamManager: true },
    ],
  },
  owner: {
    id: "570b9f4d2a7c0e4d008da6ef",
    email: "user_a@scalableminds.com",
    firstName: "user_A",
    lastName: "last_A",
    isAdmin: true,
    isDatasetManager: true,
    isAnonymous: false,
    teams: [
      { id: "570b9f4b2a7c0e3b008da6ec", name: "team_X1", isTeamManager: true },
      { id: "59882b370d889b84020efd3f", name: "team_X3", isTeamManager: false },
      { id: "59882b370d889b84020efd6f", name: "team_X4", isTeamManager: true },
    ],
  },
  contributors: [],
  othersMayEdit: false,
};
