import type { ServerTracing } from "types/api_types";
const a: Array<ServerTracing> = [
  {
    trees: [],
    treeGroups: [],
    userBoundingBoxes: [],
    editPositionAdditionalCoordinates: [],
    additionalAxes: [],
    userStates: [],
    createdTimestamp: 1762190586235,
    editPosition: { x: 256, y: 256, z: 128 },
    editRotation: { x: 0, y: 0, z: 0 },
    zoomLevel: 2,
    storedWithExternalTreeBodies: true,
    id: "7d99addd-ea63-444d-b1ac-eb5c4dada9ac",
    typ: "Skeleton",
  },
  {
    userBoundingBoxes: [],
    mags: [
      { x: 1, y: 1, z: 1 },
      { x: 2, y: 2, z: 2 },
      { x: 4, y: 4, z: 4 },
      { x: 8, y: 8, z: 8 },
      { x: 16, y: 16, z: 16 },
    ],
    segments: [],
    segmentGroups: [],
    editPositionAdditionalCoordinates: [],
    additionalAxes: [],
    userStates: [],
    boundingBox: { topLeft: { x: 0, y: 0, z: 0 }, width: 512, height: 512, depth: 256 },
    createdTimestamp: 1762190586253,
    editPosition: { x: 256, y: 256, z: 128 },
    editRotation: { x: 0, y: 0, z: 0 },
    elementClass: "uint32",
    largestSegmentId: 0,
    zoomLevel: 1,
    hasSegmentIndex: true,
    volumeBucketDataHasChanged: false,
    id: "af746f9d-1415-48cf-9908-e88748f9c226",
    typ: "Volume",
  },
];
