version: '2.1'

services:
  webknossos-datastore:
    image: scalableminds/webknossos-datastore:${DOCKER_TAG:-master}
    ports:
      - "9090:9090"

  base:
    image: scalableminds/sbt:$SBT_VERSION_TAG
    environment:
      - USER_NAME=${USER_NAME:-sbt-user}
      - USER_UID
      - USER_GID
      - TZ
    working_dir: /home/${USER_NAME:-sbt-user}/webknossos-datastore
    volumes:
      - ".:/home/${USER_NAME:-sbt-user}/webknossos-datastore"
      - "${DOCKER_CACHE_PREFIX:-~}/.m2:/home/${USER_NAME:-sbt-user}/.m2"
      - "${DOCKER_CACHE_PREFIX:-~}/.ivy2:/home/${USER_NAME:-sbt-user}/.ivy2"
      - "${DOCKER_CACHE_PREFIX:-~}/.sbt:/home/${USER_NAME:-sbt-user}/.sbt"

  dev:
    extends:
      service: base
    ports:
      - "9090:9090"
      - "5005:5005"
    command: >
      bash -c
      "sbt -v -d -jvm-debug 5005 \"run
      -Djava.net.preferIPv4Stack=true
      -Dhttp.address=0.0.0.0
      -Dhttp.port=$${PORT}
      \""
    environment:
      - PORT=9090
    stdin_open: true

  prod:
    extends:
      service: dev
    command: >
      bash -c
      "sbt -v -d -jvm-debug 5005 \"testProd
      -Djava.net.preferIPv4Stack=true
      -Dhttp.address=0.0.0.0
      -Dhttp.port=$${PORT}
      \""
