version: 2
jobs:
  build_test_push:
    machine: true
    environment:
      SBT_VERSION_TAG: sbt-0.13.15_mongo-3.2.17_node-8.x_jdk-8
      USER_NAME: circleci
      USER_UID: 1001
      USER_GID: 1001
    steps:
      - checkout
      - run:
          name: Pull sbt docker image
          command: docker pull scalableminds/sbt:$SBT_VERSION_TAG
      - run:
          name: Prepare dependency folders
          command: mkdir -p ~/.m2 ~/.ivy2 ~/.sbt ~/.yarn-cache
      - restore_cache:
          keys:
            - cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}
            - cache-{{ checksum ".circleci/cache_version" }}-master
      - run:
          name: Build code (sbt)
          command: docker-compose run base sbt clean compile stage

      - save_cache:
          key: cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}
          paths:
            - "~/.m2"
            - "~/.ivy2"
            - "~/.sbt"
            - "~/.yarn-cache"

      - run:
          name: Build docker image
          command: docker build --pull -t scalableminds/webknossos-datastore:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} .
      - run:
          name: Run smoke test
          command: |
            set -x
            DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up -d webknossos-datastore
            sleep 10
            curl --retry 3 --max-time 15 -v http://localhost:9090/data/health
            docker-compose down --volumes --remove-orphans
      - run:
          name: Push docker images
          command: |
            set -x
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag scalableminds/webknossos-datastore:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} scalableminds/webknossos-datastore:${CIRCLE_BRANCH}
            docker push scalableminds/webknossos-datastore:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/webknossos-datastore:${CIRCLE_BRANCH}
            docker logout
workflows:
  version: 2
  default:
    jobs:
      - build_test_push
