name: Auto Assign Issues to Project
on:
  issues:
    types: [opened]

jobs:
  assign_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to GitHub projects
        uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/orgs/scalableminds/projects/6
          github-token: ${{ secrets.PROJECT_GITHUB_TOKEN }}
